const products = [
  {
    name: "Beefsteak Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/beefsteak-tomato.webp",
  },
  {
    name: "Red Delicious Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/red-delicious-apple.webp",
  },
  {
    name: "Strawberries",
    category: "RedFruitsBerry",
    subCategory: "Berry",
    photo: "/images/product-images/strawberry.webp",
  },
  {
    name: "Eggs",
    category: "PoultryChickenEgg",
    subCategory: "egg",
    photo: "/images/product-images/egg.webp",
  },
  {
    name: "Basil",
    category: "herbs and spices",
    subCategory: "green",
    photo: "/images/product-images/basil.webp",
  },
  {
    name: "Blood Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/blood-orange.webp",
  },
  {
    name: "Baby Spinach",
    category: "Vegetables",
    subCategory: "Spinach",
    photo: "/images/product-images/baby-spinach.webp",
  },
  {
    name: "Elk",
    category: "Meats",
    subCategory: "",
    photo: "/images/product-images/Elk.webp",
  },
  {
    name: "Cherry Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/cherry-tomato.webp",
  },
  {
    name: "Heirloom Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/hierloom-tomato.webp",
  },
  {
    name: "Roma Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/roma-tomato.webp",
  },
  {
    name: "Grape Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/grape-tomato.webp",
  },
  {
    name: "San Marzano Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    name: "Brandywine Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    name: "Green Zebra Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    name: "Cherokee Purple Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    name: "Yellow Pear Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    name: "Black Krim Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    name: "Amish Paste Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    name: "Celebrity Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    name: "Early Girl Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    name: "Big Boy Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    name: "Sun Gold Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    name: "Sweet Million Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    name: "Mortgage Lifter Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    name: "Pineapple Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    name: "Supersweet 100 Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    name: "Black Cherry Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    name: "Campari Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    name: "Kumato Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    name: "Principe Borghese Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    name: "Rutgers Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    name: "Paul Robeson Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    name: "Arkansas Traveler Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    name: "Persimmon Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    name: "Costoluto Genovese Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    name: "Striped German Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    name: "Golden Jubilee Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    name: "Green Giant Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    name: "Orange Wellington Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    name: "Pink Brandywine Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    name: "Red Currant Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    name: "Snow White Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    name: "Yellow Brandywine Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    name: "Black Pineapple Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    name: "Blondkopfchen Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    name: "Caspian Pink Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    name: "German Johnson Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    name: "Hillbilly Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    name: "Indigo Rose Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    name: "Japanese Black Trifele Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    name: "Kellogg's Breakfast Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    name: "Marianna's Peace Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    name: "Old German Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    name: "Purple Calabash Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    name: "Rose de Berne Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    name: "Tigerella Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    name: "Valencia Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  ///////////////////////////////////////////////////////

  {
    name: "Granny Smith Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/granny-smith.webp",
  },
  {
    name: "Fuji Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/fuji-apple.webp",
  },
  {
    name: "Gala Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/gala-apple.webp",
  },
  {
    name: "Honeycrisp Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/honey-crisp-apple.webp",
  },
  {
    name: "Golden Delicious Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/golden-delicious-apple.webp",
  },
  {
    name: "Pink Lady Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    name: "McIntosh Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    name: "Braeburn Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    name: "Jonagold Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    name: "Cortland Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    name: "Empire Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    name: "Arkansas Black Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    name: "Rome Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    name: "Ambrosia Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    name: "Jazz Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    name: "Cameo Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    name: "Opal Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    name: "Winesap Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    name: "Mutsu Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    name: "York Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    name: "Pink Pearl Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    name: "Liberty Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    name: "Ginger Gold Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    name: "Paula Red Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    name: "Northern Spy Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    name: "Gravenstein Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    name: "Jonathan Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    name: "SunCrisp Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    name: "Crimson Crisp Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    name: "EverCrisp Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    name: "SnowSweet Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    name: "Snowdrift Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    name: "SweeTango Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    name: "Wine Crisp Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    name: "Ruby Frost Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    name: "Autumn Glory Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    name: "Cosmic Crisp Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    name: "Smitten Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    name: "Kiku Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    name: "Envy Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    name: "Snapdragon Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    name: "Pacific Rose Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    name: "Kanzi Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    name: "Ambri Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    name: "SweeTango Tango Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    name: "SweeTango Zester Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    name: "Sweetie Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    name: "Sweetie Pie Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    name: "Sweetie Treat Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  ///////////////////////////////////////////////////////
  {
    name: "Anjou Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/anjou-pear.webp",
  },
  {
    name: "Bartlett Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/bartlett-pear.webp",
  },
  {
    name: "Bosc Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/bosc-pear.webp",
  },
  {
    name: "Comice Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/comice-pear.webp",
  },
  {
    name: "Forelle Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/forelle-pear.webp",
  },
  {
    name: "Seckel Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    name: "Concorde Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    name: "Starkrimson Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    name: "Asian Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    name: "Forelle Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    name: "Red Anjou Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    name: "Green Anjou Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    name: "Concorde Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    name: "Starkrimson Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    name: "Comice Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    name: "Red Bartlett Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    name: "Brown Bartlett Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    name: "Green Bartlett Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    name: "Red Sensation Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    name: "Hosui Asian Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    name: "Shinseiki Asian Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    name: "20th Century Asian Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    name: "Ya Li Asian Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    name: "Harrow Sweet Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    name: "Magness Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    name: "Moonglow Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    name: "Blake's Pride Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    name: "Harrow Delight Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    name: "Summercrisp Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    name: "Harrow Crisp Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    name: "Orcas Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    name: "Rescue Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    name: "Moonglow Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    name: "D'Anjou Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    name: "Red D'Anjou Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    name: "Green D'Anjou Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    name: "Max Red Bartlett Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    name: "Maxie Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    name: "Pineapple Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    name: "Warren Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    name: "Warren Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    name: "Ayers Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    name: "Le Conte Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    name: "Kieffer Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    name: "Blake's Pride Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    name: "Luscious Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    name: "Orca Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    name: "Olympic Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    name: "Navel Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/navel-orange.webp",
  },
  {
    name: "Valencia Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/valencia_orange.webp",
  },

  {
    name: "Cara Cara Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/orange.webp",
  },
  {
    name: "Seville Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/orange.webp",
  },
  {
    name: "Mandarin Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/mandarin-orange.webp",
  },
  {
    name: "Satsuma Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/orange.webp",
  },
  {
    name: "Clementine Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/orange.webp",
  },
  {
    name: "Tangerine Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/orange.webp",
  },
  {
    name: "Moro Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/orange.webp",
  },
  {
    name: "Ambersweet Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/orange.webp",
  },
  {
    name: "Temple Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/orange.webp",
  },
  {
    name: "Sour Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/orange.webp",
  },
  {
    name: "Clementine Mandarin Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/orange.webp",
  },
  {
    name: "Dancy Tangerine Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/orange.webp",
  },
  {
    name: "Nova Tangerine Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/orange.webp",
  },
  {
    name: "Sunburst Tangerine Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/orange.webp",
  },
  {
    name: "Fairchild Tangerine Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/orange.webp",
  },
  {
    name: "Robinson Tangerine Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/orange.webp",
  },
  {
    name: "Orlando Tangelo Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/orange.webp",
  },
  {
    name: "Minneola Tangelo Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/orange.webp",
  },
  {
    name: "Ugli Fruits",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/orange.webp",
  },
  {
    name: "Tangor Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/orange.webp",
  },
  {
    name: "Lemonade Lemon Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/orange.webp",
  },
  {
    name: "Sour Lemon Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/orange.webp",
  },
  {
    name: "Tangelo Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/orange.webp",
  },
  {
    name: "Seminole Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/orange.webp",
  },
  {
    name: "Pineapple Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/orange.webp",
  },
  {
    name: "Bitter Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/orange.webp",
  },
  {
    name: "Trifoliate Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/orange.webp",
  },
  {
    name: "Cleopatra Mandarin Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/orange.webp",
  },
  {
    name: "Kumquat Mandarin Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/orange.webp",
  },
  {
    name: "Willowleaf Mandarin Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/orange.webp",
  },
  {
    name: "Kinnow Mandarin Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/orange.webp",
  },
  {
    name: "Sunki Mandarin Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/orange.webp",
  },
  {
    name: "Ponkan Mandarin Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/orange.webp",
  },
  {
    name: "Dekopon Mandarin Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/orange.webp",
  },
  {
    name: "Yuzu Mandarin Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/orange.webp",
  },
  {
    name: "Khasi Mandarin Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/orange.webp",
  },
  {
    name: "Clementine Hybrid Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/orange.webp",
  },
  {
    name: "Satsuma Hybrid Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/orange.webp",
  },
  {
    name: "Tangor Hybrid Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/orange.webp",
  },
  {
    name: "Tangelo Hybrid Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/orange.webp",
  },
  {
    name: "Clementine Hybrid Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/orange.webp",
  },
  {
    name: "Nova Tangelo Hybrid Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/orange.webp",
  },
  {
    name: "Ortanique Hybrid Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/orange.webp",
  },
  {
    name: "Nantes Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/nantes-carrot.webp",
  },
  {
    name: "Danvers Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/danvers-carrot.webp",
  },
  {
    name: "Imperator Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/imperator-carrot.webp",
  },
  {
    name: "Chantenay Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/carrot.webp",
  },
  {
    name: "Paris Market Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/carrot.webp",
  },
  {
    name: "Babette Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/carrot.webp",
  },
  {
    name: "Little Finger Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/carrot.webp",
  },
  {
    name: "Scarlet Nantes Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/carrot.webp",
  },
  {
    name: "Kuroda Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/carrot.webp",
  },
  {
    name: "Atomic Red Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/carrot.webp",
  },
  {
    name: "Cosmic Purple Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/carrot.webp",
  },
  {
    name: "Solar Yellow Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/carrot.webp",
  },
  {
    name: "Lunar White Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/carrot.webp",
  },
  {
    name: "Bolero Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/carrot.webp",
  },
  {
    name: "Thumbelina Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/carrot.webp",
  },
  {
    name: "Dragon Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/carrot.webp",
  },
  {
    name: "Purple Haze Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/carrot.webp",
  },
  {
    name: "Atomic Red Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/carrot.webp",
  },
  {
    name: "Cosmic Purple Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/carrot.webp",
  },
  {
    name: "Solar Yellow Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/carrot.webp",
  },
  {
    name: "Lunar White Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/carrot.webp",
  },
  {
    name: "Bolero Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/carrot.webp",
  },
  {
    name: "Thumbelina Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/carrot.webp",
  },
  {
    name: "Dragon Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/carrot.webp",
  },
  {
    name: "Purple Haze Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/carrot.webp",
  },
  {
    name: "Yellowstone Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/carrot.webp",
  },
  {
    name: "Red Samurai Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/carrot.webp",
  },
  {
    name: "Sweet Treat Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/carrot.webp",
  },
  {
    name: "Sugarsnax Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/carrot.webp",
  },
  {
    name: "Kaleidoscope Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/carrot.webp",
  },
  {
    name: "Purple Elite Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/carrot.webp",
  },
  {
    name: "Merida Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/carrot.webp",
  },
  {
    name: "Sugarsnax Hybrid Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/carrot.webp",
  },
  {
    name: "Babette Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/carrot.webp",
  },
  {
    name: "Kinko Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/carrot.webp",
  },
  {
    name: "Purple 68 Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/purple-68-carrot.webp",
  },
  {
    name: "Amsterdam Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/carrot.webp",
  },
  {
    name: "Sweetness III Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/sweetness-III-carrot.webp",
  },
  {
    name: "Sugarsnax Hybrid Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/carrot.webp",
  },
  {
    name: "Hercules Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/carrot.webp",
  },
  {
    name: "Kaleidoscope Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/carrot.webp",
  },
  {
    name: "Purple Elite Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/carrot.webp",
  },
  {
    name: "Merida Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/carrot.webp",
  },
  {
    name: "Babette Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/carrot.webp",
  },
  {
    name: "Bloomsdale Spinach",
    category: "Vegetables",
    subCategory: "Spinach",
    photo: "/images/product-images/bloomsdale-spinach.webp",
  },

  {
    name: "Savoy Spinach",
    category: "Vegetables",
    subCategory: "Spinach",
    photo: "/images/product-images/spinach.webp",
  },
  {
    name: "Malabar Spinach",
    category: "Vegetables",
    subCategory: "Spinach",
    photo: "/images/product-images/malabar-spinach.webp",
  },
  {
    name: "Red Kitten Spinach",
    category: "Vegetables",
    subCategory: "Spinach",
    photo: "/images/product-images/spinach.webp",
  },
  {
    name: "Tyee Spinach",
    category: "Vegetables",
    subCategory: "Spinach",
    photo: "/images/product-images/spinach.webp",
  },
  {
    name: "Space Spinach",
    category: "Vegetables",
    subCategory: "Spinach",
    photo: "/images/product-images/spinach.webp",
  },
  {
    name: "Giant Winter Spinach",
    category: "Vegetables",
    subCategory: "Spinach",
    photo: "/images/product-images/spinach.webp",
  },
  {
    name: "Matador Spinach",
    category: "Vegetables",
    subCategory: "Spinach",
    photo: "/images/product-images/spinach.webp",
  },
  {
    name: "Corvair Spinach",
    category: "Vegetables",
    subCategory: "Spinach",
    photo: "/images/product-images/spinach.webp",
  },
  {
    name: "Regiment Spinach",
    category: "Vegetables",
    subCategory: "Spinach",
    photo: "/images/product-images/spinach.webp",
  },
  {
    name: "Space Spinach",
    category: "Vegetables",
    subCategory: "Spinach",
    photo: "/images/product-images/spinach.webp",
  },
  {
    name: "Reflect Spinach",
    category: "Vegetables",
    subCategory: "Spinach",
    photo: "/images/product-images/spinach.webp",
  },
  {
    name: "Avenger Spinach",
    category: "Vegetables",
    subCategory: "Spinach",
    photo: "/images/product-images/spinach.webp",
  },
  {
    name: "Coronet Spinach",
    category: "Vegetables",
    subCategory: "Spinach",
    photo: "/images/product-images/spinach.webp",
  },
  {
    name: "Catalyst Spinach",
    category: "Vegetables",
    subCategory: "Spinach",
    photo: "/images/product-images/spinach.webp",
  },
  {
    name: "Giant Nobel Spinach",
    category: "Vegetables",
    subCategory: "Spinach",
    photo: "/images/product-images/spinach.webp",
  },
  {
    name: "Red Cardinal Spinach",
    category: "Vegetables",
    subCategory: "Spinach",
    photo: "/images/product-images/spinach.webp",
  },
  {
    name: "Vienna Spinach",
    category: "Vegetables",
    subCategory: "Spinach",
    photo: "/images/product-images/spinach.webp",
  },
  {
    name: "Nobel Giant Spinach",
    category: "Vegetables",
    subCategory: "Spinach",
    photo: "/images/product-images/spinach.webp",
  },
  {
    name: "Calabrese Broccoli",
    category: "Vegetables",
    subCategory: "Broccoli",
    photo: "/images/product-images/calabrese-broccoli.webp",
  },
  {
    name: "Sprouting Broccoli",
    category: "Vegetables",
    subCategory: "Broccoli",
    photo: "/images/product-images/broccoli.webp",
  },
  {
    name: "Romanesco Broccoli",
    category: "Vegetables",
    subCategory: "Broccoli",
    photo: "/images/product-images/broccoli.webp",
  },
  {
    name: "Purple Sprouting Broccoli",
    category: "Vegetables",
    subCategory: "Broccoli",
    photo: "/images/product-images/broccoli.webp",
  },
  {
    name: "Broccolini",
    category: "Vegetables",
    subCategory: "Broccoli",
    photo: "/images/product-images/broccoli.webp",
  },
  {
    name: "Broccoflower",
    category: "Vegetables",
    subCategory: "Broccoli",
    photo: "/images/product-images/broccoli.webp",
  },
  {
    name: "Baby Broccoli",
    category: "Vegetables",
    subCategory: "Broccoli",
    photo: "/images/product-images/broccoli.webp",
  },
  {
    name: "Purple Broccoli",
    category: "Vegetables",
    subCategory: "Broccoli",
    photo: "/images/product-images/broccoli.webp",
  },
  {
    name: "White Sprouting Broccoli",
    category: "Vegetables",
    subCategory: "Broccoli",
    photo: "/images/product-images/broccoli.webp",
  },
  {
    name: "Belstar Broccoli",
    category: "Vegetables",
    subCategory: "Broccoli",
    photo: "/images/product-images/broccoli.webp",
  },
  {
    name: "Green Magic Broccoli",
    category: "Vegetables",
    subCategory: "Broccoli",
    photo: "/images/product-images/broccoli.webp",
  },
  {
    name: "Imperial Broccoli",
    category: "Vegetables",
    subCategory: "Broccoli",
    photo: "/images/product-images/broccoli.webp",
  },
  {
    name: "Paragon Broccoli",
    category: "Vegetables",
    subCategory: "Broccoli",
    photo: "/images/product-images/broccoli.webp",
  },
  {
    name: "Arcadia Broccoli",
    category: "Vegetables",
    subCategory: "Broccoli",
    photo: "/images/product-images/broccoli.webp",
  },
  {
    name: "Green Goliath Broccoli",
    category: "Vegetables",
    subCategory: "Broccoli",
    photo: "/images/product-images/broccoli.webp",
  },
  {
    name: "Marathon Broccoli",
    category: "Vegetables",
    subCategory: "Broccoli",
    photo: "/images/product-images/broccoli.webp",
  },
  {
    name: "Packman Broccoli",
    category: "Vegetables",
    subCategory: "Broccoli",
    photo: "/images/product-images/broccoli.webp",
  },
  {
    name: "Belstar Broccoli",
    category: "Vegetables",
    subCategory: "Broccoli",
    photo: "/images/product-images/broccoli.webp",
  },
  {
    name: "Green Magic Broccoli",
    category: "Vegetables",
    subCategory: "Broccoli",
    photo: "/images/product-images/broccoli.webp",
  },
  {
    name: "Imperial Broccoli",
    category: "Vegetables",
    subCategory: "Broccoli",
    photo: "/images/product-images/broccoli.webp",
  },
  {
    name: "Concord Grapes",
    category: "Fruits",
    subCategory: "Grape",
    photo: "/images/product-images/concord-grape.webp",
  },
  {
    name: "Thompson Seedless Grapes",
    category: "Fruits",
    subCategory: "Grape",
    photo: "/images/product-images/thompson-seedless-grape.webp",
  },
  {
    name: "Green Grapes",
    category: "Fruits",
    subCategory: "Grape",
    photo: "/images/product-images/thompson-seedless-grape.webp",
  },
  {
    name: "Red Globe Grapes",
    category: "Fruits",
    subCategory: "Grape",
    photo: "/images/product-images/red-globe-grape.webp",
  },
  {
    name: "Red Grapes",
    category: "Fruits",
    subCategory: "Grape",
    photo: "/images/product-images/red-globe-grape.webp",
  },
  {
    name: "Crimson Seedless Grapes",
    category: "Fruits",
    subCategory: "Grape",
    photo: "/images/product-images/crimson-seedless-grape.webp",
  },
  {
    name: "Chardonnay Grapes",
    category: "Fruits",
    subCategory: "Grape",
    photo: "/images/product-images/crimson-seedless-grape.webp",
  },
  {
    name: "Cabernet Sauvignon Grapes",
    category: "Fruits",
    subCategory: "Grape",
    photo: "/images/product-images/crimson-seedless-grape.webp",
  },
  {
    name: "Pinot Noir Grapes",
    category: "Fruits",
    subCategory: "Grape",
    photo: "/images/product-images/crimson-seedless-grape.webp",
  },
  {
    name: "Muscat Grapes",
    category: "Fruits",
    subCategory: "Grape",
    photo: "/images/product-images/crimson-seedless-grape.webp",
  },
  {
    name: "Merlot Grapes",
    category: "Fruits",
    subCategory: "Grape",
    photo: "/images/product-images/crimson-seedless-grape.webp",
  },
  {
    name: "Zinfandel Grapes",
    category: "Fruits",
    subCategory: "Grape",
    photo: "/images/product-images/crimson-seedless-grape.webp",
  },
  {
    name: "Cabernet Franc Grapes",
    category: "Fruits",
    subCategory: "Grape",
    photo: "/images/product-images/crimson-seedless-grape.webp",
  },
  {
    name: "Eureka Lemons",
    category: "Fruits",
    subCategory: "lemon",
    photo: "/images/product-images/lemon.webp",
  },
  {
    name: "Lisbon Lemons",
    category: "Fruits",
    subCategory: "lemon",
    photo: "/images/product-images/lemon.webp",
  },
  {
    name: "Meyer Lemons",
    category: "Fruits",
    subCategory: "lemon",
    photo: "/images/product-images/lemon.webp",
  },
  {
    name: "Ponderosa Lemons",
    category: "Fruits",
    subCategory: "lemon",
    photo: "/images/product-images/lemon.webp",
  },
  {
    name: "Lunario Lemon",
    category: "Fruits",
    subCategory: "lemon",
    photo: "/images/product-images/lemon.webp",
  },
  {
    name: "Variegated Pink Lemon",
    category: "Fruits",
    subCategory: "lemon",
    photo: "/images/product-images/lemon.webp",
  },
  {
    name: "Yen Ben Lemon",
    category: "Fruits",
    subCategory: "lemon",
    photo: "/images/product-images/lemon.webp",
  },
  {
    name: "Femminello St. Teresa Lemon",
    category: "Fruits",
    subCategory: "lemon",
    photo: "/images/product-images/lemon.webp",
  },
  {
    name: "Verna Lemon",
    category: "Fruits",
    subCategory: "lemon",
    photo: "/images/product-images/lemon.webp",
  },
  {
    name: "Bush Lemon",
    category: "Fruits",
    subCategory: "lemon",
    photo: "/images/product-images/lemon.webp",
  },
  {
    name: "Armenian Cucumbers",
    category: "Vegetables",
    subCategory: "cucumber",
    photo: "/images/product-images/armeniancucumber.webp",
  },
  {
    name: "English Telegraph Cucumbers",
    category: "Vegetables",
    subCategory: "cucumber",
    photo: "/images/product-images/english-telegraph-cucumber.webp",
  },
  {
    name: "Persian Cucumbers",
    category: "Vegetables",
    subCategory: "cucumber",
    photo: "/images/product-images/persian-cucumber.webp",
  },
  {
    name: "Lemon Cucumbers",
    category: "Vegetables",
    subCategory: "cucumber",
    photo: "/images/product-images/cucumber.webp",
  },
  {
    name: "Japanese Cucumbers",
    category: "Vegetables",
    subCategory: "cucumber",
    photo: "/images/product-images/cucumber.webp",
  },
  {
    name: "Kirby Cucumbers",
    category: "Vegetables",
    subCategory: "cucumber",
    photo: "/images/product-images/cucumber.webp",
  },
  {
    name: "Marketmore Cucumbers",
    category: "Vegetables",
    subCategory: "cucumber",
    photo: "/images/product-images/cucumber.webp",
  },
  {
    name: "National Pickling Cucumbers",
    category: "Vegetables",
    subCategory: "cucumber",
    photo: "/images/product-images/cucumber.webp",
  },
  {
    name: "Straight Eight Cucumbers",
    category: "Vegetables",
    subCategory: "cucumber",
    photo: "/images/product-images/cucumber.webp",
  },
  {
    name: "Bush Crop Cucumbers",
    category: "Vegetables",
    subCategory: "cucumber",
    photo: "/images/product-images/cucumber.webp",
  },
  {
    name: "Parisian Pickling Cucumbers",
    category: "Vegetables",
    subCategory: "cucumber",
    photo: "/images/product-images/cucumber.webp",
  },
  {
    name: "Burpless Cucumbers",
    category: "Vegetables",
    subCategory: "cucumber",
    photo: "/images/product-images/cucumber.webp",
  },
  {
    name: "DivA Hybrid Cucumbers",
    category: "Vegetables",
    subCategory: "cucumber",
    photo: "/images/product-images/cucumber.webp",
  },
  {
    name: "Marketmore 76 Cucumbers",
    category: "Vegetables",
    subCategory: "cucumber",
    photo: "/images/product-images/cucumber.webp",
  },
  {
    name: "Sweet Success Cucumbers",
    category: "Vegetables",
    subCategory: "cucumber",
    photo: "/images/product-images/cucumber.webp",
  },
  {
    name: "Sumter Cucumbers",
    category: "Vegetables",
    subCategory: "cucumber",
    photo: "/images/product-images/cucumber.webp",
  },
  {
    name: "Sweet Slice Cucumbers",
    category: "Vegetables",
    subCategory: "cucumber",
    photo: "/images/product-images/cucumber.webp",
  },
  {
    name: "Tasty Green Cucumbers",
    category: "Vegetables",
    subCategory: "cucumber",
    photo: "/images/product-images/cucumber.webp",
  },
  {
    name: "Picklebush Cucumbers",
    category: "Vegetables",
    subCategory: "cucumber",
    photo: "/images/product-images/cucumber.webp",
  },
  {
    name: "Miniature White Cucumbers",
    category: "Vegetables",
    subCategory: "cucumber",
    photo: "/images/product-images/cucumber.webp",
  },
  {
    name: "Mexican Sour Gherkin Cucumbers",
    category: "Vegetables",
    subCategory: "cucumber",
    photo: "/images/product-images/cucumber.webp",
  },
  {
    name: "Passandra Cucumbers",
    category: "Vegetables",
    subCategory: "cucumber",
    photo: "/images/product-images/cucumber.webp",
  },
  {
    name: "Dasher II Cucumbers",
    category: "Vegetables",
    subCategory: "cucumber",
    photo: "/images/product-images/cucumber.webp",
  },
  {
    name: "Fanfare Cucumbers",
    category: "Vegetables",
    subCategory: "cucumber",
    photo: "/images/product-images/cucumber.webp",
  },
  {
    name: "Cucino Cucumbers",
    category: "Vegetables",
    subCategory: "cucumber",
    photo: "/images/product-images/cucumber.webp",
  },
  {
    name: "Greensleeves Cucumbers",
    category: "Vegetables",
    subCategory: "cucumber",
    photo: "/images/product-images/cucumber.webp",
  },
  {
    name: "Socrates Cucumbers",
    category: "Vegetables",
    subCategory: "cucumber",
    photo: "/images/product-images/cucumber.webp",
  },
  {
    name: "Regal Cucumbers",
    category: "Vegetables",
    subCategory: "cucumber",
    photo: "/images/product-images/cucumber.webp",
  },
  {
    name: "Patio Snacker Cucumbers",
    category: "Vegetables",
    subCategory: "cucumber",
    photo: "/images/product-images/cucumber.webp",
  },
  {
    name: "PineApples",
    category: "Fruits",
    subCategory: "pineapple",
    photo: "/images/product-images/pineapple.webp",
  },
  {
    name: "Smooth Cayenne PineApples",
    category: "Fruits",
    subCategory: "pineapple",
    photo: "/images/product-images/pineapple.webp",
  },
  {
    name: "Red Spanish PineApples",
    category: "Fruits",
    subCategory: "pineapple",
    photo: "/images/product-images/pineapple.webp",
  },
  {
    name: "Sugarloaf PineApples",
    category: "Fruits",
    subCategory: "pineapple",
    photo: "/images/product-images/pineapple.webp",
  },
  {
    name: "Hilo PineApples",
    category: "Fruits",
    subCategory: "pineapple",
    photo: "/images/product-images/pineapple.webp",
  },
  {
    name: "Pernambuco PineApples",
    category: "Fruits",
    subCategory: "pineapple",
    photo: "/images/product-images/pineapple.webp",
  },
  {
    name: "Detroit Dark Red Beets",
    category: "Vegetables",
    subCategory: "beet",
    photo: "/images/product-images/beet.webp",
  },
  {
    name: "Golden Beets",
    category: "Vegetables",
    subCategory: "beet",
    photo: "/images/product-images/beet.webp",
  },
  {
    name: "Chioggia Beet (Candy Stripe Beet)",
    category: "Vegetables",
    subCategory: "beet",
    photo: "/images/product-images/beet.webp",
  },
  {
    name: "Bulls Blood Beets",
    category: "Vegetables",
    subCategory: "beet",
    photo: "/images/product-images/beet.webp",
  },
  {
    name: "Cylindra Beets",
    category: "Vegetables",
    subCategory: "beet",
    photo: "/images/product-images/beet.webp",
  },
  {
    name: "Burpee's Golden Beets",
    category: "Vegetables",
    subCategory: "beet",
    photo: "/images/product-images/beet.webp",
  },
  {
    name: "Early Wonder Beets",
    category: "Vegetables",
    subCategory: "beet",
    photo: "/images/product-images/beet.webp",
  },
  {
    name: "Merlin Beets",
    category: "Vegetables",
    subCategory: "beet",
    photo: "/images/product-images/beet.webp",
  },
  {
    name: "Ruby Queen Beets",
    category: "Vegetables",
    subCategory: "beet",
    photo: "/images/product-images/beet.webp",
  },
  {
    name: "Touchstone Gold Beets",
    category: "Vegetables",
    subCategory: "beet",
    photo: "/images/product-images/beet.webp",
  },
  {
    name: "Avalanche Beets",
    category: "Vegetables",
    subCategory: "beet",
    photo: "/images/product-images/beet.webp",
  },
  {
    name: "Badger Flame Beets",
    category: "Vegetables",
    subCategory: "beet",
    photo: "/images/product-images/beet.webp",
  },
  {
    name: "Blankoma Beets",
    category: "Vegetables",
    subCategory: "beet",
    photo: "/images/product-images/beet.webp",
  },
  {
    name: "Crosby Egyptian Beets",
    category: "Vegetables",
    subCategory: "beet",
    photo: "/images/product-images/beet.webp",
  },
  {
    name: "Early Wonder Tall Top Beets",
    category: "Vegetables",
    subCategory: "beet",
    photo: "/images/product-images/beet.webp",
  },
  {
    name: "Formanova Beets",
    category: "Vegetables",
    subCategory: "beet",
    photo: "/images/product-images/beet.webp",
  },
  {
    name: "Lutz Green Leaf Beets",
    category: "Vegetables",
    subCategory: "beet",
    photo: "/images/product-images/beet.webp",
  },
  {
    name: "Red Ace Beets",
    category: "Vegetables",
    subCategory: "beet",
    photo: "/images/product-images/beet.webp",
  },
  {
    name: "Red Cloud Beets",
    category: "Vegetables",
    subCategory: "beet",
    photo: "/images/product-images/beet.webp",
  },
  {
    name: "White Albino Beets",
    category: "Vegetables",
    subCategory: "beet",
    photo: "/images/product-images/beet.webp",
  },
  {
    name: "Hass Avacados",
    category: "Fruits",
    subCategory: "avacado",
    photo: "/images/product-images/avocado.webp",
  },
  {
    name: "Fuerte Avacados",
    category: "Fruits",
    subCategory: "avacado",
    photo: "/images/product-images/avocado.webp",
  },
  {
    name: "Reed Avacados",
    category: "Fruits",
    subCategory: "avacado",
    photo: "/images/product-images/avocado.webp",
  },
  {
    name: "Bacon Avacados",
    category: "Fruits",
    subCategory: "avacado",
    photo: "/images/product-images/avocado.webp",
  },
  {
    name: "Zutano Avacados",
    category: "Fruits",
    subCategory: "avacado",
    photo: "/images/product-images/avocado.webp",
  },
  {
    name: "Gwen Avacados",
    category: "Fruits",
    subCategory: "avacado",
    photo: "/images/product-images/avocado.webp",
  },
  {
    name: "Pinkerton Avacados",
    category: "Fruits",
    subCategory: "avacado",
    photo: "/images/product-images/avocado.webp",
  },
  {
    name: "Lamb Hass Avacados",
    category: "Fruits",
    subCategory: "avacado",
    photo: "/images/product-images/avocado.webp",
  },
  {
    name: "Sharwil Avacados",
    category: "Fruits",
    subCategory: "avacado",
    photo: "/images/product-images/avocado.webp",
  },
  {
    name: "Brogdon Avacados",
    category: "Fruits",
    subCategory: "avacado",
    photo: "/images/product-images/avocado.webp",
  },

  {
    name: "Blueberries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/blueberry.webp",
  },
  {
    name: "Raspberries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/raspberry.webp",
  },
  {
    name: "Blackberries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/blackberry.webp",
  },
  {
    name: "Cranberries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/cranberry.webp",
  },
  {
    name: "Goji Berries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/goji-berry.webp",
  },
  {
    name: "Acai Berries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/acai-berry.webp",
  },
  {
    name: "Elderberries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/elderberry.webp",
  },
  {
    name: "Mulberries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/mulberry.webp",
  },
  {
    name: "Huckleberries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/huckleberry.webp",
  },
  {
    name: "Salmonberries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/salmonberry.webp",
  },
  {
    name: "Marionberries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/blackberry.webp",
  },
  {
    name: "Currant Berries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/currant-berry.webp",
  },
  {
    name: "White Mulberries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/whtmul.webp",
  },
  {
    name: "Beautyberries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/beautyb.webp",
  },
  {
    name: "Bearberries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/buffb.webp",
  },
  {
    name: "Snowberries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/snowb.webp",
  },
  {
    name: "Calafate Berries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/calafate.webp",
  },
  {
    name: "Chehalem Blackberries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/Boysenberry.webp",
  },
  {
    name: "Clingstone Thornless Blackberries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/Boysenberry.webp",
  },
  {
    name: "Cutleaf Blackberries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/Boysenberry.webp",
  },
  {
    name: "Garden Blackberries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/Boysenberry.webp",
  },
  {
    name: "Himalayan Blackberries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/Boysenberry.webp",
  },
  {
    name: "Natchez Blackberries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/Boysenberry.webp",
  },
  {
    name: "Triple Crown Blackberries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/Boysenberry.webp",
  },
  {
    name: "Waldo Berries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/aronian.webp",
  },
  {
    name: "Hardy Kiwis",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/hkiwi.webp",
  },
  {
    name: "Olallieberries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/olallie.webp",
  },
  {
    name: "Thimbleberries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/thimbleberry.webp",
  },
  {
    name: "Bananaberries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/aronian.webp",
  },
  {
    name: "Cape Gooseberries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/capegoose.webp",
  },
  {
    name: "Barberries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/barberry.webp",
  },
  {
    name: "Buffaloberries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/buffb.webp",
  },
  {
    name: "Salal Berries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/aronia.webp",
  },
  {
    name: "Seaberries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/seaber.webp",
  },
  {
    name: "Strawberry Tree Berries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/strawtree.webp",
  },
  {
    name: "Youngberries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/youngber.webp",
  },
  {
    name: "Partridgeberries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/partridgeb.webp",
  },
  {
    name: "Debbaneh Berrieies",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/aronia.webp",
  },
  {
    name: "Tropical Berries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/tropicber.webp",
  },
  {
    name: "Raisinberries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/aronia.webp",
  },
  {
    name: "Chokeberries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/aronia.webp",
  },
  {
    name: "Boysenberries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/Boysenberry.webp",
  },
  {
    name: "Saskatoon Berries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/aronia.webp",
  },
  {
    name: "Juneberries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/aronia.webp",
  },
  {
    name: "Serviceberries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/serviceb.webp",
  },
  {
    name: "Cloud Berries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/cloudberries.webp",
  },
  {
    name: "Aronia Berries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/aronia.webp",
  },
  {
    name: "Cilantro",
    category: "herbs and spices",
    subCategory: "green",
    photo: "/images/product-images/cilantro.webp",
  },
  {
    name: "Parsley",
    category: "herbs and spices",
    subCategory: "green",
    photo: "/images/product-images/parsley.webp",
  },

  {
    name: "Mint",
    category: "herbs and spices",
    subCategory: "green",
    photo: "/images/product-images/mint.webp",
  },
  {
    name: "Thyme",
    category: "herbs and spices",
    subCategory: "green",
    photo: "/images/product-images/thyme.webp",
  },
  {
    name: "Oregano",
    category: "herbs and spices",
    subCategory: "green",
    photo: "/images/product-images/oregano.webp",
  },
  {
    name: "Rosemary",
    category: "herbs and spices",
    subCategory: "green",
    photo: "/images/product-images/rosemary.webp",
  },
  {
    name: "Sage",
    category: "herbs and spices",
    subCategory: "green",
    photo: "/images/product-images/sage.webp",
  },
  {
    name: "Chives",
    category: "herbs and spices",
    subCategory: "green",
    photo: "/images/product-images/chives.webp",
  },
  {
    name: "Dill",
    category: "herbs and spices",
    subCategory: "green",
    photo: "/images/product-images/dill.webp",
  },
  {
    name: "Borage",
    category: "herbs and spices",
    subCategory: "green",
    photo: "/images/product-images/borage.webp",
  },
  {
    name: "Culantro",
    category: "herbs and spices",
    subCategory: "green",
    photo: "/images/product-images/cullantro.webp",
  },
  {
    name: "Lemongrass",
    category: "herbs and spices",
    subCategory: "green",
    photo: "/images/product-images/lemongrass.webp",
  },
  {
    name: "Lavender",
    category: "herbs and spices",
    subCategory: "green",
    photo: "/images/product-images/lavender.webp",
  },
  {
    name: "Fennel",
    category: "herbs and spices",
    subCategory: "green",
    photo: "/images/product-images/fennel.webp",
  },
  {
    name: "Tarragon",
    category: "herbs and spices",
    subCategory: "green",
    photo: "/images/product-images/tarragon.webp",
  },
  {
    name: "Marjoram",
    category: "herbs and spices",
    subCategory: "green",
    photo: "/images/product-images/marjoram.webp",
  },
  {
    name: "Cress",
    category: "herbs and spices",
    subCategory: "green",
    photo: "/images/product-images/cress.webp",
  },
  {
    name: "Savory",
    category: "herbs and spices",
    subCategory: "green",
    photo: "/images/product-images/savory.webp",
  },
  {
    name: "Bay Leaf",
    category: "herbs and spices",
    subCategory: "green",
    photo: "/images/product-images/bayleaf.webp",
  },
  {
    name: "Watermelon",
    category: "Fruits",
    subCategory: "melon",
    photo: "/images/product-images/watermel.webp",
  },
  {
    name: "Cantaloupe",
    category: "Fruits",
    subCategory: "melon",
    photo: "/images/product-images/cantaloupe.webp",
  },
  {
    name: "Honeydew Melon",
    category: "Fruits",
    subCategory: "melon",
    photo: "/images/product-images/honeydew.webp",
  },
  {
    name: "Casaba Melon",
    category: "Fruits",
    subCategory: "melon",
    photo: "/images/product-images/spritemel.webp",
  },
  {
    name: "Crenshaw Melon",
    category: "Fruits",
    subCategory: "melon",
    photo: "/images/product-images/spritemel.webp",
  },
  {
    name: "Canary Melon",
    category: "Fruits",
    subCategory: "melon",
    photo: "/images/product-images/spritemel.webp",
  },
  {
    name: "Persian Melon",
    category: "Fruits",
    subCategory: "melon",
    photo: "/images/product-images/spritemel.webp",
  },
  {
    name: "Galia Melon",
    category: "Fruits",
    subCategory: "melon",
    photo: "/images/product-images/spritemel.webp",
  },
  {
    name: "Piel de Sapo Melon",
    category: "Fruits",
    subCategory: "melon",
    photo: "/images/product-images/spritemel.webp",
  },
  {
    name: "Golden Dewlicious Melon",
    category: "Fruits",
    subCategory: "melon",
    photo: "/images/product-images/spritemel.webp",
  },
  {
    name: "Winter Melon",
    category: "Fruits",
    subCategory: "melon",
    photo: "/images/product-images/spritemel.webp",
  },
  {
    name: "Hamigua Melon",
    category: "Fruits",
    subCategory: "melon",
    photo: "/images/product-images/spritemel.webp",
  },
  {
    name: "Bitter Melon",
    category: "Fruits",
    subCategory: "melon",
    photo: "/images/product-images/spritemel.webp",
  },
  {
    name: "Preserve Melon",
    category: "Fruits",
    subCategory: "melon",
    photo: "/images/product-images/spritemel.webp",
  },
  {
    name: "Kiwano Melon",
    category: "Fruits",
    subCategory: "melon",
    photo: "/images/product-images/spritemel.webp",
  },
  {
    name: "Santa Claus Melon",
    category: "Fruits",
    subCategory: "melon",
    photo: "/images/product-images/spritemel.webp",
  },
  {
    name: "Sprite Melon",
    category: "Fruits",
    subCategory: "melon",
    photo: "/images/product-images/spritemel.webp",
  },
  {
    name: "Galia Melon",
    category: "Fruits",
    subCategory: "melon",
    photo: "/images/product-images/spritemel.webp",
  },
  {
    name: "Dragon Fruits",
    category: "Fruits",
    subCategory: "fruit",
    photo: "/images/product-images/dragonFruits.webp",
  },
  {
    name: "Kiwano",
    category: "Fruits",
    subCategory: "fruit",
    photo: "/images/product-images/kiwano.webp",
  },
  {
    name: "Star Fruits",
    category: "Fruits",
    subCategory: "fruit",
    photo: "/images/product-images/star.webp",
  },
  {
    name: "Durian",
    category: "Fruits",
    subCategory: "fruit",
    photo: "/images/product-images/durian.webp",
  },
  {
    name: "JackFruits",
    category: "Fruits",
    subCategory: "fruit",
    photo: "/images/product-images/jackFruits.webp",
  },
  {
    name: "Rambutan",
    category: "Fruits",
    subCategory: "fruit",
    photo: "/images/product-images/rambutan.webp",
  },
  {
    name: "Mangosteen",
    category: "Fruits",
    subCategory: "fruit",
    photo: "/images/product-images/mangosteen.webp",
  },
  {
    name: "Passion Fruits",
    category: "Fruits",
    subCategory: "fruit",
    photo: "/images/product-images/passion.webp",
  },
  {
    name: "Papaya",
    category: "Fruits",
    subCategory: "fruit",
    photo: "/images/product-images/papaya.webp",
  },
  {
    name: "Guava",
    category: "Fruits",
    subCategory: "fruit",
    photo: "/images/product-images/guava.webp",
  },
  {
    name: "Lychee",
    category: "Fruits",
    subCategory: "fruit",
    photo: "/images/product-images/lychee.webp",
  },
  {
    name: "Açaí",
    category: "Fruits",
    subCategory: "fruit",
    photo: "/images/product-images/acai.webp",
  },
  {
    name: "Pitaya, Dragon Fruits",
    category: "Fruits",
    subCategory: "fruit",
    photo: "/images/product-images/dragonFruits.webp",
  },
  {
    name: "Feijoa",
    category: "Fruits",
    subCategory: "fruit",
    photo: "/images/product-images/feijoa.webp",
  },
  {
    name: "Chayote",
    category: "Vegetables",
    subCategory: "fruit",
    photo: "/images/product-images/chayote.webp",
  },
  {
    name: "Yuca",
    category: "Vegetables",
    subCategory: "vegetable",
    photo: "/images/product-images/yuca.webp",
  },
  {
    name: "Jícama",
    category: "Vegetables",
    subCategory: "vegetable",
    photo: "/images/product-images/jicama.webp",
  },
  {
    name: "Salsify",
    category: "Vegetables",
    subCategory: "vegetable",
    photo: "/images/product-images/salsify.webp",
  },
  {
    name: "Parsnip",
    category: "Vegetables",
    subCategory: "vegetable",
    photo: "/images/product-images/sprouts.webp",
  },
  {
    name: "Bok Choy",
    category: "Vegetables",
    subCategory: "vegetable",
    photo: "/images/product-images/sprouts.webp",
  },
  {
    name: "Bean Sprouts",
    category: "seeds",
    subCategory: "shoot",
    photo: "/images/product-images/sprouts.webp",
  },
  {
    name: "Alfalfa Sprouts",
    category: "seeds",
    subCategory: "shoot",
    photo: "/images/product-images/sprouts.webp",
  },
  {
    name: "Mung Bean Sprouts",
    category: "seeds",
    subCategory: "shoot",
    photo: "/images/product-images/sprouts.webp",
  },
  {
    name: "Broccoli Sprouts",
    category: "seeds",
    subCategory: "shoot",
    photo: "/images/product-images/sprouts.webp",
  },
  {
    name: "Radish Sprouts",
    category: "seeds",
    subCategory: "shoot",
    photo: "/images/product-images/sprouts.webp",
  },
  {
    name: "Pea Shoots",
    category: "seeds",
    subCategory: "shoot",
    photo: "/images/product-images/sprouts.webp",
  },
  {
    name: "Sunflower Shoots",
    category: "seeds",
    subCategory: "shoot",
    photo: "/images/product-images/sprouts.webp",
  },
  {
    name: "Wheatgrass",
    category: "seeds",
    subCategory: "shoot",
    photo: "/images/product-images/sprouts.webp",
  },
  {
    name: "Arugula Sprouts",
    category: "seeds",
    subCategory: "shoot",
    photo: "/images/product-images/sprouts.webp",
  },
  {
    name: "Clover Sprouts",
    category: "seeds",
    subCategory: "shoot",
    photo: "/images/product-images/sprouts.webp",
  },
  {
    name: "Lentil Sprouts",
    category: "seeds",
    subCategory: "shoot",
    photo: "/images/product-images/sprouts.webp",
  },
  {
    name: "Fenugreek Sprouts",
    category: "seeds",
    subCategory: "shoot",
    photo: "/images/product-images/sprouts.webp",
  },
  {
    name: "Kale Sprouts",
    category: "seeds",
    subCategory: "shoot",
    photo: "/images/product-images/sprouts.webp",
  },
  {
    name: "Chia Sprouts",
    category: "seeds",
    subCategory: "shoot",
    photo: "/images/product-images/sprouts.webp",
  },
  {
    name: "Bamboo Shoots",
    category: "seeds",
    subCategory: "shoot",
    photo: "/images/product-images/sprouts.webp",
  },
  {
    name: "Soybean Sprouts",
    category: "seeds",
    subCategory: "shoot",
    photo: "/images/product-images/sprouts.webp",
  },
  {
    name: "Cabbage Sprouts",
    category: "seeds",
    subCategory: "shoot",
    photo: "/images/product-images/sprouts.webp",
  },
  {
    name: "Mustard Sprouts",
    category: "seeds",
    subCategory: "shoot",
    photo: "/images/product-images/sprouts.webp",
  },
  {
    name: "Celery Sprouts",
    category: "seeds",
    subCategory: "shoot",
    photo: "/images/product-images/sprouts.webp",
  },
  {
    name: "Onion Sprouts",
    category: "seeds",
    subCategory: "shoot",
    photo: "/images/product-images/sprouts.webp",
  },
  {
    name: "Potato",
    category: "Vegetables",
    subCategory: "tuber",
    photo: "/images/product-images/potat.webp",
  },
  {
    name: "Sweet Potato",
    category: "Vegetables",
    subCategory: "tuber",
    photo: "/images/product-images/yam.webp",
  },
  {
    name: "Yam",
    category: "Vegetables",
    subCategory: "tuber",
    photo: "/images/product-images/yam.webp",
  },
  {
    name: "Cassava",
    category: "Vegetables",
    subCategory: "tuber",
    photo: "/images/product-images/tubers.webp",
  },
  {
    name: "Taro",
    category: "Vegetables",
    subCategory: "tuber",
    photo: "/images/product-images/tubers.webp",
  },
  {
    name: "Jicama",
    category: "Vegetables",
    subCategory: "tuber",
    photo: "/images/product-images/tubers.webp",
  },
  {
    name: "Jerusalem Artichoke",
    category: "Vegetables",
    subCategory: "tuber",
    photo: "/images/product-images/tubers.webp",
  },
  {
    name: "Rutabaga",
    category: "Vegetables",
    subCategory: "tuber",
    photo: "/images/product-images/tubers.webp",
  },
  {
    name: "Sunchokes",
    category: "Vegetables",
    subCategory: "tuber",
    photo: "/images/product-images/tubers.webp",
  },
  {
    name: "Chinese Artichoke",
    category: "Vegetables",
    subCategory: "tuber",
    photo: "/images/product-images/tubers.webp",
  },
  {
    name: "Arracacha",
    category: "Vegetables",
    subCategory: "tuber",
    photo: "/images/product-images/tubers.webp",
  },
  {
    name: "Oca",
    category: "Vegetables",
    subCategory: "tuber",
    photo: "/images/product-images/tubers.webp",
  },
  {
    name: "Crosne",
    category: "Vegetables",
    subCategory: "tuber",
    photo: "/images/product-images/tubers.webp",
  },
  {
    name: "Chayote",
    category: "Vegetables",
    subCategory: "tuber",
    photo: "/images/product-images/tubers.webp",
  },
  {
    name: "Malanga",
    category: "Vegetables",
    subCategory: "tuber",
    photo: "/images/product-images/tubers.webp",
  },
  {
    name: "Konjac",
    category: "Vegetables",
    subCategory: "tuber",
    photo: "/images/product-images/tubers.webp",
  },
  {
    name: "Tiquisque",
    category: "Vegetables",
    subCategory: "tuber",
    photo: "/images/product-images/tubers.webp",
  },
  {
    name: "Dasheen",
    category: "Vegetables",
    subCategory: "tuber",
    photo: "/images/product-images/tubers.webp",
  },
  {
    name: "Plectranthus",
    category: "Vegetables",
    subCategory: "tuber",
    photo: "/images/product-images/tubers.webp",
  },
  {
    name: "Chufa",
    category: "Vegetables",
    subCategory: "tuber",
    photo: "/images/product-images/tubers.webp",
  },
  {
    name: "Garlic",
    category: "Vegetables",
    subCategory: "allium",
    photo: "/images/product-images/garlic.webp",
  },
  {
    name: "Onion",
    category: "Vegetables",
    subCategory: "allium",
    photo: "/images/product-images/onion.webp",
  },
  {
    name: "Leek",
    category: "Vegetables",
    subCategory: "allium",
    photo: "/images/product-images/leek.webp",
  },
  {
    name: "Scallion",
    category: "Vegetables",
    subCategory: "allium",
    photo: "/images/product-images/scallion.webp",
  },
  {
    name: "Chives",
    category: "Vegetables",
    subCategory: "allium",
    photo: "/images/product-images/chives.webp",
  },
  {
    name: "Shallot",
    category: "Vegetables",
    subCategory: "allium",
    photo: "/images/product-images/onion.webp",
  },
  {
    name: "Spring Onion",
    category: "Vegetables",
    subCategory: "allium",
    photo: "/images/product-images/onion.webp",
  },
  {
    name: "Elephant Garlic",
    category: "Vegetables",
    subCategory: "allium",
    photo: "/images/product-images/garlic.webp",
  },
  {
    name: "Pearl Onion",
    category: "Vegetables",
    subCategory: "allium",
    photo: "/images/product-images/onion.webp",
  },
  {
    name: "Ramps",
    category: "Vegetables",
    subCategory: "allium",
    photo: "/images/product-images/onion.webp",
  },
  {
    name: "Welsh Onion",
    category: "Vegetables",
    subCategory: "allium",
    photo: "/images/product-images/onion.webp",
  },
  {
    name: "Egyptian Walking Onion",
    category: "Vegetables",
    subCategory: "allium",
    photo: "/images/product-images/onion.webp",
  },
  {
    name: "Tree Onion",
    category: "Vegetables",
    subCategory: "allium",
    photo: "/images/product-images/onion.webp",
  },
  {
    name: "Evergreen Bunching Onion",
    category: "Vegetables",
    subCategory: "allium",
    photo: "/images/product-images/onion.webp",
  },
  {
    name: "Cipollini Onion",
    category: "Vegetables",
    subCategory: "allium",
    photo: "/images/product-images/onion.webp",
  },
  {
    name: "Red Onion",
    category: "Vegetables",
    subCategory: "allium",
    photo: "/images/product-images/onion.webp",
  },
  {
    name: "Yellow Onion",
    category: "Vegetables",
    subCategory: "allium",
    photo: "/images/product-images/onion.webp",
  },
  {
    name: "White Onion",
    category: "Vegetables",
    subCategory: "allium",
    photo: "/images/product-images/onion.webp",
  },
  {
    name: "Vidalia Onion",
    category: "Vegetables",
    subCategory: "allium",
    photo: "/images/product-images/onion.webp",
  },
  {
    name: "Boiling Onion",
    category: "Vegetables",
    subCategory: "allium",
    photo: "/images/product-images/onion.webp",
  },
  {
    name: "Green Pea",
    category: "Legumes",
    subCategory: "Peas",
    photo: "/images/product-images/beans.webp",
  },
  {
    name: "Snow Pea",
    category: "Legumes",
    subCategory: "Peas",
    photo: "/images/product-images/beans.webp",
  },
  {
    name: "Sugar Snap Pea",
    category: "Legumes",
    subCategory: "Peas",
    photo: "/images/product-images/beans.webp",
  },
  {
    name: "Black-Eyed Pea",
    category: "Legumes",
    subCategory: "Peas",
    photo: "/images/product-images/beans.webp",
  },
  {
    name: "Yellow Pea",
    category: "Legumes",
    subCategory: "Peas",
    photo: "/images/product-images/beans.webp",
  },
  {
    name: "Split Pea",
    category: "Legumes",
    subCategory: "Peas",
    photo: "/images/product-images/beans.webp",
  },
  {
    name: "Chickpea",
    category: "Legumes",
    subCategory: "Peas",
    photo: "/images/product-images/beans.webp",
  },
  {
    name: "Black Chickpea",
    category: "Legumes",
    subCategory: "Peas",
    photo: "/images/product-images/beans.webp",
  },
  {
    name: "Green Chickpea",
    category: "Legumes",
    subCategory: "Peas",
    photo: "/images/product-images/beans.webp",
  },
  {
    name: "Pigeon Pea",
    category: "Legumes",
    subCategory: "Peas",
    photo: "/images/product-images/beans.webp",
  },
  {
    name: "Field Pea",
    category: "Legumes",
    subCategory: "Peas",
    photo: "/images/product-images/beans.webp",
  },
  {
    name: "Crowder Pea",
    category: "Legumes",
    subCategory: "Peas",
    photo: "/images/product-images/beans.webp",
  },
  {
    name: "Purple Hull Pea",
    category: "Legumes",
    subCategory: "Peas",
    photo: "/images/product-images/beans.webp",
  },
  {
    name: "Cowpea",
    category: "Legumes",
    subCategory: "Peas",
    photo: "/images/product-images/beans.webp",
  },
  {
    name: "Garden Pea",
    category: "Legumes",
    subCategory: "Peas",
    photo: "/images/product-images/beans.webp",
  },
  {
    name: "Edible-Podded Pea",
    category: "Legumes",
    subCategory: "Peas",
    photo: "/images/product-images/beans.webp",
  },
  {
    name: "Alderman Pea",
    category: "Legumes",
    subCategory: "Peas",
    photo: "/images/product-images/beans.webp",
  },
  {
    name: "Tom Thumb Pea",
    category: "Legumes",
    subCategory: "Peas",
    photo: "/images/product-images/beans.webp",
  },
  {
    name: "Butter Pea",
    category: "Legumes",
    subCategory: "Peas",
    photo: "/images/product-images/beans.webp",
  },
  {
    name: "Snap Pea",
    category: "Legumes",
    subCategory: "Peas",
    photo: "/images/product-images/beans.webp",
  },
  {
    name: "Green Bean",
    category: "Legumes",
    subCategory: "Beans",
    photo: "/images/product-images/beans.webp",
  },
  {
    name: "Kidney Bean",
    category: "Legumes",
    subCategory: "Beans",
    photo: "/images/product-images/beans.webp",
  },
  {
    name: "Black Bean",
    category: "Legumes",
    subCategory: "Beans",
    photo: "/images/product-images/beans.webp",
  },
  {
    name: "Pinto Bean",
    category: "Legumes",
    subCategory: "Beans",
    photo: "/images/product-images/beans.webp",
  },
  {
    name: "Navy Bean",
    category: "Legumes",
    subCategory: "Beans",
    photo: "/images/product-images/beans.webp",
  },
  {
    name: "Lima Bean",
    category: "Legumes",
    subCategory: "Beans",
    photo: "/images/product-images/beans.webp",
  },
  {
    name: "Garbanzo Bean",
    category: "Legumes",
    subCategory: "Beans",
    photo: "/images/product-images/beans.webp",
  },
  {
    name: "Fava Bean",
    category: "Legumes",
    subCategory: "Beans",
    photo: "/images/product-images/beans.webp",
  },
  {
    name: "Cannellini Bean",
    category: "Legumes",
    subCategory: "Beans",
    photo: "/images/product-images/beans.webp",
  },
  {
    name: "Great Northern Bean",
    category: "Legumes",
    subCategory: "Beans",
    photo: "/images/product-images/beans.webp",
  },
  {
    name: "Black-Eyed Pea",
    category: "Legumes",
    subCategory: "Beans",
    photo: "/images/product-images/beans.webp",
  },
  {
    name: "Adzuki Bean",
    category: "Legumes",
    subCategory: "Beans",
    photo: "/images/product-images/beans.webp",
  },
  {
    name: "Red Bean",
    category: "Legumes",
    subCategory: "Beans",
    photo: "/images/product-images/beans.webp",
  },
  {
    name: "Cranberry Bean",
    category: "Legumes",
    subCategory: "Beans",
    photo: "/images/product-images/beans.webp",
  },
  {
    name: "Mung Bean",
    category: "Legumes",
    subCategory: "Beans",
    photo: "/images/product-images/beans.webp",
  },
  {
    name: "Lentil",
    category: "Legumes",
    subCategory: "Beans",
    photo: "/images/product-images/beans.webp",
  },
  {
    name: "Chickpea",
    category: "Legumes",
    subCategory: "Beans",
    photo: "/images/product-images/beans.webp",
  },
  {
    name: "Black-Eyed Pea",
    category: "Legumes",
    subCategory: "Beans",
    photo: "/images/product-images/beans.webp",
  },
  {
    name: "Split Pea",
    category: "Legumes",
    subCategory: "Beans",
    photo: "/images/product-images/beans.webp",
  },
  {
    name: "Lima Bean",
    category: "Legumes",
    subCategory: "Beans",
    photo: "/images/product-images/beans.webp",
  },
  {
    name: "Butternut Squash",
    category: "Vegetables",
    subCategory: "squash",
    photo: "/images/product-images/squash.webp",
  },
  {
    name: "Acorn Squash",
    category: "Vegetables",
    subCategory: "squash",
    photo: "/images/product-images/squash.webp",
  },
  {
    name: "Spaghetti Squash",
    category: "Vegetables",
    subCategory: "squash",
    photo: "/images/product-images/squash.webp",
  },
  {
    name: "Yellow Squash",
    category: "Vegetables",
    subCategory: "squash",
    photo: "/images/product-images/squash.webp",
  },
  {
    name: "Delicata Squash",
    category: "Vegetables",
    subCategory: "squash",
    photo: "/images/product-images/squash.webp",
  },
  {
    name: "Kabocha Squash",
    category: "Vegetables",
    subCategory: "squash",
    photo: "/images/product-images/squash.webp",
  },
  {
    name: "Hubbard Squash",
    category: "Vegetables",
    subCategory: "squash",
    photo: "/images/product-images/squash.webp",
  },
  {
    name: "Buttercup Squash",
    category: "Vegetables",
    subCategory: "squash",
    photo: "/images/product-images/squash.webp",
  },
  {
    name: "Carnival Squash",
    category: "Vegetables",
    subCategory: "squash",
    photo: "/images/product-images/squash.webp",
  },
  {
    name: "Pattypan Squash",
    category: "Vegetables",
    subCategory: "squash",
    photo: "/images/product-images/squash.webp",
  },
  {
    name: "Crookneck Squash",
    category: "Vegetables",
    subCategory: "squash",
    photo: "/images/product-images/squash.webp",
  },
  {
    name: "Straightneck Squash",
    category: "Vegetables",
    subCategory: "squash",
    photo: "/images/product-images/squash.webp",
  },
  {
    name: "Sweet Dumpling Squash",
    category: "Vegetables",
    subCategory: "squash",
    photo: "/images/product-images/squash.webp",
  },
  {
    name: "Golden Nugget Squash",
    category: "Vegetables",
    subCategory: "squash",
    photo: "/images/product-images/squash.webp",
  },
  {
    name: "Hubbard Squash",
    category: "Vegetables",
    subCategory: "squash",
    photo: "/images/product-images/squash.webp",
  },
  {
    name: "Tromboncino Squash",
    category: "Vegetables",
    subCategory: "squash",
    photo: "/images/product-images/squash.webp",
  },
  {
    name: "Tatume Squash",
    category: "Vegetables",
    subCategory: "squash",
    photo: "/images/product-images/squash.webp",
  },
  {
    name: "Calabaza Squash",
    category: "Vegetables",
    subCategory: "squash",
    photo: "/images/product-images/squash.webp",
  },
  {
    name: "Banana Squash",
    category: "Vegetables",
    subCategory: "squash",
    photo: "/images/product-images/squash.webp",
  },
  {
    name: "Dill Pickles",
    category: "Vegetables",
    subCategory: "pickle",
    photo: "/images/product-images/pickle.webp",
  },
  {
    name: "Sweet Pickles",
    category: "Vegetables",
    subCategory: "pickle",
    photo: "/images/product-images/pickle.webp",
  },
  {
    name: "Bread and Butter Pickles",
    category: "Vegetables",
    subCategory: "pickle",
    photo: "/images/product-images/pickle.webp",
  },
  {
    name: "Bell Peppers",
    category: "Vegetables",
    subCategory: "pepper",
    photo: "/images/product-images/bellpep.webp",
  },
  {
    name: "Jalapeno Peppers",
    category: "Vegetables",
    subCategory: "pepper",
    photo: "/images/product-images/jalapeno.webp",
  },
  {
    name: "Habanero Peppers",
    category: "Vegetables",
    subCategory: "pepper",
    photo: "/images/product-images/habanero.webp",
  },
  {
    name: "Cayenne Peppers",
    category: "Vegetables",
    subCategory: "pepper",
    photo: "/images/product-images/thaichili.webp",
  },
  {
    name: "Anaheim Peppers",
    category: "Vegetables",
    subCategory: "pepper",
    photo: "/images/product-images/pepper.webp",
  },
  {
    name: "Poblano Peppers",
    category: "Vegetables",
    subCategory: "pepper",
    photo: "/images/product-images/pablo.webp",
  },
  {
    name: "Fresno Peppers",
    category: "Vegetables",
    subCategory: "pepper",
    photo: "/images/product-images/fresno.webp",
  },
  {
    name: "Chipotle Peppers",
    category: "Vegetables",
    subCategory: "pepper",
    photo: "/images/product-images/chipotlepep.webp",
  },
  {
    name: "Serrano Peppers",
    category: "Vegetables",
    subCategory: "pepper",
    photo: "/images/product-images/Serranos.webp",
  },
  {
    name: "Banana Peppers",
    category: "Vegetables",
    subCategory: "pepper",
    photo: "/images/product-images/bananapep.webp",
  },
  {
    name: "Thai Chili Peppers",
    category: "Vegetables",
    subCategory: "pepper",
    photo: "/images/product-images/thaichili.webp",
  },
  {
    name: "Bird's Eye Peppers",
    category: "Vegetables",
    subCategory: "pepper",
    photo: "/images/product-images/pepper.webp",
  },
  {
    name: "Cubanelle Peppers",
    category: "Vegetables",
    subCategory: "pepper",
    photo: "/images/product-images/pepper.webp",
  },
  {
    name: "Carolina Reaper Peppers",
    category: "Vegetables",
    subCategory: "pepper",
    photo: "/images/product-images/carolina.webp",
  },
  {
    name: "Ghost Peppers",
    category: "Vegetables",
    subCategory: "pepper",
    photo: "/images/product-images/Ghost-pepper.webp",
  },
  {
    name: "Scotch Bonnet Peppers",
    category: "Vegetables",
    subCategory: "pepper",
    photo: "/images/product-images/pepper.webp",
  },
  {
    name: "Aji Amarillo Peppers",
    category: "Vegetables",
    subCategory: "pepper",
    photo: "/images/product-images/pepper.webp",
  },
  {
    name: "Peperoncini Peppers",
    category: "Vegetables",
    subCategory: "pepper",
    photo: "/images/product-images/peperon.webp",
  },
  {
    name: "Shishito Peppers",
    category: "Vegetables",
    subCategory: "pepper",
    photo: "/images/product-images/pepper.webp",
  },
  {
    name: "Iceberg Lettuce",
    category: "Vegetables",
    subCategory: "lettuce",
    photo: "/images/product-images/iceberg.webp",
  },
  {
    name: "Romaine Lettuce",
    category: "Vegetables",
    subCategory: "lettuce",
    photo: "/images/product-images/Romaine.webp",
  },
  {
    name: "Butterhead Lettuce",
    category: "Vegetables",
    subCategory: "lettuce",
    photo: "/images/product-images/lettuce.webp",
  },
  {
    name: "Leaf Lettuce",
    category: "Vegetables",
    subCategory: "lettuce",
    photo: "/images/product-images/lettuce.webp",
  },
  {
    name: "Red Leaf Lettuce",
    category: "Vegetables",
    subCategory: "lettuce",
    photo: "/images/product-images/lettuce.webp",
  },
  {
    name: "Green Leaf Lettuce",
    category: "Vegetables",
    subCategory: "lettuce",
    photo: "/images/product-images/lettuce.webp",
  },
  {
    name: "Boston Lettuce",
    category: "Vegetables",
    subCategory: "lettuce",
    photo: "/images/product-images/lettuce.webp",
  },
  {
    name: "Summer Crisp Lettuce",
    category: "Vegetables",
    subCategory: "lettuce",
    photo: "/images/product-images/lettuce.webp",
  },
  {
    name: "Batavia Lettuce",
    category: "Vegetables",
    subCategory: "lettuce",
    photo: "/images/product-images/lettuce.webp",
  },
  {
    name: "Arugula Lettuce",
    category: "Vegetables",
    subCategory: "lettuce",
    photo: "/images/product-images/Arugula.webp",
  },
  {
    name: "Frisee Lettuce",
    category: "Vegetables",
    subCategory: "lettuce",
    photo: "/images/product-images/lettuce.webp",
  },
  {
    name: "Oak Leaf Lettuce",
    category: "Vegetables",
    subCategory: "lettuce",
    photo: "/images/product-images/lettuce.webp",
  },
  {
    name: "Crisphead Lettuce",
    category: "Vegetables",
    subCategory: "lettuce",
    photo: "/images/product-images/lettuce.webp",
  },
  {
    name: "Endive Lettuce",
    category: "Vegetables",
    subCategory: "lettuce",
    photo: "/images/product-images/lettuce.webp",
  },
  {
    name: "Escarole Lettuce",
    category: "Vegetables",
    subCategory: "lettuce",
    photo: "/images/product-images/lettuce.webp",
  },
  {
    name: "Radichetta Lettuce",
    category: "Vegetables",
    subCategory: "lettuce",
    photo: "/images/product-images/lettuce.webp",
  },
  {
    name: "Tango Lettuce",
    category: "Vegetables",
    subCategory: "lettuce",
    photo: "/images/product-images/lettuce.webp",
  },
  {
    name: "Lollo Rosso Lettuce",
    category: "Vegetables",
    subCategory: "lettuce",
    photo: "/images/product-images/lettuce.webp",
  },
  {
    name: "Red Batavia Lettuce",
    category: "Vegetables",
    subCategory: "lettuce",
    photo: "/images/product-images/lettuce.webp",
  },
  {
    name: "Salanova Lettuce",
    category: "Vegetables",
    subCategory: "lettuce",
    photo: "/images/product-images/lettuce.webp",
  },
  {
    name: "Beef",
    category: "Meats",
    subCategory: "",
    photo: "/images/product-images/beef.webp",
  },
  {
    name: "Pork",
    category: "Meats",
    subCategory: "",
    photo: "/images/product-images/pork.webp",
  },
  {
    name: "Chicken",
    category: "Meats",
    subCategory: "",
    photo: "/images/product-images/chicken.webp",
  },
  {
    name: "Turkey",
    category: "Meats",
    subCategory: "",
    photo: "/images/product-images/turkey.webp",
  },
  {
    name: "Lamb",
    category: "Meats",
    subCategory: "",
    photo: "/images/product-images/lamb.webp",
  },
  {
    name: "Duck",
    category: "Meats",
    subCategory: "",
    photo: "/images/product-images/duck.webp",
  },
  {
    name: "Bison",
    category: "Meats",
    subCategory: "",
    photo: "/images/product-images/bison.webp",
  },
  {
    name: "Rabbit",
    category: "Meats",
    subCategory: "",
    photo: "/images/product-images/rabbit.webp",
  },
  {
    name: "Quail",
    category: "Meats",
    subCategory: "",
    photo: "/images/product-images/quail.webp",
  },
  {
    name: "Venison",
    category: "Meats",
    subCategory: "",
    photo: "/images/product-images/venison.webp",
  },

  {
    name: "Goose",
    category: "Meats",
    subCategory: "",
    photo: "/images/product-images/goose.webp",
  },
  {
    name: "Pheasant",
    category: "Meats",
    subCategory: "",
    photo: "/images/product-images/Pheasant.webp",
  },
  {
    name: "Wild Boar",
    category: "Meats",
    subCategory: "",
    photo: "/images/product-images/boar.webp",
  },
  {
    name: "Emu",
    category: "Meats",
    subCategory: "",
    photo: "/images/product-images/emu.webp",
  },
  {
    name: "Ostrich",
    category: "Meats",
    subCategory: "",
    photo: "/images/product-images/ostrich.webp",
  },
  {
    name: "Alligator",
    category: "Meats",
    subCategory: "",
    photo: "/images/product-images/Alligator.webp",
  },
  {
    name: "Frog",
    category: "Meats",
    subCategory: "",
    photo: "/images/product-images/frogleg.webp",
  },
  {
    name: "Milk",
    category: "Dairy",
    subCategory: "milk",
    photo: "/images/product-images/milk.webp",
  },
  {
    name: "Whole Milk",
    category: "Dairy",
    subCategory: "milk",
    photo: "/images/product-images/milk.webp",
  },
  {
    name: "2% Milk",
    category: "Dairy",
    subCategory: "milk",
    photo: "/images/product-images/milk.webp",
  },
  {
    name: "Heavy Whipping Cream",
    category: "Dairy",
    subCategory: "milk",
    photo: "/images/product-images/cream.webp",
  },
  {
    name: "Cheese",
    category: "Dairy",
    subCategory: "Cheese",
    photo: "/images/product-images/cheese.webp",
  },
  {
    name: "Yogurt",
    category: "Dairy",
    subCategory: "milk product",
    photo: "/images/product-images/yogurt.webp",
  },
  {
    name: "Butter",
    category: "Dairy",
    subCategory: "milk product",
    photo: "/images/product-images/butter.webp",
  },
  {
    name: "Cream",
    category: "Dairy",
    subCategory: "milk",
    photo: "/images/product-images/cream.webp",
  },
  {
    name: "Ice Cream",
    category: "Dairy",
    subCategory: "milk product",
    photo: "/images/product-images/icecream.webp",
  },
  {
    name: "Almonds",
    category: "Nuts",
    subCategory: "",
    photo: "/images/product-images/almond.webp",
  },
  {
    name: "Walnuts",
    category: "Nuts",
    subCategory: "",
    photo: "/images/product-images/walnut.webp",
  },
  {
    name: "Cashews",
    category: "Nuts",
    subCategory: "",
    photo: "/images/product-images/cashew.webp",
  },
  {
    name: "Pistachios",
    category: "Nuts",
    subCategory: "",
    photo: "/images/product-images/pistachio.webp",
  },
  {
    name: "Hazelnuts",
    category: "Nuts",
    subCategory: "",
    photo: "/images/product-images/hazel.webp",
  },
  {
    name: "Peanuts",
    category: "Nuts",
    subCategory: "",
    photo: "/images/product-images/peanuts.webp",
  },
  {
    name: "Baguette",
    category: "Bread",
    subCategory: "",
    photo: "/images/product-images/baguette.webp",
  },
  {
    name: "Sourdough",
    category: "Bread",
    subCategory: "",
    photo: "/images/product-images/sourdough.webp",
  },
  {
    name: "Whole Wheat",
    category: "Bread",
    subCategory: "",
    photo: "/images/product-images/whole_wheat.webp",
  },
  {
    name: "Rye Bread",
    category: "Bread",
    subCategory: "",
    photo: "/images/product-images/rye_bread.webp",
  },
  {
    name: "Ciabatta",
    category: "Bread",
    subCategory: "",
    photo: "/images/product-images/ciabatta.webp",
  },
  {
    name: "Multigrain",
    category: "Bread",
    subCategory: "",
    photo: "/images/product-images/multigrain.webp",
  },
  {
    name: "Olive Oil",
    category: "Oils",
    subCategory: "",
    photo: "/images/product-images/oil.webp",
  },
  {
    name: "Coconut Oil",
    category: "Oils",
    subCategory: "",
    photo: "/images/product-images/oil.webp",
  },
  {
    name: "Canola Oil",
    category: "Oils",
    subCategory: "",
    photo: "/images/product-images/oil.webp",
  },
  {
    name: "Sesame Oil",
    category: "Oils",
    subCategory: "",
    photo: "/images/product-images/oil.webp",
  },
  {
    name: "Sunflower Oil",
    category: "Oils",
    subCategory: "",
    photo: "/images/product-images/oil.webp",
  },
  {
    name: "Avocado Oil",
    category: "Oils",
    subCategory: "",
    photo: "/images/product-images/oil.webp",
  },
  {
    name: "Rice",
    category: "Grains",
    subCategory: "",
    photo: "/images/product-images/rice.webp",
  },
  {
    name: "Quinoa",
    category: "Grains",
    subCategory: "",
    photo: "/images/product-images/millet.webp",
  },
  {
    name: "Oats",
    category: "Grains",
    subCategory: "",
    photo: "/images/product-images/oats.webp",
  },
  {
    name: "Barley",
    category: "Grains",
    subCategory: "",
    photo: "/images/product-images/barley.webp",
  },
  {
    name: "Bulgur",
    category: "Grains",
    subCategory: "",
    photo: "/images/product-images/millet.webp",
  },
  {
    name: "Millet",
    category: "Grains",
    subCategory: "",
    photo: "/images/product-images/millet.webp",
  },
  {
    name: "Chocolate",
    category: "Sweets",
    subCategory: "",
    photo: "/images/product-images/chocolate.webp",
  },
  {
    name: "Cookies",
    category: "Sweets",
    subCategory: "",
    photo: "/images/product-images/cookies.webp",
  },
  {
    name: "Cake",
    category: "Sweets",
    subCategory: "",
    photo: "/images/product-images/cake.webp",
  },
  {
    name: "Gummies",
    category: "Sweets",
    subCategory: "",
    photo: "/images/product-images/gummies.webp",
  },
];

const formattedProducts = products.map((product) => ({
  value: product.name,
  label: product.name,
  cat: product.subCategory,
  photo: product.photo,
  category: product.category,
}));

const useProducts = () => {
  const getAll = () => formattedProducts;

  const getByValue = (value: string) => {
    return formattedProducts.find((item) => item.value === value);
  };

  return {
    getAll,
    getByValue,
  };
};

export default useProducts;
