const products = [
  {
    name: "Beefsteak Tomato",
    category: "Vegetable",
    subCategory: "Tomato",
    photo: "",
  },
  {
    name: "Cherry Tomato",
    category: "Vegetable",
    subCategory: "Tomato",
    photo: "",
  },
  {
    name: "Heirloom Tomato",
    category: "Vegetable",
    subCategory: "Tomato",
    photo: "",
  },
  {
    name: "Roma Tomato",
    category: "Vegetable",
    subCategory: "Tomato",
    photo: "",
  },
  {
    name: "Grape Tomato",
    category: "Vegetable",
    subCategory: "Tomato",
    photo: "",
  },
  {
    name: "San Marzano Tomato",
    category: "Vegetable",
    subCategory: "Tomato",
    photo: "",
  },
  {
    name: "Brandywine Tomato",
    category: "Vegetable",
    subCategory: "Tomato",
    photo: "",
  },
  {
    name: "Green Zebra Tomato",
    category: "Vegetable",
    subCategory: "Tomato",
    photo: "",
  },
  {
    name: "Cherokee Purple Tomato",
    category: "Vegetable",
    subCategory: "Tomato",
    photo: "",
  },
  {
    name: "Yellow Pear Tomato",
    category: "Vegetable",
    subCategory: "Tomato",
    photo: "",
  },
  {
    name: "Black Krim Tomato",
    category: "Vegetable",
    subCategory: "Tomato",
    photo: "",
  },
  {
    name: "Amish Paste Tomato",
    category: "Vegetable",
    subCategory: "Tomato",
    photo: "",
  },
  {
    name: "Celebrity Tomato",
    category: "Vegetable",
    subCategory: "Tomato",
    photo: "",
  },
  {
    name: "Early Girl Tomato",
    category: "Vegetable",
    subCategory: "Tomato",
    photo: "",
  },
  {
    name: "Big Boy Tomato",
    category: "Vegetable",
    subCategory: "Tomato",
    photo: "",
  },
  {
    name: "Sun Gold Tomato",
    category: "Vegetable",
    subCategory: "Tomato",
    photo: "",
  },
  {
    name: "Sweet Million Tomato",
    category: "Vegetable",
    subCategory: "Tomato",
    photo: "",
  },
  {
    name: "Mortgage Lifter Tomato",
    category: "Vegetable",
    subCategory: "Tomato",
    photo: "",
  },
  {
    name: "Pineapple Tomato",
    category: "Vegetable",
    subCategory: "Tomato",
    photo: "",
  },
  {
    name: "Supersweet 100 Tomato",
    category: "Vegetable",
    subCategory: "Tomato",
    photo: "",
  },
  {
    name: "Black Cherry Tomato",
    category: "Vegetable",
    subCategory: "Tomato",
    photo: "",
  },
  {
    name: "Campari Tomato",
    category: "Vegetable",
    subCategory: "Tomato",
    photo: "",
  },
  {
    name: "Kumato Tomato",
    category: "Vegetable",
    subCategory: "Tomato",
    photo: "",
  },
  {
    name: "Principe Borghese Tomato",
    category: "Vegetable",
    subCategory: "Tomato",
    photo: "",
  },
  {
    name: "Rutgers Tomato",
    category: "Vegetable",
    subCategory: "Tomato",
    photo: "",
  },
  {
    name: "Paul Robeson Tomato",
    category: "Vegetable",
    subCategory: "Tomato",
    photo: "",
  },
  {
    name: "Arkansas Traveler Tomato",
    category: "Vegetable",
    subCategory: "Tomato",
    photo: "",
  },
  {
    name: "Persimmon Tomato",
    category: "Vegetable",
    subCategory: "Tomato",
    photo: "",
  },
  {
    name: "Costoluto Genovese Tomato",
    category: "Vegetable",
    subCategory: "Tomato",
    photo: "",
  },
  {
    name: "Striped German Tomato",
    category: "Vegetable",
    subCategory: "Tomato",
    photo: "",
  },
  {
    name: "Golden Jubilee Tomato",
    category: "Vegetable",
    subCategory: "Tomato",
    photo: "",
  },
  {
    name: "Green Giant Tomato",
    category: "Vegetable",
    subCategory: "Tomato",
    photo: "",
  },
  {
    name: "Orange Wellington Tomato",
    category: "Vegetable",
    subCategory: "Tomato",
    photo: "",
  },
  {
    name: "Pink Brandywine Tomato",
    category: "Vegetable",
    subCategory: "Tomato",
    photo: "",
  },
  {
    name: "Red Currant Tomato",
    category: "Vegetable",
    subCategory: "Tomato",
    photo: "",
  },
  {
    name: "Snow White Tomato",
    category: "Vegetable",
    subCategory: "Tomato",
    photo: "",
  },
  {
    name: "Yellow Brandywine Tomato",
    category: "Vegetable",
    subCategory: "Tomato",
    photo: "",
  },
  {
    name: "Black Pineapple Tomato",
    category: "Vegetable",
    subCategory: "Tomato",
    photo: "",
  },
  {
    name: "Blondkopfchen Tomato",
    category: "Vegetable",
    subCategory: "Tomato",
    photo: "",
  },
  {
    name: "Caspian Pink Tomato",
    category: "Vegetable",
    subCategory: "Tomato",
    photo: "",
  },
  {
    name: "German Johnson Tomato",
    category: "Vegetable",
    subCategory: "Tomato",
    photo: "",
  },
  {
    name: "Hillbilly Tomato",
    category: "Vegetable",
    subCategory: "Tomato",
    photo: "",
  },
  {
    name: "Indigo Rose Tomato",
    category: "Vegetable",
    subCategory: "Tomato",
    photo: "",
  },
  {
    name: "Japanese Black Trifele Tomato",
    category: "Vegetable",
    subCategory: "Tomato",
    photo: "",
  },
  {
    name: "Kellogg's Breakfast Tomato",
    category: "Vegetable",
    subCategory: "Tomato",
    photo: "",
  },
  {
    name: "Marianna's Peace Tomato",
    category: "Vegetable",
    subCategory: "Tomato",
    photo: "",
  },
  {
    name: "Old German Tomato",
    category: "Vegetable",
    subCategory: "Tomato",
    photo: "",
  },
  {
    name: "Purple Calabash Tomato",
    category: "Vegetable",
    subCategory: "Tomato",
    photo: "",
  },
  {
    name: "Rose de Berne Tomato",
    category: "Vegetable",
    subCategory: "Tomato",
    photo: "",
  },
  {
    name: "Tigerella Tomato",
    category: "Vegetable",
    subCategory: "Tomato",
    photo: "",
  },
  {
    name: "Valencia Tomato",
    category: "Vegetable",
    subCategory: "Tomato",
    photo: "",
  },
  {
    name: "Red Delicious Apple",
    category: "Fruit",
    subCategory: "Apple",
    photo: "",
  },
  {
    name: "Granny Smith Apple",
    category: "Fruit",
    subCategory: "Apple",
    photo: "",
  },
  {
    name: "Fuji Apple",
    category: "Fruit",
    subCategory: "Apple",
    photo: "",
  },
  {
    name: "Gala Apple",
    category: "Fruit",
    subCategory: "Apple",
    photo: "",
  },
  {
    name: "Honeycrisp Apple",
    category: "Fruit",
    subCategory: "Apple",
    photo: "",
  },
  {
    name: "Golden Delicious Apple",
    category: "Fruit",
    subCategory: "Apple",
    photo: "",
  },
  {
    name: "Pink Lady Apple",
    category: "Fruit",
    subCategory: "Apple",
    photo: "",
  },
  {
    name: "McIntosh Apple",
    category: "Fruit",
    subCategory: "Apple",
    photo: "",
  },
  {
    name: "Braeburn Apple",
    category: "Fruit",
    subCategory: "Apple",
    photo: "",
  },
  {
    name: "Jonagold Apple",
    category: "Fruit",
    subCategory: "Apple",
    photo: "",
  },
  {
    name: "Cortland Apple",
    category: "Fruit",
    subCategory: "Apple",
    photo: "",
  },
  {
    name: "Empire Apple",
    category: "Fruit",
    subCategory: "Apple",
    photo: "",
  },
  {
    name: "Arkansas Black Apple",
    category: "Fruit",
    subCategory: "Apple",
    photo: "",
  },
  {
    name: "Rome Apple",
    category: "Fruit",
    subCategory: "Apple",
    photo: "",
  },
  {
    name: "Ambrosia Apple",
    category: "Fruit",
    subCategory: "Apple",
    photo: "",
  },
  {
    name: "Jazz Apple",
    category: "Fruit",
    subCategory: "Apple",
    photo: "",
  },
  {
    name: "Cameo Apple",
    category: "Fruit",
    subCategory: "Apple",
    photo: "",
  },
  {
    name: "Opal Apple",
    category: "Fruit",
    subCategory: "Apple",
    photo: "",
  },
  {
    name: "Winesap Apple",
    category: "Fruit",
    subCategory: "Apple",
    photo: "",
  },
  {
    name: "Mutsu Apple",
    category: "Fruit",
    subCategory: "Apple",
    photo: "",
  },
  {
    name: "York Apple",
    category: "Fruit",
    subCategory: "Apple",
    photo: "",
  },
  {
    name: "Pink Pearl Apple",
    category: "Fruit",
    subCategory: "Apple",
    photo: "",
  },
  {
    name: "Liberty Apple",
    category: "Fruit",
    subCategory: "Apple",
    photo: "",
  },
  {
    name: "Ginger Gold Apple",
    category: "Fruit",
    subCategory: "Apple",
    photo: "",
  },
  {
    name: "Paula Red Apple",
    category: "Fruit",
    subCategory: "Apple",
    photo: "",
  },
  {
    name: "Northern Spy Apple",
    category: "Fruit",
    subCategory: "Apple",
    photo: "",
  },
  {
    name: "Gravenstein Apple",
    category: "Fruit",
    subCategory: "Apple",
    photo: "",
  },
  {
    name: "Jonathan Apple",
    category: "Fruit",
    subCategory: "Apple",
    photo: "",
  },
  {
    name: "SunCrisp Apple",
    category: "Fruit",
    subCategory: "Apple",
    photo: "",
  },
  {
    name: "Crimson Crisp Apple",
    category: "Fruit",
    subCategory: "Apple",
    photo: "",
  },
  {
    name: "EverCrisp Apple",
    category: "Fruit",
    subCategory: "Apple",
    photo: "",
  },
  {
    name: "SnowSweet Apple",
    category: "Fruit",
    subCategory: "Apple",
    photo: "",
  },
  {
    name: "Snowdrift Apple",
    category: "Fruit",
    subCategory: "Apple",
    photo: "",
  },
  {
    name: "SweeTango Apple",
    category: "Fruit",
    subCategory: "Apple",
    photo: "",
  },
  {
    name: "WineCrisp Apple",
    category: "Fruit",
    subCategory: "Apple",
    photo: "",
  },
  {
    name: "RubyFrost Apple",
    category: "Fruit",
    subCategory: "Apple",
    photo: "",
  },
  {
    name: "Autumn Glory Apple",
    category: "Fruit",
    subCategory: "Apple",
    photo: "",
  },
  {
    name: "Cosmic Crisp Apple",
    category: "Fruit",
    subCategory: "Apple",
    photo: "",
  },
  {
    name: "Smitten Apple",
    category: "Fruit",
    subCategory: "Apple",
    photo: "",
  },
  {
    name: "Kiku Apple",
    category: "Fruit",
    subCategory: "Apple",
    photo: "",
  },
  {
    name: "Envy Apple",
    category: "Fruit",
    subCategory: "Apple",
    photo: "",
  },
  {
    name: "Snapdragon Apple",
    category: "Fruit",
    subCategory: "Apple",
    photo: "",
  },
  {
    name: "Pacific Rose Apple",
    category: "Fruit",
    subCategory: "Apple",
    photo: "",
  },
  {
    name: "Kanzi Apple",
    category: "Fruit",
    subCategory: "Apple",
    photo: "",
  },
  {
    name: "Ambri Apple",
    category: "Fruit",
    subCategory: "Apple",
    photo: "",
  },
  {
    name: "SweeTango Tango Apple",
    category: "Fruit",
    subCategory: "Apple",
    photo: "",
  },
  {
    name: "SweeTango Zester Apple",
    category: "Fruit",
    subCategory: "Apple",
    photo: "",
  },
  {
    name: "Sweetie Apple",
    category: "Fruit",
    subCategory: "Apple",
    photo: "",
  },
  {
    name: "Sweetie Pie Apple",
    category: "Fruit",
    subCategory: "Apple",
    photo: "",
  },
  {
    name: "Sweetie Treat Apple",
    category: "Fruit",
    subCategory: "Apple",
    photo: "",
  },
  {
    name: "Anjou Pear",
    category: "Fruit",
    subCategory: "Pear",
    photo: "",
  },
  {
    name: "Bartlett Pear",
    category: "Fruit",
    subCategory: "Pear",
    photo: "",
  },
  {
    name: "Bosc Pear",
    category: "Fruit",
    subCategory: "Pear",
    photo: "",
  },
  {
    name: "Comice Pear",
    category: "Fruit",
    subCategory: "Pear",
    photo: "",
  },
  {
    name: "Forelle Pear",
    category: "Fruit",
    subCategory: "Pear",
    photo: "",
  },
  {
    name: "Seckel Pear",
    category: "Fruit",
    subCategory: "Pear",
    photo: "",
  },
  {
    name: "Concorde Pear",
    category: "Fruit",
    subCategory: "Pear",
    photo: "",
  },
  {
    name: "Starkrimson Pear",
    category: "Fruit",
    subCategory: "Pear",
    photo: "",
  },
  {
    name: "Asian Pear",
    category: "Fruit",
    subCategory: "Pear",
    photo: "",
  },
  {
    name: "Forelle Pear",
    category: "Fruit",
    subCategory: "Pear",
    photo: "",
  },
  {
    name: "Red Anjou Pear",
    category: "Fruit",
    subCategory: "Pear",
    photo: "",
  },
  {
    name: "Green Anjou Pear",
    category: "Fruit",
    subCategory: "Pear",
    photo: "",
  },
  {
    name: "Concorde Pear",
    category: "Fruit",
    subCategory: "Pear",
    photo: "",
  },
  {
    name: "Starkrimson Pear",
    category: "Fruit",
    subCategory: "Pear",
    photo: "",
  },
  {
    name: "Comice Pear",
    category: "Fruit",
    subCategory: "Pear",
    photo: "",
  },
  {
    name: "Red Bartlett Pear",
    category: "Fruit",
    subCategory: "Pear",
    photo: "",
  },
  {
    name: "Brown Bartlett Pear",
    category: "Fruit",
    subCategory: "Pear",
    photo: "",
  },
  {
    name: "Green Bartlett Pear",
    category: "Fruit",
    subCategory: "Pear",
    photo: "",
  },
  {
    name: "Red Sensation Pear",
    category: "Fruit",
    subCategory: "Pear",
    photo: "",
  },
  {
    name: "Hosui Asian Pear",
    category: "Fruit",
    subCategory: "Pear",
    photo: "",
  },
  {
    name: "Shinseiki Asian Pear",
    category: "Fruit",
    subCategory: "Pear",
    photo: "",
  },
  {
    name: "20th Century Asian Pear",
    category: "Fruit",
    subCategory: "Pear",
    photo: "",
  },
  {
    name: "Ya Li Asian Pear",
    category: "Fruit",
    subCategory: "Pear",
    photo: "",
  },
  {
    name: "Harrow Sweet Pear",
    category: "Fruit",
    subCategory: "Pear",
    photo: "",
  },
  {
    name: "Magness Pear",
    category: "Fruit",
    subCategory: "Pear",
    photo: "",
  },
  {
    name: "Moonglow Pear",
    category: "Fruit",
    subCategory: "Pear",
    photo: "",
  },
  {
    name: "Blake's Pride Pear",
    category: "Fruit",
    subCategory: "Pear",
    photo: "",
  },
  {
    name: "Harrow Delight Pear",
    category: "Fruit",
    subCategory: "Pear",
    photo: "",
  },
  {
    name: "Summercrisp Pear",
    category: "Fruit",
    subCategory: "Pear",
    photo: "",
  },
  {
    name: "Harrow Crisp Pear",
    category: "Fruit",
    subCategory: "Pear",
    photo: "",
  },
  {
    name: "Orcas Pear",
    category: "Fruit",
    subCategory: "Pear",
    photo: "",
  },
  {
    name: "Rescue Pear",
    category: "Fruit",
    subCategory: "Pear",
    photo: "",
  },
  {
    name: "Moonglow Pear",
    category: "Fruit",
    subCategory: "Pear",
    photo: "",
  },
  {
    name: "D'Anjou Pear",
    category: "Fruit",
    subCategory: "Pear",
    photo: "",
  },
  {
    name: "Red D'Anjou Pear",
    category: "Fruit",
    subCategory: "Pear",
    photo: "",
  },
  {
    name: "Green D'Anjou Pear",
    category: "Fruit",
    subCategory: "Pear",
    photo: "",
  },
  {
    name: "Max Red Bartlett Pear",
    category: "Fruit",
    subCategory: "Pear",
    photo: "",
  },
  {
    name: "Maxie Pear",
    category: "Fruit",
    subCategory: "Pear",
    photo: "",
  },
  {
    name: "Pineapple Pear",
    category: "Fruit",
    subCategory: "Pear",
    photo: "",
  },
  {
    name: "Warren Pear",
    category: "Fruit",
    subCategory: "Pear",
    photo: "",
  },
  {
    name: "Warren Pear",
    category: "Fruit",
    subCategory: "Pear",
    photo: "",
  },
  {
    name: "Ayers Pear",
    category: "Fruit",
    subCategory: "Pear",
    photo: "",
  },
  {
    name: "Le Conte Pear",
    category: "Fruit",
    subCategory: "Pear",
    photo: "",
  },
  {
    name: "Kieffer Pear",
    category: "Fruit",
    subCategory: "Pear",
    photo: "",
  },
  {
    name: "Blake's Pride Pear",
    category: "Fruit",
    subCategory: "Pear",
    photo: "",
  },
  {
    name: "Luscious Pear",
    category: "Fruit",
    subCategory: "Pear",
    photo: "",
  },
  {
    name: "Orca Pear",
    category: "Fruit",
    subCategory: "Pear",
    photo: "",
  },
  {
    name: "Olympic Pear",
    category: "Fruit",
    subCategory: "Pear",
    photo: "",
  },
  {
    name: "Navel Orange",
    category: "Fruit",
    subCategory: "Orange",
    photo: "",
  },
  {
    name: "Valencia Orange",
    category: "Fruit",
    subCategory: "Orange",
    photo: "",
  },
  {
    name: "Blood Orange",
    category: "Fruit",
    subCategory: "Orange",
    photo: "",
  },
  {
    name: "Cara Cara Orange",
    category: "Fruit",
    subCategory: "Orange",
    photo: "",
  },
  {
    name: "Seville Orange",
    category: "Fruit",
    subCategory: "Orange",
    photo: "",
  },
  {
    name: "Mandarin Orange",
    category: "Fruit",
    subCategory: "Orange",
    photo: "",
  },
  {
    name: "Satsuma Orange",
    category: "Fruit",
    subCategory: "Orange",
    photo: "",
  },
  {
    name: "Clementine Orange",
    category: "Fruit",
    subCategory: "Orange",
    photo: "",
  },
  {
    name: "Tangerine Orange",
    category: "Fruit",
    subCategory: "Orange",
    photo: "",
  },
  {
    name: "Moro Orange",
    category: "Fruit",
    subCategory: "Orange",
    photo: "",
  },
  {
    name: "Ambersweet Orange",
    category: "Fruit",
    subCategory: "Orange",
    photo: "",
  },
  {
    name: "Temple Orange",
    category: "Fruit",
    subCategory: "Orange",
    photo: "",
  },
  {
    name: "Sour Orange",
    category: "Fruit",
    subCategory: "Orange",
    photo: "",
  },
  {
    name: "Clementine Mandarin Orange",
    category: "Fruit",
    subCategory: "Orange",
    photo: "",
  },
  {
    name: "Dancy Tangerine Orange",
    category: "Fruit",
    subCategory: "Orange",
    photo: "",
  },
  {
    name: "Nova Tangerine Orange",
    category: "Fruit",
    subCategory: "Orange",
    photo: "",
  },
  {
    name: "Sunburst Tangerine Orange",
    category: "Fruit",
    subCategory: "Orange",
    photo: "",
  },
  {
    name: "Fairchild Tangerine Orange",
    category: "Fruit",
    subCategory: "Orange",
    photo: "",
  },
  {
    name: "Robinson Tangerine Orange",
    category: "Fruit",
    subCategory: "Orange",
    photo: "",
  },
  {
    name: "Orlando Tangelo Orange",
    category: "Fruit",
    subCategory: "Orange",
    photo: "",
  },
  {
    name: "Minneola Tangelo Orange",
    category: "Fruit",
    subCategory: "Orange",
    photo: "",
  },
  {
    name: "Ugli Fruit",
    category: "Fruit",
    subCategory: "Orange",
    photo: "",
  },
  {
    name: "Tangor Orange",
    category: "Fruit",
    subCategory: "Orange",
    photo: "",
  },
  {
    name: "Lemonade Lemon Orange",
    category: "Fruit",
    subCategory: "Orange",
    photo: "",
  },
  {
    name: "Sour Lemon Orange",
    category: "Fruit",
    subCategory: "Orange",
    photo: "",
  },
  {
    name: "Tangelo Orange",
    category: "Fruit",
    subCategory: "Orange",
    photo: "",
  },
  {
    name: "Seminole Orange",
    category: "Fruit",
    subCategory: "Orange",
    photo: "",
  },
  {
    name: "Pineapple Orange",
    category: "Fruit",
    subCategory: "Orange",
    photo: "",
  },
  {
    name: "Bitter Orange",
    category: "Fruit",
    subCategory: "Orange",
    photo: "",
  },
  {
    name: "Trifoliate Orange",
    category: "Fruit",
    subCategory: "Orange",
    photo: "",
  },
  {
    name: "Cleopatra Mandarin Orange",
    category: "Fruit",
    subCategory: "Orange",
    photo: "",
  },
  {
    name: "Kumquat Mandarin Orange",
    category: "Fruit",
    subCategory: "Orange",
    photo: "",
  },
  {
    name: "Willowleaf Mandarin Orange",
    category: "Fruit",
    subCategory: "Orange",
    photo: "",
  },
  {
    name: "Kinnow Mandarin Orange",
    category: "Fruit",
    subCategory: "Orange",
    photo: "",
  },
  {
    name: "Sunki Mandarin Orange",
    category: "Fruit",
    subCategory: "Orange",
    photo: "",
  },
  {
    name: "Ponkan Mandarin Orange",
    category: "Fruit",
    subCategory: "Orange",
    photo: "",
  },
  {
    name: "Dekopon Mandarin Orange",
    category: "Fruit",
    subCategory: "Orange",
    photo: "",
  },
  {
    name: "Yuzu Mandarin Orange",
    category: "Fruit",
    subCategory: "Orange",
    photo: "",
  },
  {
    name: "Khasi Mandarin Orange",
    category: "Fruit",
    subCategory: "Orange",
    photo: "",
  },
  {
    name: "Clementine Hybrid Orange",
    category: "Fruit",
    subCategory: "Orange",
    photo: "",
  },
  {
    name: "Satsuma Hybrid Orange",
    category: "Fruit",
    subCategory: "Orange",
    photo: "",
  },
  {
    name: "Tangor Hybrid Orange",
    category: "Fruit",
    subCategory: "Orange",
    photo: "",
  },
  {
    name: "Tangelo Hybrid Orange",
    category: "Fruit",
    subCategory: "Orange",
    photo: "",
  },
  {
    name: "Clementine Hybrid Orange",
    category: "Fruit",
    subCategory: "Orange",
    photo: "",
  },
  {
    name: "Nova Tangelo Hybrid Orange",
    category: "Fruit",
    subCategory: "Orange",
    photo: "",
  },
  {
    name: "Ortanique Hybrid Orange",
    category: "Fruit",
    subCategory: "Orange",
    photo: "",
  },
  {
    name: "Nantes Carrot",
    category: "Vegetable",
    subCategory: "Carrot",
    photo: "",
  },
  {
    name: "Danvers Carrot",
    category: "Vegetable",
    subCategory: "Carrot",
    photo: "",
  },
  {
    name: "Imperator Carrot",
    category: "Vegetable",
    subCategory: "Carrot",
    photo: "",
  },
  {
    name: "Chantenay Carrot",
    category: "Vegetable",
    subCategory: "Carrot",
    photo: "",
  },
  {
    name: "Paris Market Carrot",
    category: "Vegetable",
    subCategory: "Carrot",
    photo: "",
  },
  {
    name: "Babette Carrot",
    category: "Vegetable",
    subCategory: "Carrot",
    photo: "",
  },
  {
    name: "Little Finger Carrot",
    category: "Vegetable",
    subCategory: "Carrot",
    photo: "",
  },
  {
    name: "Scarlet Nantes Carrot",
    category: "Vegetable",
    subCategory: "Carrot",
    photo: "",
  },
  {
    name: "Kuroda Carrot",
    category: "Vegetable",
    subCategory: "Carrot",
    photo: "",
  },
  {
    name: "Atomic Red Carrot",
    category: "Vegetable",
    subCategory: "Carrot",
    photo: "",
  },
  {
    name: "Cosmic Purple Carrot",
    category: "Vegetable",
    subCategory: "Carrot",
    photo: "",
  },
  {
    name: "Solar Yellow Carrot",
    category: "Vegetable",
    subCategory: "Carrot",
    photo: "",
  },
  {
    name: "Lunar White Carrot",
    category: "Vegetable",
    subCategory: "Carrot",
    photo: "",
  },
  {
    name: "Bolero Carrot",
    category: "Vegetable",
    subCategory: "Carrot",
    photo: "",
  },
  {
    name: "Thumbelina Carrot",
    category: "Vegetable",
    subCategory: "Carrot",
    photo: "",
  },
  {
    name: "Dragon Carrot",
    category: "Vegetable",
    subCategory: "Carrot",
    photo: "",
  },
  {
    name: "Purple Haze Carrot",
    category: "Vegetable",
    subCategory: "Carrot",
    photo: "",
  },
  {
    name: "Atomic Red Carrot",
    category: "Vegetable",
    subCategory: "Carrot",
    photo: "",
  },
  {
    name: "Cosmic Purple Carrot",
    category: "Vegetable",
    subCategory: "Carrot",
    photo: "",
  },
  {
    name: "Solar Yellow Carrot",
    category: "Vegetable",
    subCategory: "Carrot",
    photo: "",
  },
  {
    name: "Lunar White Carrot",
    category: "Vegetable",
    subCategory: "Carrot",
    photo: "",
  },
  {
    name: "Bolero Carrot",
    category: "Vegetable",
    subCategory: "Carrot",
    photo: "",
  },
  {
    name: "Thumbelina Carrot",
    category: "Vegetable",
    subCategory: "Carrot",
    photo: "",
  },
  {
    name: "Dragon Carrot",
    category: "Vegetable",
    subCategory: "Carrot",
    photo: "",
  },
  {
    name: "Purple Haze Carrot",
    category: "Vegetable",
    subCategory: "Carrot",
    photo: "",
  },
  {
    name: "Yellowstone Carrot",
    category: "Vegetable",
    subCategory: "Carrot",
    photo: "",
  },
  {
    name: "Red Samurai Carrot",
    category: "Vegetable",
    subCategory: "Carrot",
    photo: "",
  },
  {
    name: "Sweet Treat Carrot",
    category: "Vegetable",
    subCategory: "Carrot",
    photo: "",
  },
  {
    name: "Sugarsnax Carrot",
    category: "Vegetable",
    subCategory: "Carrot",
    photo: "",
  },
  {
    name: "Kaleidoscope Carrot",
    category: "Vegetable",
    subCategory: "Carrot",
    photo: "",
  },
  {
    name: "Purple Elite Carrot",
    category: "Vegetable",
    subCategory: "Carrot",
    photo: "",
  },
  {
    name: "Merida Carrot",
    category: "Vegetable",
    subCategory: "Carrot",
    photo: "",
  },
  {
    name: "Sugarsnax Hybrid Carrot",
    category: "Vegetable",
    subCategory: "Carrot",
    photo: "",
  },
  {
    name: "Babette Carrot",
    category: "Vegetable",
    subCategory: "Carrot",
    photo: "",
  },
  {
    name: "Kinko Carrot",
    category: "Vegetable",
    subCategory: "Carrot",
    photo: "",
  },
  {
    name: "Purple 68 Carrot",
    category: "Vegetable",
    subCategory: "Carrot",
    photo: "",
  },
  {
    name: "Amsterdam Carrot",
    category: "Vegetable",
    subCategory: "Carrot",
    photo: "",
  },
  {
    name: "Sweetness III Carrot",
    category: "Vegetable",
    subCategory: "Carrot",
    photo: "",
  },
  {
    name: "Sugarsnax Hybrid Carrot",
    category: "Vegetable",
    subCategory: "Carrot",
    photo: "",
  },
  {
    name: "Hercules Carrot",
    category: "Vegetable",
    subCategory: "Carrot",
    photo: "",
  },
  {
    name: "Kaleidoscope Carrot",
    category: "Vegetable",
    subCategory: "Carrot",
    photo: "",
  },
  {
    name: "Purple Elite Carrot",
    category: "Vegetable",
    subCategory: "Carrot",
    photo: "",
  },
  {
    name: "Merida Carrot",
    category: "Vegetable",
    subCategory: "Carrot",
    photo: "",
  },
  {
    name: "Babette Carrot",
    category: "Vegetable",
    subCategory: "Carrot",
    photo: "",
  },
  {
    name: "Bloomsdale Spinach",
    category: "Vegetable",
    subCategory: "Spinach",
    photo: "",
  },
  {
    name: "Baby Spinach",
    category: "Vegetable",
    subCategory: "Spinach",
    photo: "",
  },
  {
    name: "Savoy Spinach",
    category: "Vegetable",
    subCategory: "Spinach",
    photo: "",
  },
  {
    name: "Malabar Spinach",
    category: "Vegetable",
    subCategory: "Spinach",
    photo: "",
  },
  {
    name: "Red Kitten Spinach",
    category: "Vegetable",
    subCategory: "Spinach",
    photo: "",
  },
  {
    name: "Tyee Spinach",
    category: "Vegetable",
    subCategory: "Spinach",
    photo: "",
  },
  {
    name: "Space Spinach",
    category: "Vegetable",
    subCategory: "Spinach",
    photo: "",
  },
  {
    name: "Giant Winter Spinach",
    category: "Vegetable",
    subCategory: "Spinach",
    photo: "",
  },
  {
    name: "Matador Spinach",
    category: "Vegetable",
    subCategory: "Spinach",
    photo: "",
  },
  {
    name: "Corvair Spinach",
    category: "Vegetable",
    subCategory: "Spinach",
    photo: "",
  },
  {
    name: "Regiment Spinach",
    category: "Vegetable",
    subCategory: "Spinach",
    photo: "",
  },
  {
    name: "Space Spinach",
    category: "Vegetable",
    subCategory: "Spinach",
    photo: "",
  },
  {
    name: "Reflect Spinach",
    category: "Vegetable",
    subCategory: "Spinach",
    photo: "",
  },
  {
    name: "Avenger Spinach",
    category: "Vegetable",
    subCategory: "Spinach",
    photo: "",
  },
  {
    name: "Coronet Spinach",
    category: "Vegetable",
    subCategory: "Spinach",
    photo: "",
  },
  {
    name: "Catalyst Spinach",
    category: "Vegetable",
    subCategory: "Spinach",
    photo: "",
  },
  {
    name: "Giant Nobel Spinach",
    category: "Vegetable",
    subCategory: "Spinach",
    photo: "",
  },
  {
    name: "Red Cardinal Spinach",
    category: "Vegetable",
    subCategory: "Spinach",
    photo: "",
  },
  {
    name: "Vienna Spinach",
    category: "Vegetable",
    subCategory: "Spinach",
    photo: "",
  },
  {
    name: "Nobel Giant Spinach",
    category: "Vegetable",
    subCategory: "Spinach",
    photo: "",
  },
  {
    name: "Calabrese Broccoli",
    category: "Vegetable",
    subCategory: "Broccoli",
    photo: "",
  },
  {
    name: "Sprouting Broccoli",
    category: "Vegetable",
    subCategory: "Broccoli",
    photo: "",
  },
  {
    name: "Romanesco Broccoli",
    category: "Vegetable",
    subCategory: "Broccoli",
    photo: "",
  },
  {
    name: "Purple Sprouting Broccoli",
    category: "Vegetable",
    subCategory: "Broccoli",
    photo: "",
  },
  {
    name: "Broccolini",
    category: "Vegetable",
    subCategory: "Broccoli",
    photo: "",
  },
  {
    name: "Broccoflower",
    category: "Vegetable",
    subCategory: "Broccoli",
    photo: "",
  },
  {
    name: "Baby Broccoli",
    category: "Vegetable",
    subCategory: "Broccoli",
    photo: "",
  },
  {
    name: "Purple Broccoli",
    category: "Vegetable",
    subCategory: "Broccoli",
    photo: "",
  },
  {
    name: "White Sprouting Broccoli",
    category: "Vegetable",
    subCategory: "Broccoli",
    photo: "",
  },
  {
    name: "Belstar Broccoli",
    category: "Vegetable",
    subCategory: "Broccoli",
    photo: "",
  },
  {
    name: "Green Magic Broccoli",
    category: "Vegetable",
    subCategory: "Broccoli",
    photo: "",
  },
  {
    name: "Imperial Broccoli",
    category: "Vegetable",
    subCategory: "Broccoli",
    photo: "",
  },
  {
    name: "Paragon Broccoli",
    category: "Vegetable",
    subCategory: "Broccoli",
    photo: "",
  },
  {
    name: "Arcadia Broccoli",
    category: "Vegetable",
    subCategory: "Broccoli",
    photo: "",
  },
  {
    name: "Green Goliath Broccoli",
    category: "Vegetable",
    subCategory: "Broccoli",
    photo: "",
  },
  {
    name: "Marathon Broccoli",
    category: "Vegetable",
    subCategory: "Broccoli",
    photo: "",
  },
  {
    name: "Packman Broccoli",
    category: "Vegetable",
    subCategory: "Broccoli",
    photo: "",
  },
  {
    name: "Belstar Broccoli",
    category: "Vegetable",
    subCategory: "Broccoli",
    photo: "",
  },
  {
    name: "Green Magic Broccoli",
    category: "Vegetable",
    subCategory: "Broccoli",
    photo: "",
  },
  {
    name: "Imperial Broccoli",
    category: "Vegetable",
    subCategory: "Broccoli",
    photo: "",
  },
  {
    name: "Concord Grape",
    category: "Fruit",
    subCategory: "Grape",
    photo: "",
  },
  {
    name: "Thompson Seedless Grape",
    category: "Fruit",
    subCategory: "Grape",
    photo: "",
  },
  {
    name: "Red Globe Grape",
    category: "Fruit",
    subCategory: "Grape",
    photo: "",
  },
  {
    name: "Crimson Seedless Grape",
    category: "Fruit",
    subCategory: "Grape",
    photo: "",
  },
  {
    name: "Chardonnay Grape",
    category: "Fruit",
    subCategory: "Grape",
    photo: "",
  },
  {
    name: "Cabernet Sauvignon Grape",
    category: "Fruit",
    subCategory: "Grape",
    photo: "",
  },
  {
    name: "Pinot Noir Grape",
    category: "Fruit",
    subCategory: "Grape",
    photo: "",
  },
  {
    name: "Muscat Grape",
    category: "Fruit",
    subCategory: "Grape",
    photo: "",
  },
  {
    name: "Merlot Grape",
    category: "Fruit",
    subCategory: "Grape",
    photo: "",
  },
  {
    name: "Zinfandel Grape",
    category: "Fruit",
    subCategory: "Grape",
    photo: "",
  },
  {
    name: "Cabernet Franc Grape",
    category: "Fruit",
    subCategory: "Grape",
    photo: "",
  },
  {
    name: "Syrah Grape",
    category: "Fruit",
    subCategory: "Grape",
    photo: "",
  },
  {
    name: "Riesling Grape",
    category: "Fruit",
    subCategory: "Grape",
    photo: "",
  },
  {
    name: "Sauvignon Blanc Grape",
    category: "Fruit",
    subCategory: "Grape",
    photo: "",
  },
  {
    name: "Grenache Grape",
    category: "Fruit",
    subCategory: "Grape",
    photo: "",
  },
  {
    name: "Tempranillo Grape",
    category: "Fruit",
    subCategory: "Grape",
    photo: "",
  },
  {
    name: "Malbec Grape",
    category: "Fruit",
    subCategory: "Grape",
    photo: "",
  },
  {
    name: "Viognier Grape",
    category: "Fruit",
    subCategory: "Grape",
    photo: "",
  },
  {
    name: "Sangiovese Grape",
    category: "Fruit",
    subCategory: "Grape",
    photo: "",
  },
  {
    name: "Barbera Grape",
    category: "Fruit",
    subCategory: "Grape",
    photo: "",
  },
  {
    name: "Eureka Lemon",
    category: "Fruit",
    subCategory: "Lemon",
    photo: "",
  },
  {
    name: "Lisbon Lemon",
    category: "Fruit",
    subCategory: "Lemon",
    photo: "",
  },
  {
    name: "Meyer Lemon",
    category: "Fruit",
    subCategory: "Lemon",
    photo: "",
  },
  {
    name: "Ponderosa Lemon",
    category: "Fruit",
    subCategory: "Lemon",
    photo: "",
  },
  {
    name: "Lunario Lemon",
    category: "Fruit",
    subCategory: "Lemon",
    photo: "",
  },
  {
    name: "Variegated Pink Lemon",
    category: "Fruit",
    subCategory: "Lemon",
    photo: "",
  },
  {
    name: "Yen Ben Lemon",
    category: "Fruit",
    subCategory: "Lemon",
    photo: "",
  },
  {
    name: "Femminello St. Teresa Lemon",
    category: "Fruit",
    subCategory: "Lemon",
    photo: "",
  },
  {
    name: "Verna Lemon",
    category: "Fruit",
    subCategory: "Lemon",
    photo: "",
  },
  {
    name: "Bush Lemon",
    category: "Fruit",
    subCategory: "Lemon",
    photo: "",
  },
  {
    name: "Armenian Cucumber",
    category: "Vegetable",
    subCategory: "Cucumber",
    photo: "",
  },
  {
    name: "English Telegraph Cucumber",
    category: "Vegetable",
    subCategory: "Cucumber",
    photo: "",
  },
  {
    name: "Persian Cucumber",
    category: "Vegetable",
    subCategory: "Cucumber",
    photo: "",
  },
  {
    name: "Lemon Cucumber",
    category: "Vegetable",
    subCategory: "Cucumber",
    photo: "",
  },
  {
    name: "Japanese Cucumber",
    category: "Vegetable",
    subCategory: "Cucumber",
    photo: "",
  },
  {
    name: "Kirby Cucumber",
    category: "Vegetable",
    subCategory: "Cucumber",
    photo: "",
  },
  {
    name: "Marketmore Cucumber",
    category: "Vegetable",
    subCategory: "Cucumber",
    photo: "",
  },
  {
    name: "National Pickling Cucumber",
    category: "Vegetable",
    subCategory: "Cucumber",
    photo: "",
  },
  {
    name: "Straight Eight Cucumber",
    category: "Vegetable",
    subCategory: "Cucumber",
    photo: "",
  },
  {
    name: "Bush Crop Cucumber",
    category: "Vegetable",
    subCategory: "Cucumber",
    photo: "",
  },
  {
    name: "Parisian Pickling Cucumber",
    category: "Vegetable",
    subCategory: "Cucumber",
    photo: "",
  },
  {
    name: "Burpless Cucumber",
    category: "Vegetable",
    subCategory: "Cucumber",
    photo: "",
  },
  {
    name: "DivA Hybrid Cucumber",
    category: "Vegetable",
    subCategory: "Cucumber",
    photo: "",
  },
  {
    name: "Marketmore 76 Cucumber",
    category: "Vegetable",
    subCategory: "Cucumber",
    photo: "",
  },
  {
    name: "Sweet Success Cucumber",
    category: "Vegetable",
    subCategory: "Cucumber",
    photo: "",
  },
  {
    name: "Sumter Cucumber",
    category: "Vegetable",
    subCategory: "Cucumber",
    photo: "",
  },
  {
    name: "Sweet Slice Cucumber",
    category: "Vegetable",
    subCategory: "Cucumber",
    photo: "",
  },
  {
    name: "Tasty Green Cucumber",
    category: "Vegetable",
    subCategory: "Cucumber",
    photo: "",
  },
  {
    name: "Picklebush Cucumber",
    category: "Vegetable",
    subCategory: "Cucumber",
    photo: "",
  },
  {
    name: "Miniature White Cucumber",
    category: "Vegetable",
    subCategory: "Cucumber",
    photo: "",
  },
  {
    name: "Mexican Sour Gherkin Cucumber",
    category: "Vegetable",
    subCategory: "Cucumber",
    photo: "",
  },
  {
    name: "Passandra Cucumber",
    category: "Vegetable",
    subCategory: "Cucumber",
    photo: "",
  },
  {
    name: "Dasher II Cucumber",
    category: "Vegetable",
    subCategory: "Cucumber",
    photo: "",
  },
  {
    name: "Fanfare Cucumber",
    category: "Vegetable",
    subCategory: "Cucumber",
    photo: "",
  },
  {
    name: "Cucino Cucumber",
    category: "Vegetable",
    subCategory: "Cucumber",
    photo: "",
  },
  {
    name: "Greensleeves Cucumber",
    category: "Vegetable",
    subCategory: "Cucumber",
    photo: "",
  },
  {
    name: "Socrates Cucumber",
    category: "Vegetable",
    subCategory: "Cucumber",
    photo: "",
  },
  {
    name: "Regal Cucumber",
    category: "Vegetable",
    subCategory: "Cucumber",
    photo: "",
  },
  {
    name: "Patio Snacker Cucumber",
    category: "Vegetable",
    subCategory: "Cucumber",
    photo: "",
  },
  {
    name: "Smooth Cayenne Pineapple",
    category: "Fruit",
    subCategory: "Pineapple",
    photo: "",
  },
  {
    name: "Red Spanish Pineapple",
    category: "Fruit",
    subCategory: "Pineapple",
    photo: "",
  },
  {
    name: "Sugarloaf Pineapple",
    category: "Fruit",
    subCategory: "Pineapple",
    photo: "",
  },
  {
    name: "Hilo Pineapple",
    category: "Fruit",
    subCategory: "Pineapple",
    photo: "",
  },
  {
    name: "Pernambuco Pineapple",
    category: "Fruit",
    subCategory: "Pineapple",
    photo: "",
  },
  {
    name: "Detroit Dark Red Beet",
    category: "Vegetable",
    subCategory: "Beet",
    photo: "",
  },
  {
    name: "Golden Beet",
    category: "Vegetable",
    subCategory: "Beet",
    photo: "",
  },
  {
    name: "Chioggia Beet (Candy Stripe Beet)",
    category: "Vegetable",
    subCategory: "Beet",
    photo: "",
  },
  {
    name: "Bulls Blood Beet",
    category: "Vegetable",
    subCategory: "Beet",
    photo: "",
  },
  {
    name: "Cylindra Beet",
    category: "Vegetable",
    subCategory: "Beet",
    photo: "",
  },
  {
    name: "Burpee's Golden Beet",
    category: "Vegetable",
    subCategory: "Beet",
    photo: "",
  },
  {
    name: "Early Wonder Beet",
    category: "Vegetable",
    subCategory: "Beet",
    photo: "",
  },
  {
    name: "Merlin Beet",
    category: "Vegetable",
    subCategory: "Beet",
    photo: "",
  },
  {
    name: "Ruby Queen Beet",
    category: "Vegetable",
    subCategory: "Beet",
    photo: "",
  },
  {
    name: "Touchstone Gold Beet",
    category: "Vegetable",
    subCategory: "Beet",
    photo: "",
  },
  {
    name: "Avalanche Beet",
    category: "Vegetable",
    subCategory: "Beet",
    photo: "",
  },
  {
    name: "Badger Flame Beet",
    category: "Vegetable",
    subCategory: "Beet",
    photo: "",
  },
  {
    name: "Blankoma Beet",
    category: "Vegetable",
    subCategory: "Beet",
    photo: "",
  },
  {
    name: "Crosby Egyptian Beet",
    category: "Vegetable",
    subCategory: "Beet",
    photo: "",
  },
  {
    name: "Early Wonder Tall Top Beet",
    category: "Vegetable",
    subCategory: "Beet",
    photo: "",
  },
  {
    name: "Formanova Beet",
    category: "Vegetable",
    subCategory: "Beet",
    photo: "",
  },
  {
    name: "Lutz Green Leaf Beet",
    category: "Vegetable",
    subCategory: "Beet",
    photo: "",
  },
  {
    name: "Red Ace Beet",
    category: "Vegetable",
    subCategory: "Beet",
    photo: "",
  },
  {
    name: "Red Cloud Beet",
    category: "Vegetable",
    subCategory: "Beet",
    photo: "",
  },
  {
    name: "White Albino Beet",
    category: "Vegetable",
    subCategory: "Beet",
    photo: "",
  },
  {
    name: "Hass Avocado",
    category: "Fruit",
    subCategory: "Avocado",
    photo: "",
  },
  {
    name: "Fuerte Avocado",
    category: "Fruit",
    subCategory: "Avocado",
    photo: "",
  },
  {
    name: "Reed Avocado",
    category: "Fruit",
    subCategory: "Avocado",
    photo: "",
  },
  {
    name: "Bacon Avocado",
    category: "Fruit",
    subCategory: "Avocado",
    photo: "",
  },
  {
    name: "Zutano Avocado",
    category: "Fruit",
    subCategory: "Avocado",
    photo: "",
  },
  {
    name: "Gwen Avocado",
    category: "Fruit",
    subCategory: "Avocado",
    photo: "",
  },
  {
    name: "Pinkerton Avocado",
    category: "Fruit",
    subCategory: "Avocado",
    photo: "",
  },
  {
    name: "Lamb Hass Avocado",
    category: "Fruit",
    subCategory: "Avocado",
    photo: "",
  },
  {
    name: "Sharwil Avocado",
    category: "Fruit",
    subCategory: "Avocado",
    photo: "",
  },
  {
    name: "Brogdon Avocado",
    category: "Fruit",
    subCategory: "Avocado",
    photo: "",
  },
  {
    name: "Strawberry",
    category: "Fruit",
    subCategory: "Berry",
    photo: "",
  },
  {
    name: "Blueberry",
    category: "Fruit",
    subCategory: "Berry",
    photo: "",
  },
  {
    name: "Raspberry",
    category: "Fruit",
    subCategory: "Berry",
    photo: "",
  },
  {
    name: "Blackberry",
    category: "Fruit",
    subCategory: "Berry",
    photo: "",
  },
  {
    name: "Cranberry",
    category: "Fruit",
    subCategory: "Berry",
    photo: "",
  },
  {
    name: "Goji Berry",
    category: "Fruit",
    subCategory: "Berry",
    photo: "",
  },
  {
    name: "Acai Berry",
    category: "Fruit",
    subCategory: "Berry",
    photo: "",
  },
  {
    name: "Boysenberry",
    category: "Fruit",
    subCategory: "Berry",
    photo: "",
  },
  {
    name: "Elderberry",
    category: "Fruit",
    subCategory: "Berry",
    photo: "",
  },
  {
    name: "Mulberry",
    category: "Fruit",
    subCategory: "Berry",
    photo: "",
  },
  {
    name: "Huckleberry",
    category: "Fruit",
    subCategory: "Berry",
    photo: "",
  },
  {
    name: "Salmonberry",
    category: "Fruit",
    subCategory: "Berry",
    photo: "",
  },
  {
    name: "Marionberry",
    category: "Fruit",
    subCategory: "Berry",
    photo: "",
  },
  {
    name: "Currant",
    category: "Fruit",
    subCategory: "Berry",
    photo: "",
  },
  {
    name: "Serviceberry",
    category: "Fruit",
    subCategory: "Berry",
    photo: "",
  },
  {
    name: "Loganberry",
    category: "Fruit",
    subCategory: "Berry",
    photo: "",
  },
  {
    name: "Cloudberry",
    category: "Fruit",
    subCategory: "Berry",
    photo: "",
  },
  {
    name: "Tayberry",
    category: "Fruit",
    subCategory: "Berry",
    photo: "",
  },
  {
    name: "Juneberry",
    category: "Fruit",
    subCategory: "Berry",
    photo: "",
  },
  {
    name: "Gooseberry",
    category: "Fruit",
    subCategory: "Berry",
    photo: "",
  },
  {
    name: "Saskatoon Berry",
    category: "Fruit",
    subCategory: "Berry",
    photo: "",
  },
  {
    name: "Wineberry",
    category: "Fruit",
    subCategory: "Berry",
    photo: "",
  },
  {
    name: "Hackberry",
    category: "Fruit",
    subCategory: "Berry",
    photo: "",
  },
  {
    name: "Bilberry",
    category: "Fruit",
    subCategory: "Berry",
    photo: "",
  },
  {
    name: "Crowberry",
    category: "Fruit",
    subCategory: "Berry",
    photo: "",
  },
  {
    name: "Red Mulberry",
    category: "Fruit",
    subCategory: "Berry",
    photo: "",
  },
  {
    name: "White Mulberry",
    category: "Fruit",
    subCategory: "Berry",
    photo: "",
  },
  {
    name: "Aronia Berry",
    category: "Fruit",
    subCategory: "Berry",
    photo: "",
  },
  {
    name: "Beautyberry",
    category: "Fruit",
    subCategory: "Berry",
    photo: "",
  },
  {
    name: "Bearberry",
    category: "Fruit",
    subCategory: "Berry",
    photo: "",
  },
  {
    name: "Snowberry",
    category: "Fruit",
    subCategory: "Berry",
    photo: "",
  },
  {
    name: "Buffalo Berry",
    category: "Fruit",
    subCategory: "Berry",
    photo: "",
  },
  {
    name: "Calafate Berry",
    category: "Fruit",
    subCategory: "Berry",
    photo: "",
  },
  {
    name: "Chehalem Blackberry",
    category: "Fruit",
    subCategory: "Berry",
    photo: "",
  },
  {
    name: "Clingstone Thornless Blackberry",
    category: "Fruit",
    subCategory: "Berry",
    photo: "",
  },
  {
    name: "Cutleaf Blackberry",
    category: "Fruit",
    subCategory: "Berry",
    photo: "",
  },
  {
    name: "Garden Blackberry",
    category: "Fruit",
    subCategory: "Berry",
    photo: "",
  },
  {
    name: "Himalayan Blackberry",
    category: "Fruit",
    subCategory: "Berry",
    photo: "",
  },
  {
    name: "Natchez Blackberry",
    category: "Fruit",
    subCategory: "Berry",
    photo: "",
  },
  {
    name: "Triple Crown Blackberry",
    category: "Fruit",
    subCategory: "Berry",
    photo: "",
  },
  {
    name: "Youngberry",
    category: "Fruit",
    subCategory: "Berry",
    photo: "",
  },
  {
    name: "Boysen",
    category: "Fruit",
    subCategory: "Berry",
    photo: "",
  },
  {
    name: "Waldo",
    category: "Fruit",
    subCategory: "Berry",
    photo: "",
  },
  {
    name: "Berry plants",
    category: "Fruit",
    subCategory: "Berry",
    photo: "",
  },
  {
    name: "Hardy Kiwi",
    category: "Fruit",
    subCategory: "Berry",
    photo: "",
  },
  {
    name: "Olallieberry",
    category: "Fruit",
    subCategory: "Berry",
    photo: "",
  },
  {
    name: "Cranberry",
    category: "Fruit",
    subCategory: "Berry",
    photo: "",
  },
  {
    name: "Thimbleberry",
    category: "Fruit",
    subCategory: "Berry",
    photo: "",
  },
  {
    name: "Raisinberry",
    category: "Fruit",
    subCategory: "Berry",
    photo: "",
  },
  {
    name: "Bananaberry",
    category: "Fruit",
    subCategory: "Berry",
    photo: "",
  },
  {
    name: "Cape Gooseberry",
    category: "Fruit",
    subCategory: "Berry",
    photo: "",
  },
  {
    name: "Barberry",
    category: "Fruit",
    subCategory: "Berry",
    photo: "",
  },
  {
    name: "Buffaloberry",
    category: "Fruit",
    subCategory: "Berry",
    photo: "",
  },
  {
    name: "Crowberry",
    category: "Fruit",
    subCategory: "Berry",
    photo: "",
  },
  {
    name: "Raspberry",
    category: "Fruit",
    subCategory: "Berry",
    photo: "",
  },
  {
    name: "Salal Berry",
    category: "Fruit",
    subCategory: "Berry",
    photo: "",
  },
  {
    name: "Seaberry",
    category: "Fruit",
    subCategory: "Berry",
    photo: "",
  },
  {
    name: "Strawberry Tree",
    category: "Fruit",
    subCategory: "Berry",
    photo: "",
  },
  {
    name: "Youngberry",
    category: "Fruit",
    subCategory: "Berry",
    photo: "",
  },
  {
    name: "Partridgeberry",
    category: "Fruit",
    subCategory: "Berry",
    photo: "",
  },
  {
    name: "Debbaneh Berry",
    category: "Fruit",
    subCategory: "Berry",
    photo: "",
  },
  {
    name: "Tropical Berry",
    category: "Fruit",
    subCategory: "Berry",
    photo: "",
  },
  {
    name: "Raisinberry",
    category: "Fruit",
    subCategory: "Berry",
    photo: "",
  },
  {
    name: "Chokeberry",
    category: "Fruit",
    subCategory: "Berry",
    photo: "",
  },
  {
    name: "Boysenberry",
    category: "Fruit",
    subCategory: "Berry",
    photo: "",
  },
  {
    name: "Saskatoon Berry",
    category: "Fruit",
    subCategory: "Berry",
    photo: "",
  },
  {
    name: "Juneberry",
    category: "Fruit",
    subCategory: "Berry",
    photo: "",
  },
  {
    name: "Serviceberry",
    category: "Fruit",
    subCategory: "Berry",
    photo: "",
  },
  {
    name: "Cloud Berry",
    category: "Fruit",
    subCategory: "Berry",
    photo: "",
  },
  {
    name: "Aronia Berry",
    category: "Fruit",
    subCategory: "Berry",
    photo: "",
  },
  {
    name: "Cilantro",
    category: "Herb",
    subCategory: "Cilantro",
    photo: "",
  },
  {
    name: "Parsley",
    category: "Herb",
    subCategory: "Parsley",
    photo: "",
  },
  {
    name: "Basil",
    category: "Herb",
    subCategory: "Basil",
    photo: "",
  },
  {
    name: "Mint",
    category: "Herb",
    subCategory: "Mint",
    photo: "",
  },
  {
    name: "Thyme",
    category: "Herb",
    subCategory: "Thyme",
    photo: "",
  },
  {
    name: "Oregano",
    category: "Herb",
    subCategory: "Oregano",
    photo: "",
  },
  {
    name: "Rosemary",
    category: "Herb",
    subCategory: "Rosemary",
    photo: "",
  },
  {
    name: "Sage",
    category: "Herb",
    subCategory: "Sage",
    photo: "",
  },
  {
    name: "Chives",
    category: "Herb",
    subCategory: "Chives",
    photo: "",
  },
  {
    name: "Dill",
    category: "Herb",
    subCategory: "Dill",
    photo: "",
  },
  {
    name: "Borage",
    category: "Herb",
    subCategory: "Borage",
    photo: "",
  },
  {
    name: "Culantro",
    category: "Herb",
    subCategory: "Culantro",
    photo: "",
  },
  {
    name: "Lemongrass",
    category: "Herb",
    subCategory: "Lemongrass",
    photo: "",
  },
  {
    name: "Lavender",
    category: "Herb",
    subCategory: "Lavender",
    photo: "",
  },
  {
    name: "Fennel",
    category: "Herb",
    subCategory: "Fennel",
    photo: "",
  },
  {
    name: "Tarragon",
    category: "Herb",
    subCategory: "Tarragon",
    photo: "",
  },
  {
    name: "Marjoram",
    category: "Herb",
    subCategory: "Marjoram",
    photo: "",
  },
  {
    name: "Cress",
    category: "Herb",
    subCategory: "Cress",
    photo: "",
  },
  {
    name: "Savory",
    category: "Herb",
    subCategory: "Savory",
    photo: "",
  },
  {
    name: "Bay Leaf",
    category: "Herb",
    subCategory: "Bay Leaf",
    photo: "",
  },
  {
    name: "Watermelon",
    category: "Fruit",
    subCategory: "Melon",
    photo: "",
  },
  {
    name: "Cantaloupe",
    category: "Fruit",
    subCategory: "Melon",
    photo: "",
  },
  {
    name: "Honeydew Melon",
    category: "Fruit",
    subCategory: "Melon",
    photo: "",
  },
  {
    name: "Casaba Melon",
    category: "Fruit",
    subCategory: "Melon",
    photo: "",
  },
  {
    name: "Crenshaw Melon",
    category: "Fruit",
    subCategory: "Melon",
    photo: "",
  },
  {
    name: "Canary Melon",
    category: "Fruit",
    subCategory: "Melon",
    photo: "",
  },
  {
    name: "Santa Claus Melon",
    category: "Fruit",
    subCategory: "Melon",
    photo: "",
  },
  {
    name: "Persian Melon",
    category: "Fruit",
    subCategory: "Melon",
    photo: "",
  },
  {
    name: "Sprite Melon",
    category: "Fruit",
    subCategory: "Melon",
    photo: "",
  },
  {
    name: "Galia Melon",
    category: "Fruit",
    subCategory: "Melon",
    photo: "",
  },
  {
    name: "Piel de Sapo Melon",
    category: "Fruit",
    subCategory: "Melon",
    photo: "",
  },
  {
    name: "Golden Dewlicious Melon",
    category: "Fruit",
    subCategory: "Melon",
    photo: "",
  },
  {
    name: "Winter Melon",
    category: "Fruit",
    subCategory: "Melon",
    photo: "",
  },
  {
    name: "Hamigua Melon",
    category: "Fruit",
    subCategory: "Melon",
    photo: "",
  },
  {
    name: "Bitter Melon",
    category: "Fruit",
    subCategory: "Melon",
    photo: "",
  },
  {
    name: "Preserve Melon",
    category: "Fruit",
    subCategory: "Melon",
    photo: "",
  },
  {
    name: "Kiwano Melon",
    category: "Fruit",
    subCategory: "Melon",
    photo: "",
  },
  {
    name: "Santa Claus Melon",
    category: "Fruit",
    subCategory: "Melon",
    photo: "",
  },
  {
    name: "Sprite Melon",
    category: "Fruit",
    subCategory: "Melon",
    photo: "",
  },
  {
    name: "Galia Melon",
    category: "Fruit",
    subCategory: "Melon",
    photo: "",
  },
  {
    name: "Dragon Fruit",
    category: "Fruit",
    subCategory: "Exotic",
    photo: "",
  },
  {
    name: "Kiwano",
    category: "Fruit",
    subCategory: "Exotic",
    photo: "",
  },
  {
    name: "Star Fruit",
    category: "Fruit",
    subCategory: "Exotic",
    photo: "",
  },
  {
    name: "Durian",
    category: "Fruit",
    subCategory: "Exotic",
    photo: "",
  },
  {
    name: "Jackfruit",
    category: "Fruit",
    subCategory: "Exotic",
    photo: "",
  },
  {
    name: "Rambutan",
    category: "Fruit",
    subCategory: "Exotic",
    photo: "",
  },
  {
    name: "Mangosteen",
    category: "Fruit",
    subCategory: "Exotic",
    photo: "",
  },
  {
    name: "Passion Fruit",
    category: "Fruit",
    subCategory: "Exotic",
    photo: "",
  },
  {
    name: "Papaya",
    category: "Fruit",
    subCategory: "Exotic",
    photo: "",
  },
  {
    name: "Guava",
    category: "Fruit",
    subCategory: "Exotic",
    photo: "",
  },
  {
    name: "Lychee",
    category: "Fruit",
    subCategory: "Exotic",
    photo: "",
  },
  {
    name: "Açaí",
    category: "Fruit",
    subCategory: "Exotic",
    photo: "",
  },
  {
    name: "Pitaya",
    category: "Fruit",
    subCategory: "Exotic",
    photo: "",
  },
  {
    name: "Feijoa",
    category: "Fruit",
    subCategory: "Exotic",
    photo: "",
  },
  {
    name: "Chayote",
    category: "Vegetable",
    subCategory: "Exotic",
    photo: "",
  },
  {
    name: "Yuca",
    category: "Vegetable",
    subCategory: "Exotic",
    photo: "",
  },
  {
    name: "Jícama",
    category: "Vegetable",
    subCategory: "Exotic",
    photo: "",
  },
  {
    name: "Salsify",
    category: "Vegetable",
    subCategory: "Exotic",
    photo: "",
  },
  {
    name: "Parsnip",
    category: "Vegetable",
    subCategory: "Exotic",
    photo: "",
  },
  {
    name: "Bok Choy",
    category: "Vegetable",
    subCategory: "Exotic",
    photo: "",
  },
  {
    name: "Bean Sprouts",
    category: "Vegetable",
    subCategory: "Shoot",
    photo: "",
  },
  {
    name: "Alfalfa Sprouts",
    category: "Vegetable",
    subCategory: "Shoot",
    photo: "",
  },
  {
    name: "Mung Bean Sprouts",
    category: "Vegetable",
    subCategory: "Shoot",
    photo: "",
  },
  {
    name: "Broccoli Sprouts",
    category: "Vegetable",
    subCategory: "Shoot",
    photo: "",
  },
  {
    name: "Radish Sprouts",
    category: "Vegetable",
    subCategory: "Shoot",
    photo: "",
  },
  {
    name: "Pea Shoots",
    category: "Vegetable",
    subCategory: "Shoot",
    photo: "",
  },
  {
    name: "Sunflower Shoots",
    category: "Vegetable",
    subCategory: "Shoot",
    photo: "",
  },
  {
    name: "Wheatgrass",
    category: "Vegetable",
    subCategory: "Shoot",
    photo: "",
  },
  {
    name: "Arugula Sprouts",
    category: "Vegetable",
    subCategory: "Shoot",
    photo: "",
  },
  {
    name: "Clover Sprouts",
    category: "Vegetable",
    subCategory: "Shoot",
    photo: "",
  },
  {
    name: "Lentil Sprouts",
    category: "Vegetable",
    subCategory: "Shoot",
    photo: "",
  },
  {
    name: "Fenugreek Sprouts",
    category: "Vegetable",
    subCategory: "Shoot",
    photo: "",
  },
  {
    name: "Kale Sprouts",
    category: "Vegetable",
    subCategory: "Shoot",
    photo: "",
  },
  {
    name: "Chia Sprouts",
    category: "Vegetable",
    subCategory: "Shoot",
    photo: "",
  },
  {
    name: "Bamboo Shoots",
    category: "Vegetable",
    subCategory: "Shoot",
    photo: "",
  },
  {
    name: "Soybean Sprouts",
    category: "Vegetable",
    subCategory: "Shoot",
    photo: "",
  },
  {
    name: "Cabbage Sprouts",
    category: "Vegetable",
    subCategory: "Shoot",
    photo: "",
  },
  {
    name: "Mustard Sprouts",
    category: "Vegetable",
    subCategory: "Shoot",
    photo: "",
  },
  {
    name: "Celery Sprouts",
    category: "Vegetable",
    subCategory: "Shoot",
    photo: "",
  },
  {
    name: "Onion Sprouts",
    category: "Vegetable",
    subCategory: "Shoot",
    photo: "",
  },
  {
    name: "Potato",
    category: "Vegetable",
    subCategory: "Tubers",
    photo: "",
  },
  {
    name: "Sweet Potato",
    category: "Vegetable",
    subCategory: "Tubers",
    photo: "",
  },
  {
    name: "Yam",
    category: "Vegetable",
    subCategory: "Tubers",
    photo: "",
  },
  {
    name: "Cassava",
    category: "Vegetable",
    subCategory: "Tubers",
    photo: "",
  },
  {
    name: "Taro",
    category: "Vegetable",
    subCategory: "Tubers",
    photo: "",
  },
  {
    name: "Jicama",
    category: "Vegetable",
    subCategory: "Tubers",
    photo: "",
  },
  {
    name: "Jerusalem Artichoke",
    category: "Vegetable",
    subCategory: "Tubers",
    photo: "",
  },
  {
    name: "Rutabaga",
    category: "Vegetable",
    subCategory: "Tubers",
    photo: "",
  },
  {
    name: "Sunchokes",
    category: "Vegetable",
    subCategory: "Tubers",
    photo: "",
  },
  {
    name: "Chinese Artichoke",
    category: "Vegetable",
    subCategory: "Tubers",
    photo: "",
  },
  {
    name: "Arracacha",
    category: "Vegetable",
    subCategory: "Tubers",
    photo: "",
  },
  {
    name: "Oca",
    category: "Vegetable",
    subCategory: "Tubers",
    photo: "",
  },
  {
    name: "Crosne",
    category: "Vegetable",
    subCategory: "Tubers",
    photo: "",
  },
  {
    name: "Chayote",
    category: "Vegetable",
    subCategory: "Tubers",
    photo: "",
  },
  {
    name: "Malanga",
    category: "Vegetable",
    subCategory: "Tubers",
    photo: "",
  },
  {
    name: "Konjac",
    category: "Vegetable",
    subCategory: "Tubers",
    photo: "",
  },
  {
    name: "Tiquisque",
    category: "Vegetable",
    subCategory: "Tubers",
    photo: "",
  },
  {
    name: "Dasheen",
    category: "Vegetable",
    subCategory: "Tubers",
    photo: "",
  },
  {
    name: "Plectranthus",
    category: "Vegetable",
    subCategory: "Tubers",
    photo: "",
  },
  {
    name: "Chufa",
    category: "Vegetable",
    subCategory: "Tubers",
    photo: "",
  },
  {
    name: "Garlic",
    category: "Vegetable",
    subCategory: "Alliums",
    photo: "",
  },
  {
    name: "Onion",
    category: "Vegetable",
    subCategory: "Alliums",
    photo: "",
  },
  {
    name: "Leek",
    category: "Vegetable",
    subCategory: "Alliums",
    photo: "",
  },
  {
    name: "Scallion",
    category: "Vegetable",
    subCategory: "Alliums",
    photo: "",
  },
  {
    name: "Chives",
    category: "Vegetable",
    subCategory: "Alliums",
    photo: "",
  },
  {
    name: "Shallot",
    category: "Vegetable",
    subCategory: "Alliums",
    photo: "",
  },
  {
    name: "Spring Onion",
    category: "Vegetable",
    subCategory: "Alliums",
    photo: "",
  },
  {
    name: "Elephant Garlic",
    category: "Vegetable",
    subCategory: "Alliums",
    photo: "",
  },
  {
    name: "Pearl Onion",
    category: "Vegetable",
    subCategory: "Alliums",
    photo: "",
  },
  {
    name: "Ramps",
    category: "Vegetable",
    subCategory: "Alliums",
    photo: "",
  },
  {
    name: "Welsh Onion",
    category: "Vegetable",
    subCategory: "Alliums",
    photo: "",
  },
  {
    name: "Egyptian Walking Onion",
    category: "Vegetable",
    subCategory: "Alliums",
    photo: "",
  },
  {
    name: "Tree Onion",
    category: "Vegetable",
    subCategory: "Alliums",
    photo: "",
  },
  {
    name: "Evergreen Bunching Onion",
    category: "Vegetable",
    subCategory: "Alliums",
    photo: "",
  },
  {
    name: "Cipollini Onion",
    category: "Vegetable",
    subCategory: "Alliums",
    photo: "",
  },
  {
    name: "Red Onion",
    category: "Vegetable",
    subCategory: "Alliums",
    photo: "",
  },
  {
    name: "Yellow Onion",
    category: "Vegetable",
    subCategory: "Alliums",
    photo: "",
  },
  {
    name: "White Onion",
    category: "Vegetable",
    subCategory: "Alliums",
    photo: "",
  },
  {
    name: "Vidalia Onion",
    category: "Vegetable",
    subCategory: "Alliums",
    photo: "",
  },
  {
    name: "Boiling Onion",
    category: "Vegetable",
    subCategory: "Alliums",
    photo: "",
  },
  {
    name: "Green Pea",
    category: "Vegetable",
    subCategory: "Peas",
    photo: "",
  },
  {
    name: "Snow Pea",
    category: "Vegetable",
    subCategory: "Peas",
    photo: "",
  },
  {
    name: "Sugar Snap Pea",
    category: "Vegetable",
    subCategory: "Peas",
    photo: "",
  },
  {
    name: "Black-Eyed Pea",
    category: "Vegetable",
    subCategory: "Peas",
    photo: "",
  },
  {
    name: "Yellow Pea",
    category: "Vegetable",
    subCategory: "Peas",
    photo: "",
  },
  {
    name: "Split Pea",
    category: "Vegetable",
    subCategory: "Peas",
    photo: "",
  },
  {
    name: "Chickpea",
    category: "Vegetable",
    subCategory: "Peas",
    photo: "",
  },
  {
    name: "Black Chickpea",
    category: "Vegetable",
    subCategory: "Peas",
    photo: "",
  },
  {
    name: "Green Chickpea",
    category: "Vegetable",
    subCategory: "Peas",
    photo: "",
  },
  {
    name: "Pigeon Pea",
    category: "Vegetable",
    subCategory: "Peas",
    photo: "",
  },
  {
    name: "Field Pea",
    category: "Vegetable",
    subCategory: "Peas",
    photo: "",
  },
  {
    name: "Crowder Pea",
    category: "Vegetable",
    subCategory: "Peas",
    photo: "",
  },
  {
    name: "Purple Hull Pea",
    category: "Vegetable",
    subCategory: "Peas",
    photo: "",
  },
  {
    name: "Cowpea",
    category: "Vegetable",
    subCategory: "Peas",
    photo: "",
  },
  {
    name: "Garden Pea",
    category: "Vegetable",
    subCategory: "Peas",
    photo: "",
  },
  {
    name: "Edible-Podded Pea",
    category: "Vegetable",
    subCategory: "Peas",
    photo: "",
  },
  {
    name: "Alderman Pea",
    category: "Vegetable",
    subCategory: "Peas",
    photo: "",
  },
  {
    name: "Tom Thumb Pea",
    category: "Vegetable",
    subCategory: "Peas",
    photo: "",
  },
  {
    name: "Butter Pea",
    category: "Vegetable",
    subCategory: "Peas",
    photo: "",
  },
  {
    name: "Snap Pea",
    category: "Vegetable",
    subCategory: "Peas",
    photo: "",
  },
  {
    name: "Green Bean",
    category: "Vegetable",
    subCategory: "Beans",
    photo: "",
  },
  {
    name: "Kidney Bean",
    category: "Vegetable",
    subCategory: "Beans",
    photo: "",
  },
  {
    name: "Black Bean",
    category: "Vegetable",
    subCategory: "Beans",
    photo: "",
  },
  {
    name: "Pinto Bean",
    category: "Vegetable",
    subCategory: "Beans",
    photo: "",
  },
  {
    name: "Navy Bean",
    category: "Vegetable",
    subCategory: "Beans",
    photo: "",
  },
  {
    name: "Lima Bean",
    category: "Vegetable",
    subCategory: "Beans",
    photo: "",
  },
  {
    name: "Garbanzo Bean",
    category: "Vegetable",
    subCategory: "Beans",
    photo: "",
  },
  {
    name: "Fava Bean",
    category: "Vegetable",
    subCategory: "Beans",
    photo: "",
  },
  {
    name: "Cannellini Bean",
    category: "Vegetable",
    subCategory: "Beans",
    photo: "",
  },
  {
    name: "Great Northern Bean",
    category: "Vegetable",
    subCategory: "Beans",
    photo: "",
  },
  {
    name: "Black-Eyed Pea",
    category: "Vegetable",
    subCategory: "Beans",
    photo: "",
  },
  {
    name: "Adzuki Bean",
    category: "Vegetable",
    subCategory: "Beans",
    photo: "",
  },
  {
    name: "Red Bean",
    category: "Vegetable",
    subCategory: "Beans",
    photo: "",
  },
  {
    name: "Cranberry Bean",
    category: "Vegetable",
    subCategory: "Beans",
    photo: "",
  },
  {
    name: "Mung Bean",
    category: "Vegetable",
    subCategory: "Beans",
    photo: "",
  },
  {
    name: "Lentil",
    category: "Vegetable",
    subCategory: "Beans",
    photo: "",
  },
  {
    name: "Chickpea",
    category: "Vegetable",
    subCategory: "Beans",
    photo: "",
  },
  {
    name: "Black-Eyed Pea",
    category: "Vegetable",
    subCategory: "Beans",
    photo: "",
  },
  {
    name: "Split Pea",
    category: "Vegetable",
    subCategory: "Beans",
    photo: "",
  },
  {
    name: "Lima Bean",
    category: "Vegetable",
    subCategory: "Beans",
    photo: "",
  },
  {
    name: "Butternut Squash",
    category: "Vegetable",
    subCategory: "Squash",
    photo: "",
  },
  {
    name: "Acorn Squash",
    category: "Vegetable",
    subCategory: "Squash",
    photo: "",
  },
  {
    name: "Spaghetti Squash",
    category: "Vegetable",
    subCategory: "Squash",
    photo: "",
  },
  {
    name: "Yellow Squash",
    category: "Vegetable",
    subCategory: "Squash",
    photo: "",
  },
  {
    name: "Delicata Squash",
    category: "Vegetable",
    subCategory: "Squash",
    photo: "",
  },
  {
    name: "Kabocha Squash",
    category: "Vegetable",
    subCategory: "Squash",
    photo: "",
  },
  {
    name: "Hubbard Squash",
    category: "Vegetable",
    subCategory: "Squash",
    photo: "",
  },
  {
    name: "Buttercup Squash",
    category: "Vegetable",
    subCategory: "Squash",
    photo: "",
  },
  {
    name: "Carnival Squash",
    category: "Vegetable",
    subCategory: "Squash",
    photo: "",
  },
  {
    name: "Pattypan Squash",
    category: "Vegetable",
    subCategory: "Squash",
    photo: "",
  },
  {
    name: "Crookneck Squash",
    category: "Vegetable",
    subCategory: "Squash",
    photo: "",
  },
  {
    name: "Straightneck Squash",
    category: "Vegetable",
    subCategory: "Squash",
    photo: "",
  },
  {
    name: "Sweet Dumpling Squash",
    category: "Vegetable",
    subCategory: "Squash",
    photo: "",
  },
  {
    name: "Golden Nugget Squash",
    category: "Vegetable",
    subCategory: "Squash",
    photo: "",
  },
  {
    name: "Hubbard Squash",
    category: "Vegetable",
    subCategory: "Squash",
    photo: "",
  },
  {
    name: "Tromboncino Squash",
    category: "Vegetable",
    subCategory: "Squash",
    photo: "",
  },
  {
    name: "Tatume Squash",
    category: "Vegetable",
    subCategory: "Squash",
    photo: "",
  },
  {
    name: "Calabaza Squash",
    category: "Vegetable",
    subCategory: "Squash",
    photo: "",
  },
  {
    name: "Banana Squash",
    category: "Vegetable",
    subCategory: "Squash",
    photo: "",
  },
  {
    name: "Dill Pickle",
    category: "Vegetable",
    subCategory: "Pickles",
    photo: "",
  },
  {
    name: "Sweet Pickle",
    category: "Vegetable",
    subCategory: "Pickles",
    photo: "",
  },
  {
    name: "Bread and Butter Pickle",
    category: "Vegetable",
    subCategory: "Pickles",
    photo: "",
  },
];

const formattedProducts = products.map((product) => ({
  value: product.name,
  label: product.name,
  cat: product.subCategory,
  photo: product.photo,
  // shelfLife: product.shelfLife,
  category: product.category,
  // price: product.suggestPrice,
  // units: product.suggestedUnits,
}));

const useProducts = () => {
  const getAll = () => formattedProducts;

  const getByValue = (value: string) => {
    return formattedProducts.find((item) => item.value === value);
  };

  return {
    getAll,
    getByValue,
  };
};

export default useProducts;
