const defaultProducts = [
  {
    title: "Beefsteak Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/beefsteak-tomato.webp",
  },
  {
    title: "Red Delicious Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/red-delicious-apple.webp",
  },
  {
    title: "Strawberries",
    category: "RedFruitsBerry",
    subCategory: "Berry",
    photo: "/images/product-images/strawberry.webp",
  },
  {
    title: "Chicken Eggs",
    category: "PoultryChickenEgg",
    subCategory: "egg",
    photo: "/images/product-images/egg.webp",
  },
  {
    title: "Duck Eggs",
    category: "PoultryDuckEgg",
    subCategory: "egg",
    photo: "/images/product-images/egg.webp",
  },
  {
    title: "Turkey Eggs",
    category: "PoultryTurkeyEgg",
    subCategory: "egg",
    photo: "/images/product-images/egg.webp",
  },
  {
    title: "Basil",
    category: "herbs and spices",
    subCategory: "green",
    photo: "/images/product-images/basil.webp",
  },
  {
    title: "Blood Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/blood-orange.webp",
  },
  {
    title: "Baby Spinach",
    category: "Vegetables",
    subCategory: "Spinach",
    photo: "/images/product-images/baby-spinach.webp",
  },
  {
    title: "Elk",
    category: "Meats",
    subCategory: "",
    photo: "/images/product-images/Elk.webp",
  },
  {
    title: "Cherry Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/cherry-tomato.webp",
  },
  {
    title: "Heirloom Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/hierloom-tomato.webp",
  },
  {
    title: "Roma Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/roma-tomato.webp",
  },
  {
    title: "Grape Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/grape-tomato.webp",
  },
  {
    title: "San Marzano Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    title: "Brandywine Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    title: "Green Zebra Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    title: "Cherokee Purple Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    title: "Yellow Pear Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    title: "Black Krim Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    title: "Amish Paste Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    title: "Celebrity Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    title: "Early Girl Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    title: "Big Boy Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    title: "Sun Gold Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    title: "Sweet Million Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    title: "Mortgage Lifter Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    title: "Pineapple Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    title: "Supersweet 100 Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    title: "Black Cherry Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    title: "Campari Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    title: "Kumato Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    title: "Principe Borghese Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    title: "Rutgers Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    title: "Paul Robeson Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    title: "Arkansas Traveler Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    title: "Persimmon Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    title: "Costoluto Genovese Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    title: "Striped German Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    title: "Golden Jubilee Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    title: "Green Giant Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    title: "Orange Wellington Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    title: "Pink Brandywine Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    title: "Red Currant Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    title: "Snow White Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    title: "Yellow Brandywine Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    title: "Black Pineapple Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    title: "Blondkopfchen Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    title: "Caspian Pink Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    title: "German Johnson Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    title: "Hillbilly Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    title: "Indigo Rose Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    title: "Japanese Black Trifele Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    title: "Kellogg's Breakfast Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    title: "Marianna's Peace Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    title: "Old German Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    title: "Purple Calabash Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    title: "Rose de Berne Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    title: "Tigerella Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    title: "Valencia Tomatoes",
    category: "Vegetables",
    subCategory: "tomato",
    photo: "/images/product-images/tomato.webp",
  },
  {
    title: "Granny Smith Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/granny-smith.webp",
  },
  {
    title: "Fuji Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/fuji-apple.webp",
  },
  {
    title: "Gala Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/gala-apple.webp",
  },
  {
    title: "Honeycrisp Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/honey-crisp-apple.webp",
  },
  {
    title: "Golden Delicious Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/golden-delicious-apple.webp",
  },
  {
    title: "Pink Lady Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    title: "McIntosh Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    title: "Braeburn Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    title: "Jonagold Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    title: "Cortland Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    title: "Empire Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    title: "Arkansas Black Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    title: "Rome Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    title: "Ambrosia Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    title: "Jazz Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    title: "Cameo Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    title: "Opal Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    title: "Winesap Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    title: "Mutsu Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    title: "York Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    title: "Pink Pearl Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    title: "Liberty Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    title: "Ginger Gold Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    title: "Paula Red Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    title: "Northern Spy Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    title: "Gravenstein Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    title: "Jonathan Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    title: "SunCrisp Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    title: "Crimson Crisp Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    title: "EverCrisp Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    title: "SnowSweet Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    title: "Snowdrift Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    title: "SweeTango Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    title: "Wine Crisp Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    title: "Ruby Frost Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    title: "Autumn Glory Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    title: "Cosmic Crisp Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    title: "Smitten Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    title: "Kiku Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    title: "Envy Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    title: "Snapdragon Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    title: "Pacific Rose Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    title: "Kanzi Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    title: "Ambri Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    title: "SweeTango Tango Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    title: "SweeTango Zester Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    title: "Sweetie Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    title: "Sweetie Pie Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    title: "Sweetie Treat Apples",
    category: "Fruits",
    subCategory: "apple",
    photo: "/images/product-images/apple.webp",
  },
  {
    title: "Anjou Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/anjou-pear.webp",
  },
  {
    title: "Bartlett Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/bartlett-pear.webp",
  },
  {
    title: "Bosc Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/bosc-pear.webp",
  },
  {
    title: "Comice Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/comice-pear.webp",
  },
  {
    title: "Forelle Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/forelle-pear.webp",
  },
  {
    title: "Seckel Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    title: "Concorde Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    title: "Starkrimson Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    title: "Asian Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    title: "Forelle Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    title: "Red Anjou Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    title: "Green Anjou Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    title: "Concorde Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    title: "Starkrimson Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    title: "Comice Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    title: "Red Bartlett Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    title: "Brown Bartlett Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    title: "Green Bartlett Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    title: "Red Sensation Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    title: "Hosui Asian Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    title: "Shinseiki Asian Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    title: "20th Century Asian Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    title: "Ya Li Asian Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    title: "Harrow Sweet Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    title: "Magness Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    title: "Moonglow Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    title: "Blake's Pride Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    title: "Harrow Delight Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    title: "Summercrisp Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    title: "Harrow Crisp Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    title: "Orcas Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    title: "Rescue Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    title: "Moonglow Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    title: "D'Anjou Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    title: "Red D'Anjou Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    title: "Green D'Anjou Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    title: "Max Red Bartlett Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    title: "Maxie Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    title: "Pineapple Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    title: "Warren Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    title: "Warren Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    title: "Ayers Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    title: "Le Conte Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    title: "Kieffer Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    title: "Blake's Pride Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    title: "Luscious Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    title: "Orca Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    title: "Olympic Pears",
    category: "Fruits",
    subCategory: "pear",
    photo: "/images/product-images/pear.webp",
  },
  {
    title: "Navel Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/navel-orange.webp",
  },
  {
    title: "Valencia Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/valencia_orange.webp",
  },
  {
    title: "Cara Cara Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/orange.webp",
  },
  {
    title: "Seville Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/orange.webp",
  },
  {
    title: "Mandarin Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/mandarin-orange.webp",
  },
  {
    title: "Satsuma Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/orange.webp",
  },
  {
    title: "Clementine Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/orange.webp",
  },
  {
    title: "Tangerine Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/orange.webp",
  },
  {
    title: "Moro Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/orange.webp",
  },
  {
    title: "Ambersweet Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/orange.webp",
  },
  {
    title: "Temple Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/orange.webp",
  },
  {
    title: "Sour Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/orange.webp",
  },
  {
    title: "Clementine Mandarin Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/orange.webp",
  },
  {
    title: "Dancy Tangerine Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/orange.webp",
  },
  {
    title: "Nova Tangerine Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/orange.webp",
  },
  {
    title: "Sunburst Tangerine Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/orange.webp",
  },
  {
    title: "Fairchild Tangerine Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/orange.webp",
  },
  {
    title: "Robinson Tangerine Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/orange.webp",
  },
  {
    title: "Orlando Tangelo Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/orange.webp",
  },
  {
    title: "Minneola Tangelo Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/orange.webp",
  },
  {
    title: "Ugli Fruits",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/orange.webp",
  },
  {
    title: "Tangor Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/orange.webp",
  },
  {
    title: "Lemonade Lemon Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/orange.webp",
  },
  {
    title: "Sour Lemon Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/orange.webp",
  },
  {
    title: "Tangelo Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/orange.webp",
  },
  {
    title: "Seminole Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/orange.webp",
  },
  {
    title: "Pineapple Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/orange.webp",
  },
  {
    title: "Bitter Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/orange.webp",
  },
  {
    title: "Trifoliate Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/orange.webp",
  },
  {
    title: "Cleopatra Mandarin Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/orange.webp",
  },
  {
    title: "Kumquat Mandarin Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/orange.webp",
  },
  {
    title: "Willowleaf Mandarin Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/orange.webp",
  },
  {
    title: "Kinnow Mandarin Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/orange.webp",
  },
  {
    title: "Sunki Mandarin Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/orange.webp",
  },
  {
    title: "Ponkan Mandarin Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/orange.webp",
  },
  {
    title: "Dekopon Mandarin Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/orange.webp",
  },
  {
    title: "Yuzu Mandarin Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/orange.webp",
  },
  {
    title: "Khasi Mandarin Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/orange.webp",
  },
  {
    title: "Clementine Hybrid Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/orange.webp",
  },
  {
    title: "Satsuma Hybrid Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/orange.webp",
  },
  {
    title: "Tangor Hybrid Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/orange.webp",
  },
  {
    title: "Tangelo Hybrid Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/orange.webp",
  },
  {
    title: "Clementine Hybrid Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/orange.webp",
  },
  {
    title: "Nova Tangelo Hybrid Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/orange.webp",
  },
  {
    title: "Ortanique Hybrid Oranges",
    category: "Fruits",
    subCategory: "orange",
    photo: "/images/product-images/orange.webp",
  },
  {
    title: "Nantes Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/nantes-carrot.webp",
  },
  {
    title: "Danvers Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/danvers-carrot.webp",
  },
  {
    title: "Imperator Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/imperator-carrot.webp",
  },
  {
    title: "Chantenay Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/carrot.webp",
  },
  {
    title: "Paris Market Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/carrot.webp",
  },
  {
    title: "Babette Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/carrot.webp",
  },
  {
    title: "Little Finger Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/carrot.webp",
  },
  {
    title: "Scarlet Nantes Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/carrot.webp",
  },
  {
    title: "Kuroda Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/carrot.webp",
  },
  {
    title: "Atomic Red Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/carrot.webp",
  },
  {
    title: "Cosmic Purple Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/carrot.webp",
  },
  {
    title: "Solar Yellow Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/carrot.webp",
  },
  {
    title: "Lunar White Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/carrot.webp",
  },
  {
    title: "Bolero Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/carrot.webp",
  },
  {
    title: "Thumbelina Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/carrot.webp",
  },
  {
    title: "Dragon Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/carrot.webp",
  },
  {
    title: "Purple Haze Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/carrot.webp",
  },
  {
    title: "Atomic Red Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/carrot.webp",
  },
  {
    title: "Cosmic Purple Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/carrot.webp",
  },
  {
    title: "Solar Yellow Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/carrot.webp",
  },
  {
    title: "Lunar White Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/carrot.webp",
  },
  {
    title: "Bolero Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/carrot.webp",
  },
  {
    title: "Thumbelina Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/carrot.webp",
  },
  {
    title: "Dragon Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/carrot.webp",
  },
  {
    title: "Purple Haze Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/carrot.webp",
  },
  {
    title: "Yellowstone Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/carrot.webp",
  },
  {
    title: "Red Samurai Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/carrot.webp",
  },
  {
    title: "Sweet Treat Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/carrot.webp",
  },
  {
    title: "Sugarsnax Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/carrot.webp",
  },
  {
    title: "Kaleidoscope Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/carrot.webp",
  },
  {
    title: "Purple Elite Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/carrot.webp",
  },
  {
    title: "Merida Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/carrot.webp",
  },
  {
    title: "Sugarsnax Hybrid Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/carrot.webp",
  },
  {
    title: "Babette Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/carrot.webp",
  },
  {
    title: "Kinko Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/carrot.webp",
  },
  {
    title: "Purple 68 Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/purple-68-carrot.webp",
  },
  {
    title: "Amsterdam Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/carrot.webp",
  },
  {
    title: "Sweetness III Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/sweetness-III-carrot.webp",
  },
  {
    title: "Sugarsnax Hybrid Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/carrot.webp",
  },
  {
    title: "Hercules Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/carrot.webp",
  },
  {
    title: "Kaleidoscope Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/carrot.webp",
  },
  {
    title: "Purple Elite Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/carrot.webp",
  },
  {
    title: "Merida Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/carrot.webp",
  },
  {
    title: "Babette Carrots",
    category: "Vegetables",
    subCategory: "carrot",
    photo: "/images/product-images/carrot.webp",
  },
  {
    title: "Bloomsdale Spinach",
    category: "Vegetables",
    subCategory: "Spinach",
    photo: "/images/product-images/bloomsdale-spinach.webp",
  },
  {
    title: "Savoy Spinach",
    category: "Vegetables",
    subCategory: "Spinach",
    photo: "/images/product-images/spinach.webp",
  },
  {
    title: "Malabar Spinach",
    category: "Vegetables",
    subCategory: "Spinach",
    photo: "/images/product-images/malabar-spinach.webp",
  },
  {
    title: "Red Kitten Spinach",
    category: "Vegetables",
    subCategory: "Spinach",
    photo: "/images/product-images/spinach.webp",
  },
  {
    title: "Tyee Spinach",
    category: "Vegetables",
    subCategory: "Spinach",
    photo: "/images/product-images/spinach.webp",
  },
  {
    title: "Space Spinach",
    category: "Vegetables",
    subCategory: "Spinach",
    photo: "/images/product-images/spinach.webp",
  },
  {
    title: "Giant Winter Spinach",
    category: "Vegetables",
    subCategory: "Spinach",
    photo: "/images/product-images/spinach.webp",
  },
  {
    title: "Matador Spinach",
    category: "Vegetables",
    subCategory: "Spinach",
    photo: "/images/product-images/spinach.webp",
  },
  {
    title: "Corvair Spinach",
    category: "Vegetables",
    subCategory: "Spinach",
    photo: "/images/product-images/spinach.webp",
  },
  {
    title: "Regiment Spinach",
    category: "Vegetables",
    subCategory: "Spinach",
    photo: "/images/product-images/spinach.webp",
  },
  {
    title: "Space Spinach",
    category: "Vegetables",
    subCategory: "Spinach",
    photo: "/images/product-images/spinach.webp",
  },
  {
    title: "Reflect Spinach",
    category: "Vegetables",
    subCategory: "Spinach",
    photo: "/images/product-images/spinach.webp",
  },
  {
    title: "Avenger Spinach",
    category: "Vegetables",
    subCategory: "Spinach",
    photo: "/images/product-images/spinach.webp",
  },
  {
    title: "Coronet Spinach",
    category: "Vegetables",
    subCategory: "Spinach",
    photo: "/images/product-images/spinach.webp",
  },
  {
    title: "Catalyst Spinach",
    category: "Vegetables",
    subCategory: "Spinach",
    photo: "/images/product-images/spinach.webp",
  },
  {
    title: "Giant Nobel Spinach",
    category: "Vegetables",
    subCategory: "Spinach",
    photo: "/images/product-images/spinach.webp",
  },
  {
    title: "Red Cardinal Spinach",
    category: "Vegetables",
    subCategory: "Spinach",
    photo: "/images/product-images/spinach.webp",
  },
  {
    title: "Vienna Spinach",
    category: "Vegetables",
    subCategory: "Spinach",
    photo: "/images/product-images/spinach.webp",
  },
  {
    title: "Nobel Giant Spinach",
    category: "Vegetables",
    subCategory: "Spinach",
    photo: "/images/product-images/spinach.webp",
  },
  {
    title: "Calabrese Broccoli",
    category: "Vegetables",
    subCategory: "Broccoli",
    photo: "/images/product-images/calabrese-broccoli.webp",
  },
  {
    title: "Sprouting Broccoli",
    category: "Vegetables",
    subCategory: "Broccoli",
    photo: "/images/product-images/broccoli.webp",
  },
  {
    title: "Romanesco Broccoli",
    category: "Vegetables",
    subCategory: "Broccoli",
    photo: "/images/product-images/broccoli.webp",
  },
  {
    title: "Purple Sprouting Broccoli",
    category: "Vegetables",
    subCategory: "Broccoli",
    photo: "/images/product-images/broccoli.webp",
  },
  {
    title: "Broccolini",
    category: "Vegetables",
    subCategory: "Broccoli",
    photo: "/images/product-images/broccoli.webp",
  },
  {
    title: "Broccoflower",
    category: "Vegetables",
    subCategory: "Broccoli",
    photo: "/images/product-images/broccoli.webp",
  },
  {
    title: "Baby Broccoli",
    category: "Vegetables",
    subCategory: "Broccoli",
    photo: "/images/product-images/broccoli.webp",
  },
  {
    title: "Purple Broccoli",
    category: "Vegetables",
    subCategory: "Broccoli",
    photo: "/images/product-images/broccoli.webp",
  },
  {
    title: "White Sprouting Broccoli",
    category: "Vegetables",
    subCategory: "Broccoli",
    photo: "/images/product-images/broccoli.webp",
  },
  {
    title: "Belstar Broccoli",
    category: "Vegetables",
    subCategory: "Broccoli",
    photo: "/images/product-images/broccoli.webp",
  },
  {
    title: "Green Magic Broccoli",
    category: "Vegetables",
    subCategory: "Broccoli",
    photo: "/images/product-images/broccoli.webp",
  },
  {
    title: "Imperial Broccoli",
    category: "Vegetables",
    subCategory: "Broccoli",
    photo: "/images/product-images/broccoli.webp",
  },
  {
    title: "Paragon Broccoli",
    category: "Vegetables",
    subCategory: "Broccoli",
    photo: "/images/product-images/broccoli.webp",
  },
  {
    title: "Arcadia Broccoli",
    category: "Vegetables",
    subCategory: "Broccoli",
    photo: "/images/product-images/broccoli.webp",
  },
  {
    title: "Green Goliath Broccoli",
    category: "Vegetables",
    subCategory: "Broccoli",
    photo: "/images/product-images/broccoli.webp",
  },
  {
    title: "Marathon Broccoli",
    category: "Vegetables",
    subCategory: "Broccoli",
    photo: "/images/product-images/broccoli.webp",
  },
  {
    title: "Packman Broccoli",
    category: "Vegetables",
    subCategory: "Broccoli",
    photo: "/images/product-images/broccoli.webp",
  },
  {
    title: "Belstar Broccoli",
    category: "Vegetables",
    subCategory: "Broccoli",
    photo: "/images/product-images/broccoli.webp",
  },
  {
    title: "Green Magic Broccoli",
    category: "Vegetables",
    subCategory: "Broccoli",
    photo: "/images/product-images/broccoli.webp",
  },
  {
    title: "Imperial Broccoli",
    category: "Vegetables",
    subCategory: "Broccoli",
    photo: "/images/product-images/broccoli.webp",
  },
  {
    title: "Concord Grapes",
    category: "Fruits",
    subCategory: "Grape",
    photo: "/images/product-images/concord-grape.webp",
  },
  {
    title: "Thompson Seedless Grapes",
    category: "Fruits",
    subCategory: "Grape",
    photo: "/images/product-images/thompson-seedless-grape.webp",
  },
  {
    title: "Green Grapes",
    category: "Fruits",
    subCategory: "Grape",
    photo: "/images/product-images/thompson-seedless-grape.webp",
  },
  {
    title: "Red Globe Grapes",
    category: "Fruits",
    subCategory: "Grape",
    photo: "/images/product-images/red-globe-grape.webp",
  },
  {
    title: "Red Grapes",
    category: "Fruits",
    subCategory: "Grape",
    photo: "/images/product-images/red-globe-grape.webp",
  },
  {
    title: "Crimson Seedless Grapes",
    category: "Fruits",
    subCategory: "Grape",
    photo: "/images/product-images/crimson-seedless-grape.webp",
  },
  {
    title: "Chardonnay Grapes",
    category: "Fruits",
    subCategory: "Grape",
    photo: "/images/product-images/crimson-seedless-grape.webp",
  },
  {
    title: "Cabernet Sauvignon Grapes",
    category: "Fruits",
    subCategory: "Grape",
    photo: "/images/product-images/crimson-seedless-grape.webp",
  },
  {
    title: "Pinot Noir Grapes",
    category: "Fruits",
    subCategory: "Grape",
    photo: "/images/product-images/crimson-seedless-grape.webp",
  },
  {
    title: "Muscat Grapes",
    category: "Fruits",
    subCategory: "Grape",
    photo: "/images/product-images/crimson-seedless-grape.webp",
  },
  {
    title: "Merlot Grapes",
    category: "Fruits",
    subCategory: "Grape",
    photo: "/images/product-images/crimson-seedless-grape.webp",
  },
  {
    title: "Zinfandel Grapes",
    category: "Fruits",
    subCategory: "Grape",
    photo: "/images/product-images/crimson-seedless-grape.webp",
  },
  {
    title: "Cabernet Franc Grapes",
    category: "Fruits",
    subCategory: "Grape",
    photo: "/images/product-images/crimson-seedless-grape.webp",
  },
  {
    title: "Eureka Lemons",
    category: "Fruits",
    subCategory: "lemon",
    photo: "/images/product-images/lemon.webp",
  },
  {
    title: "Lisbon Lemons",
    category: "Fruits",
    subCategory: "lemon",
    photo: "/images/product-images/lemon.webp",
  },
  {
    title: "Meyer Lemons",
    category: "Fruits",
    subCategory: "lemon",
    photo: "/images/product-images/lemon.webp",
  },
  {
    title: "Ponderosa Lemons",
    category: "Fruits",
    subCategory: "lemon",
    photo: "/images/product-images/lemon.webp",
  },
  {
    title: "Lunario Lemon",
    category: "Fruits",
    subCategory: "lemon",
    photo: "/images/product-images/lemon.webp",
  },
  {
    title: "Variegated Pink Lemon",
    category: "Fruits",
    subCategory: "lemon",
    photo: "/images/product-images/lemon.webp",
  },
  {
    title: "Yen Ben Lemon",
    category: "Fruits",
    subCategory: "lemon",
    photo: "/images/product-images/lemon.webp",
  },
  {
    title: "Femminello St. Teresa Lemon",
    category: "Fruits",
    subCategory: "lemon",
    photo: "/images/product-images/lemon.webp",
  },
  {
    title: "Verna Lemon",
    category: "Fruits",
    subCategory: "lemon",
    photo: "/images/product-images/lemon.webp",
  },
  {
    title: "Bush Lemon",
    category: "Fruits",
    subCategory: "lemon",
    photo: "/images/product-images/lemon.webp",
  },
  {
    title: "Armenian Cucumbers",
    category: "Vegetables",
    subCategory: "cucumber",
    photo: "/images/product-images/armeniancucumber.webp",
  },
  {
    title: "English Telegraph Cucumbers",
    category: "Vegetables",
    subCategory: "cucumber",
    photo: "/images/product-images/english-telegraph-cucumber.webp",
  },
  {
    title: "Persian Cucumbers",
    category: "Vegetables",
    subCategory: "cucumber",
    photo: "/images/product-images/persian-cucumber.webp",
  },
  {
    title: "Lemon Cucumbers",
    category: "Vegetables",
    subCategory: "cucumber",
    photo: "/images/product-images/cucumber.webp",
  },
  {
    title: "Japanese Cucumbers",
    category: "Vegetables",
    subCategory: "cucumber",
    photo: "/images/product-images/cucumber.webp",
  },
  {
    title: "Kirby Cucumbers",
    category: "Vegetables",
    subCategory: "cucumber",
    photo: "/images/product-images/cucumber.webp",
  },
  {
    title: "Marketmore Cucumbers",
    category: "Vegetables",
    subCategory: "cucumber",
    photo: "/images/product-images/cucumber.webp",
  },
  {
    title: "National Pickling Cucumbers",
    category: "Vegetables",
    subCategory: "cucumber",
    photo: "/images/product-images/cucumber.webp",
  },
  {
    title: "Straight Eight Cucumbers",
    category: "Vegetables",
    subCategory: "cucumber",
    photo: "/images/product-images/cucumber.webp",
  },
  {
    title: "Bush Crop Cucumbers",
    category: "Vegetables",
    subCategory: "cucumber",
    photo: "/images/product-images/cucumber.webp",
  },
  {
    title: "Parisian Pickling Cucumbers",
    category: "Vegetables",
    subCategory: "cucumber",
    photo: "/images/product-images/cucumber.webp",
  },
  {
    title: "Burpless Cucumbers",
    category: "Vegetables",
    subCategory: "cucumber",
    photo: "/images/product-images/cucumber.webp",
  },
  {
    title: "DivA Hybrid Cucumbers",
    category: "Vegetables",
    subCategory: "cucumber",
    photo: "/images/product-images/cucumber.webp",
  },
  {
    title: "Marketmore 76 Cucumbers",
    category: "Vegetables",
    subCategory: "cucumber",
    photo: "/images/product-images/cucumber.webp",
  },
  {
    title: "Sweet Success Cucumbers",
    category: "Vegetables",
    subCategory: "cucumber",
    photo: "/images/product-images/cucumber.webp",
  },
  {
    title: "Sumter Cucumbers",
    category: "Vegetables",
    subCategory: "cucumber",
    photo: "/images/product-images/cucumber.webp",
  },
  {
    title: "Sweet Slice Cucumbers",
    category: "Vegetables",
    subCategory: "cucumber",
    photo: "/images/product-images/cucumber.webp",
  },
  {
    title: "Tasty Green Cucumbers",
    category: "Vegetables",
    subCategory: "cucumber",
    photo: "/images/product-images/cucumber.webp",
  },
  {
    title: "Picklebush Cucumbers",
    category: "Vegetables",
    subCategory: "cucumber",
    photo: "/images/product-images/cucumber.webp",
  },
  {
    title: "Miniature White Cucumbers",
    category: "Vegetables",
    subCategory: "cucumber",
    photo: "/images/product-images/cucumber.webp",
  },
  {
    title: "Mexican Sour Gherkin Cucumbers",
    category: "Vegetables",
    subCategory: "cucumber",
    photo: "/images/product-images/cucumber.webp",
  },
  {
    title: "Passandra Cucumbers",
    category: "Vegetables",
    subCategory: "cucumber",
    photo: "/images/product-images/cucumber.webp",
  },
  {
    title: "Dasher II Cucumbers",
    category: "Vegetables",
    subCategory: "cucumber",
    photo: "/images/product-images/cucumber.webp",
  },
  {
    title: "Fanfare Cucumbers",
    category: "Vegetables",
    subCategory: "cucumber",
    photo: "/images/product-images/cucumber.webp",
  },
  {
    title: "Cucino Cucumbers",
    category: "Vegetables",
    subCategory: "cucumber",
    photo: "/images/product-images/cucumber.webp",
  },
  {
    title: "Greensleeves Cucumbers",
    category: "Vegetables",
    subCategory: "cucumber",
    photo: "/images/product-images/cucumber.webp",
  },
  {
    title: "Socrates Cucumbers",
    category: "Vegetables",
    subCategory: "cucumber",
    photo: "/images/product-images/cucumber.webp",
  },
  {
    title: "Regal Cucumbers",
    category: "Vegetables",
    subCategory: "cucumber",
    photo: "/images/product-images/cucumber.webp",
  },
  {
    title: "Patio Snacker Cucumbers",
    category: "Vegetables",
    subCategory: "cucumber",
    photo: "/images/product-images/cucumber.webp",
  },
  {
    title: "PineApples",
    category: "Fruits",
    subCategory: "pineapple",
    photo: "/images/product-images/pineapple.webp",
  },
  {
    title: "Smooth Cayenne PineApples",
    category: "Fruits",
    subCategory: "pineapple",
    photo: "/images/product-images/pineapple.webp",
  },
  {
    title: "Red Spanish PineApples",
    category: "Fruits",
    subCategory: "pineapple",
    photo: "/images/product-images/pineapple.webp",
  },
  {
    title: "Sugarloaf PineApples",
    category: "Fruits",
    subCategory: "pineapple",
    photo: "/images/product-images/pineapple.webp",
  },
  {
    title: "Hilo PineApples",
    category: "Fruits",
    subCategory: "pineapple",
    photo: "/images/product-images/pineapple.webp",
  },
  {
    title: "Pernambuco PineApples",
    category: "Fruits",
    subCategory: "pineapple",
    photo: "/images/product-images/pineapple.webp",
  },
  {
    title: "Detroit Dark Red Beets",
    category: "Vegetables",
    subCategory: "beet",
    photo: "/images/product-images/beet.webp",
  },
  {
    title: "Golden Beets",
    category: "Vegetables",
    subCategory: "beet",
    photo: "/images/product-images/beet.webp",
  },
  {
    title: "Chioggia Beet (Candy Stripe Beet)",
    category: "Vegetables",
    subCategory: "beet",
    photo: "/images/product-images/beet.webp",
  },
  {
    title: "Bulls Blood Beets",
    category: "Vegetables",
    subCategory: "beet",
    photo: "/images/product-images/beet.webp",
  },
  {
    title: "Cylindra Beets",
    category: "Vegetables",
    subCategory: "beet",
    photo: "/images/product-images/beet.webp",
  },
  {
    title: "Burpee's Golden Beets",
    category: "Vegetables",
    subCategory: "beet",
    photo: "/images/product-images/beet.webp",
  },
  {
    title: "Early Wonder Beets",
    category: "Vegetables",
    subCategory: "beet",
    photo: "/images/product-images/beet.webp",
  },
  {
    title: "Merlin Beets",
    category: "Vegetables",
    subCategory: "beet",
    photo: "/images/product-images/beet.webp",
  },
  {
    title: "Ruby Queen Beets",
    category: "Vegetables",
    subCategory: "beet",
    photo: "/images/product-images/beet.webp",
  },
  {
    title: "Touchstone Gold Beets",
    category: "Vegetables",
    subCategory: "beet",
    photo: "/images/product-images/beet.webp",
  },
  {
    title: "Avalanche Beets",
    category: "Vegetables",
    subCategory: "beet",
    photo: "/images/product-images/beet.webp",
  },
  {
    title: "Badger Flame Beets",
    category: "Vegetables",
    subCategory: "beet",
    photo: "/images/product-images/beet.webp",
  },
  {
    title: "Blankoma Beets",
    category: "Vegetables",
    subCategory: "beet",
    photo: "/images/product-images/beet.webp",
  },
  {
    title: "Crosby Egyptian Beets",
    category: "Vegetables",
    subCategory: "beet",
    photo: "/images/product-images/beet.webp",
  },
  {
    title: "Early Wonder Tall Top Beets",
    category: "Vegetables",
    subCategory: "beet",
    photo: "/images/product-images/beet.webp",
  },
  {
    title: "Formanova Beets",
    category: "Vegetables",
    subCategory: "beet",
    photo: "/images/product-images/beet.webp",
  },
  {
    title: "Lutz Green Leaf Beets",
    category: "Vegetables",
    subCategory: "beet",
    photo: "/images/product-images/beet.webp",
  },
  {
    title: "Red Ace Beets",
    category: "Vegetables",
    subCategory: "beet",
    photo: "/images/product-images/beet.webp",
  },
  {
    title: "Red Cloud Beets",
    category: "Vegetables",
    subCategory: "beet",
    photo: "/images/product-images/beet.webp",
  },
  {
    title: "White Albino Beets",
    category: "Vegetables",
    subCategory: "beet",
    photo: "/images/product-images/beet.webp",
  },
  {
    title: "Hass Avacados",
    category: "Fruits",
    subCategory: "avacado",
    photo: "/images/product-images/avocado.webp",
  },
  {
    title: "Fuerte Avacados",
    category: "Fruits",
    subCategory: "avacado",
    photo: "/images/product-images/avocado.webp",
  },
  {
    title: "Reed Avacados",
    category: "Fruits",
    subCategory: "avacado",
    photo: "/images/product-images/avocado.webp",
  },
  {
    title: "Bacon Avacados",
    category: "Fruits",
    subCategory: "avacado",
    photo: "/images/product-images/avocado.webp",
  },
  {
    title: "Zutano Avacados",
    category: "Fruits",
    subCategory: "avacado",
    photo: "/images/product-images/avocado.webp",
  },
  {
    title: "Gwen Avacados",
    category: "Fruits",
    subCategory: "avacado",
    photo: "/images/product-images/avocado.webp",
  },
  {
    title: "Pinkerton Avacados",
    category: "Fruits",
    subCategory: "avacado",
    photo: "/images/product-images/avocado.webp",
  },
  {
    title: "Lamb Hass Avacados",
    category: "Fruits",
    subCategory: "avacado",
    photo: "/images/product-images/avocado.webp",
  },
  {
    title: "Sharwil Avacados",
    category: "Fruits",
    subCategory: "avacado",
    photo: "/images/product-images/avocado.webp",
  },
  {
    title: "Brogdon Avacados",
    category: "Fruits",
    subCategory: "avacado",
    photo: "/images/product-images/avocado.webp",
  },
  {
    title: "Blueberries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/blueberry.webp",
  },
  {
    title: "Raspberries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/raspberry.webp",
  },
  {
    title: "Blackberries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/blackberry.webp",
  },
  {
    title: "Cranberries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/cranberry.webp",
  },
  {
    title: "Goji Berries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/goji-berry.webp",
  },
  {
    title: "Acai Berries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/acai-berry.webp",
  },
  {
    title: "Elderberries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/elderberry.webp",
  },
  {
    title: "Mulberries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/mulberry.webp",
  },
  {
    title: "Huckleberries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/huckleberry.webp",
  },
  {
    title: "Salmonberries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/salmonberry.webp",
  },
  {
    title: "Marionberries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/blackberry.webp",
  },
  {
    title: "Currant Berries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/currant-berry.webp",
  },
  {
    title: "White Mulberries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/whtmul.webp",
  },
  {
    title: "Beautyberries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/beautyb.webp",
  },
  {
    title: "Bearberries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/buffb.webp",
  },
  {
    title: "Snowberries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/snowb.webp",
  },
  {
    title: "Calafate Berries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/calafate.webp",
  },
  {
    title: "Chehalem Blackberries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/Boysenberry.webp",
  },
  {
    title: "Clingstone Thornless Blackberries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/Boysenberry.webp",
  },
  {
    title: "Cutleaf Blackberries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/Boysenberry.webp",
  },
  {
    title: "Garden Blackberries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/Boysenberry.webp",
  },
  {
    title: "Himalayan Blackberries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/Boysenberry.webp",
  },
  {
    title: "Natchez Blackberries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/Boysenberry.webp",
  },
  {
    title: "Triple Crown Blackberries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/Boysenberry.webp",
  },
  {
    title: "Waldo Berries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/aronian.webp",
  },
  {
    title: "Hardy Kiwis",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/hkiwi.webp",
  },
  {
    title: "Olallieberries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/olallie.webp",
  },
  {
    title: "Thimbleberries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/thimbleberry.webp",
  },
  {
    title: "Bananaberries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/aronian.webp",
  },
  {
    title: "Cape Gooseberries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/capegoose.webp",
  },
  {
    title: "Barberries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/barberry.webp",
  },
  {
    title: "Buffaloberries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/buffb.webp",
  },
  {
    title: "Salal Berries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/aronia.webp",
  },
  {
    title: "Seaberries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/seaber.webp",
  },
  {
    title: "Strawberry Tree Berries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/strawtree.webp",
  },
  {
    title: "Youngberries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/youngber.webp",
  },
  {
    title: "Partridgeberries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/partridgeb.webp",
  },
  {
    title: "Debbaneh Berrieies",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/aronia.webp",
  },
  {
    title: "Tropical Berries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/tropicber.webp",
  },
  {
    title: "Raisinberries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/aronia.webp",
  },
  {
    title: "Chokeberries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/aronia.webp",
  },
  {
    title: "Boysenberries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/Boysenberry.webp",
  },
  {
    title: "Saskatoon Berries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/aronia.webp",
  },
  {
    title: "Juneberries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/aronia.webp",
  },
  {
    title: "Serviceberries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/serviceb.webp",
  },
  {
    title: "Cloud Berries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/cloudberries.webp",
  },
  {
    title: "Aronia Berries",
    category: "Fruits",
    subCategory: "Berry",
    photo: "/images/product-images/aronia.webp",
  },
  {
    title: "Cilantro",
    category: "herbs and spices",
    subCategory: "green",
    photo: "/images/product-images/cilantro.webp",
  },
  {
    title: "Parsley",
    category: "herbs and spices",
    subCategory: "green",
    photo: "/images/product-images/parsley.webp",
  },
  {
    title: "Mint",
    category: "herbs and spices",
    subCategory: "green",
    photo: "/images/product-images/mint.webp",
  },
  {
    title: "Thyme",
    category: "herbs and spices",
    subCategory: "green",
    photo: "/images/product-images/thyme.webp",
  },
  {
    title: "Oregano",
    category: "herbs and spices",
    subCategory: "green",
    photo: "/images/product-images/oregano.webp",
  },
  {
    title: "Rosemary",
    category: "herbs and spices",
    subCategory: "green",
    photo: "/images/product-images/rosemary.webp",
  },
  {
    title: "Sage",
    category: "herbs and spices",
    subCategory: "green",
    photo: "/images/product-images/sage.webp",
  },
  {
    title: "Chives",
    category: "herbs and spices",
    subCategory: "green",
    photo: "/images/product-images/chives.webp",
  },
  {
    title: "Dill",
    category: "herbs and spices",
    subCategory: "green",
    photo: "/images/product-images/dill.webp",
  },
  {
    title: "Borage",
    category: "herbs and spices",
    subCategory: "green",
    photo: "/images/product-images/borage.webp",
  },
  {
    title: "Culantro",
    category: "herbs and spices",
    subCategory: "green",
    photo: "/images/product-images/cullantro.webp",
  },
  {
    title: "Lemongrass",
    category: "herbs and spices",
    subCategory: "green",
    photo: "/images/product-images/lemongrass.webp",
  },
  {
    title: "Lavender",
    category: "herbs and spices",
    subCategory: "green",
    photo: "/images/product-images/lavender.webp",
  },
  {
    title: "Fennel",
    category: "herbs and spices",
    subCategory: "green",
    photo: "/images/product-images/fennel.webp",
  },
  {
    title: "Tarragon",
    category: "herbs and spices",
    subCategory: "green",
    photo: "/images/product-images/tarragon.webp",
  },
  {
    title: "Marjoram",
    category: "herbs and spices",
    subCategory: "green",
    photo: "/images/product-images/marjoram.webp",
  },
  {
    title: "Cress",
    category: "herbs and spices",
    subCategory: "green",
    photo: "/images/product-images/cress.webp",
  },
  {
    title: "Savory",
    category: "herbs and spices",
    subCategory: "green",
    photo: "/images/product-images/savory.webp",
  },
  {
    title: "Bay Leaf",
    category: "herbs and spices",
    subCategory: "green",
    photo: "/images/product-images/bayleaf.webp",
  },
  {
    title: "Watermelon",
    category: "Fruits",
    subCategory: "melon",
    photo: "/images/product-images/watermel.webp",
  },
  {
    title: "Cantaloupe",
    category: "Fruits",
    subCategory: "melon",
    photo: "/images/product-images/cantaloupe.webp",
  },
  {
    title: "Honeydew Melon",
    category: "Fruits",
    subCategory: "melon",
    photo: "/images/product-images/honeydew.webp",
  },
  {
    title: "Casaba Melon",
    category: "Fruits",
    subCategory: "melon",
    photo: "/images/product-images/spritemel.webp",
  },
  {
    title: "Crenshaw Melon",
    category: "Fruits",
    subCategory: "melon",
    photo: "/images/product-images/spritemel.webp",
  },
  {
    title: "Canary Melon",
    category: "Fruits",
    subCategory: "melon",
    photo: "/images/product-images/spritemel.webp",
  },
  {
    title: "Persian Melon",
    category: "Fruits",
    subCategory: "melon",
    photo: "/images/product-images/spritemel.webp",
  },
  {
    title: "Galia Melon",
    category: "Fruits",
    subCategory: "melon",
    photo: "/images/product-images/spritemel.webp",
  },
  {
    title: "Piel de Sapo Melon",
    category: "Fruits",
    subCategory: "melon",
    photo: "/images/product-images/spritemel.webp",
  },
  {
    title: "Golden Dewlicious Melon",
    category: "Fruits",
    subCategory: "melon",
    photo: "/images/product-images/spritemel.webp",
  },
  {
    title: "Winter Melon",
    category: "Fruits",
    subCategory: "melon",
    photo: "/images/product-images/spritemel.webp",
  },
  {
    title: "Hamigua Melon",
    category: "Fruits",
    subCategory: "melon",
    photo: "/images/product-images/spritemel.webp",
  },
  {
    title: "Bitter Melon",
    category: "Fruits",
    subCategory: "melon",
    photo: "/images/product-images/spritemel.webp",
  },
  {
    title: "Preserve Melon",
    category: "Fruits",
    subCategory: "melon",
    photo: "/images/product-images/spritemel.webp",
  },
  {
    title: "Kiwano Melon",
    category: "Fruits",
    subCategory: "melon",
    photo: "/images/product-images/spritemel.webp",
  },
  {
    title: "Santa Claus Melon",
    category: "Fruits",
    subCategory: "melon",
    photo: "/images/product-images/spritemel.webp",
  },
  {
    title: "Sprite Melon",
    category: "Fruits",
    subCategory: "melon",
    photo: "/images/product-images/spritemel.webp",
  },
  {
    title: "Galia Melon",
    category: "Fruits",
    subCategory: "melon",
    photo: "/images/product-images/spritemel.webp",
  },
  {
    title: "Dragon Fruits",
    category: "Fruits",
    subCategory: "fruit",
    photo: "/images/product-images/dragonFruits.webp",
  },
  {
    title: "Kiwano",
    category: "Fruits",
    subCategory: "fruit",
    photo: "/images/product-images/kiwano.webp",
  },
  {
    title: "Star Fruits",
    category: "Fruits",
    subCategory: "fruit",
    photo: "/images/product-images/star.webp",
  },
  {
    title: "Durian",
    category: "Fruits",
    subCategory: "fruit",
    photo: "/images/product-images/durian.webp",
  },
  {
    title: "JackFruits",
    category: "Fruits",
    subCategory: "fruit",
    photo: "/images/product-images/jackFruits.webp",
  },
  {
    title: "Rambutan",
    category: "Fruits",
    subCategory: "fruit",
    photo: "/images/product-images/rambutan.webp",
  },
  {
    title: "Mangosteen",
    category: "Fruits",
    subCategory: "fruit",
    photo: "/images/product-images/mangosteen.webp",
  },
  {
    title: "Passion Fruits",
    category: "Fruits",
    subCategory: "fruit",
    photo: "/images/product-images/passion.webp",
  },
  {
    title: "Papaya",
    category: "Fruits",
    subCategory: "fruit",
    photo: "/images/product-images/papaya.webp",
  },
  {
    title: "Guava",
    category: "Fruits",
    subCategory: "fruit",
    photo: "/images/product-images/guava.webp",
  },
  {
    title: "Lychee",
    category: "Fruits",
    subCategory: "fruit",
    photo: "/images/product-images/lychee.webp",
  },
  {
    title: "Açaí",
    category: "Fruits",
    subCategory: "fruit",
    photo: "/images/product-images/acai.webp",
  },
  {
    title: "Pitaya, Dragon Fruits",
    category: "Fruits",
    subCategory: "fruit",
    photo: "/images/product-images/dragonFruits.webp",
  },
  {
    title: "Feijoa",
    category: "Fruits",
    subCategory: "fruit",
    photo: "/images/product-images/feijoa.webp",
  },
  {
    title: "Chayote",
    category: "Vegetables",
    subCategory: "fruit",
    photo: "/images/product-images/chayote.webp",
  },
  {
    title: "Yuca",
    category: "Vegetables",
    subCategory: "vegetable",
    photo: "/images/product-images/yuca.webp",
  },
  {
    title: "Jícama",
    category: "Vegetables",
    subCategory: "vegetable",
    photo: "/images/product-images/jicama.webp",
  },
  {
    title: "Salsify",
    category: "Vegetables",
    subCategory: "vegetable",
    photo: "/images/product-images/salsify.webp",
  },
  {
    title: "Parsnip",
    category: "Vegetables",
    subCategory: "vegetable",
    photo: "/images/product-images/sprouts.webp",
  },
  {
    title: "Bok Choy",
    category: "Vegetables",
    subCategory: "vegetable",
    photo: "/images/product-images/sprouts.webp",
  },
  {
    title: "Bean Sprouts",
    category: "seeds",
    subCategory: "shoot",
    photo: "/images/product-images/sprouts.webp",
  },
  {
    title: "Alfalfa Sprouts",
    category: "seeds",
    subCategory: "shoot",
    photo: "/images/product-images/sprouts.webp",
  },
  {
    title: "Mung Bean Sprouts",
    category: "seeds",
    subCategory: "shoot",
    photo: "/images/product-images/sprouts.webp",
  },
  {
    title: "Broccoli Sprouts",
    category: "seeds",
    subCategory: "shoot",
    photo: "/images/product-images/sprouts.webp",
  },
  {
    title: "Radish Sprouts",
    category: "seeds",
    subCategory: "shoot",
    photo: "/images/product-images/sprouts.webp",
  },
  {
    title: "Pea Shoots",
    category: "seeds",
    subCategory: "shoot",
    photo: "/images/product-images/sprouts.webp",
  },
  {
    title: "Sunflower Shoots",
    category: "seeds",
    subCategory: "shoot",
    photo: "/images/product-images/sprouts.webp",
  },
  {
    title: "Wheatgrass",
    category: "seeds",
    subCategory: "shoot",
    photo: "/images/product-images/sprouts.webp",
  },
  {
    title: "Arugula Sprouts",
    category: "seeds",
    subCategory: "shoot",
    photo: "/images/product-images/sprouts.webp",
  },
  {
    title: "Clover Sprouts",
    category: "seeds",
    subCategory: "shoot",
    photo: "/images/product-images/sprouts.webp",
  },
  {
    title: "Lentil Sprouts",
    category: "seeds",
    subCategory: "shoot",
    photo: "/images/product-images/sprouts.webp",
  },
  {
    title: "Fenugreek Sprouts",
    category: "seeds",
    subCategory: "shoot",
    photo: "/images/product-images/sprouts.webp",
  },
  {
    title: "Kale Sprouts",
    category: "seeds",
    subCategory: "shoot",
    photo: "/images/product-images/sprouts.webp",
  },
  {
    title: "Chia Sprouts",
    category: "seeds",
    subCategory: "shoot",
    photo: "/images/product-images/sprouts.webp",
  },
  {
    title: "Bamboo Shoots",
    category: "seeds",
    subCategory: "shoot",
    photo: "/images/product-images/sprouts.webp",
  },
  {
    title: "Soybean Sprouts",
    category: "seeds",
    subCategory: "shoot",
    photo: "/images/product-images/sprouts.webp",
  },
  {
    title: "Cabbage Sprouts",
    category: "seeds",
    subCategory: "shoot",
    photo: "/images/product-images/sprouts.webp",
  },
  {
    title: "Mustard Sprouts",
    category: "seeds",
    subCategory: "shoot",
    photo: "/images/product-images/sprouts.webp",
  },
  {
    title: "Celery Sprouts",
    category: "seeds",
    subCategory: "shoot",
    photo: "/images/product-images/sprouts.webp",
  },
  {
    title: "Onion Sprouts",
    category: "seeds",
    subCategory: "shoot",
    photo: "/images/product-images/sprouts.webp",
  },
  {
    title: "Potato",
    category: "Vegetables",
    subCategory: "tuber",
    photo: "/images/product-images/potat.webp",
  },
  {
    title: "Sweet Potato",
    category: "Vegetables",
    subCategory: "tuber",
    photo: "/images/product-images/yam.webp",
  },
  {
    title: "Yam",
    category: "Vegetables",
    subCategory: "tuber",
    photo: "/images/product-images/yam.webp",
  },
  {
    title: "Cassava",
    category: "Vegetables",
    subCategory: "tuber",
    photo: "/images/product-images/tubers.webp",
  },
  {
    title: "Taro",
    category: "Vegetables",
    subCategory: "tuber",
    photo: "/images/product-images/tubers.webp",
  },
  {
    title: "Jicama",
    category: "Vegetables",
    subCategory: "tuber",
    photo: "/images/product-images/tubers.webp",
  },
  {
    title: "Jerusalem Artichoke",
    category: "Vegetables",
    subCategory: "tuber",
    photo: "/images/product-images/tubers.webp",
  },
  {
    title: "Rutabaga",
    category: "Vegetables",
    subCategory: "tuber",
    photo: "/images/product-images/tubers.webp",
  },
  {
    title: "Sunchokes",
    category: "Vegetables",
    subCategory: "tuber",
    photo: "/images/product-images/tubers.webp",
  },
  {
    title: "Chinese Artichoke",
    category: "Vegetables",
    subCategory: "tuber",
    photo: "/images/product-images/tubers.webp",
  },
  {
    title: "Arracacha",
    category: "Vegetables",
    subCategory: "tuber",
    photo: "/images/product-images/tubers.webp",
  },
  {
    title: "Oca",
    category: "Vegetables",
    subCategory: "tuber",
    photo: "/images/product-images/tubers.webp",
  },
  {
    title: "Crosne",
    category: "Vegetables",
    subCategory: "tuber",
    photo: "/images/product-images/tubers.webp",
  },
  {
    title: "Chayote",
    category: "Vegetables",
    subCategory: "tuber",
    photo: "/images/product-images/tubers.webp",
  },
  {
    title: "Malanga",
    category: "Vegetables",
    subCategory: "tuber",
    photo: "/images/product-images/tubers.webp",
  },
  {
    title: "Konjac",
    category: "Vegetables",
    subCategory: "tuber",
    photo: "/images/product-images/tubers.webp",
  },
  {
    title: "Tiquisque",
    category: "Vegetables",
    subCategory: "tuber",
    photo: "/images/product-images/tubers.webp",
  },
  {
    title: "Dasheen",
    category: "Vegetables",
    subCategory: "tuber",
    photo: "/images/product-images/tubers.webp",
  },
  {
    title: "Plectranthus",
    category: "Vegetables",
    subCategory: "tuber",
    photo: "/images/product-images/tubers.webp",
  },
  {
    title: "Chufa",
    category: "Vegetables",
    subCategory: "tuber",
    photo: "/images/product-images/tubers.webp",
  },
  {
    title: "Garlic",
    category: "Vegetables",
    subCategory: "allium",
    photo: "/images/product-images/garlic.webp",
  },
  {
    title: "Onion",
    category: "Vegetables",
    subCategory: "allium",
    photo: "/images/product-images/onion.webp",
  },
  {
    title: "Leek",
    category: "Vegetables",
    subCategory: "allium",
    photo: "/images/product-images/leek.webp",
  },
  {
    title: "Scallion",
    category: "Vegetables",
    subCategory: "allium",
    photo: "/images/product-images/scallion.webp",
  },
  {
    title: "Chives",
    category: "Vegetables",
    subCategory: "allium",
    photo: "/images/product-images/chives.webp",
  },
  {
    title: "Shallot",
    category: "Vegetables",
    subCategory: "allium",
    photo: "/images/product-images/onion.webp",
  },
  {
    title: "Spring Onion",
    category: "Vegetables",
    subCategory: "allium",
    photo: "/images/product-images/onion.webp",
  },
  {
    title: "Elephant Garlic",
    category: "Vegetables",
    subCategory: "allium",
    photo: "/images/product-images/garlic.webp",
  },
  {
    title: "Pearl Onion",
    category: "Vegetables",
    subCategory: "allium",
    photo: "/images/product-images/onion.webp",
  },
  {
    title: "Ramps",
    category: "Vegetables",
    subCategory: "allium",
    photo: "/images/product-images/onion.webp",
  },
  {
    title: "Welsh Onion",
    category: "Vegetables",
    subCategory: "allium",
    photo: "/images/product-images/onion.webp",
  },
  {
    title: "Egyptian Walking Onion",
    category: "Vegetables",
    subCategory: "allium",
    photo: "/images/product-images/onion.webp",
  },
  {
    title: "Tree Onion",
    category: "Vegetables",
    subCategory: "allium",
    photo: "/images/product-images/onion.webp",
  },
  {
    title: "Evergreen Bunching Onion",
    category: "Vegetables",
    subCategory: "allium",
    photo: "/images/product-images/onion.webp",
  },
  {
    title: "Cipollini Onion",
    category: "Vegetables",
    subCategory: "allium",
    photo: "/images/product-images/onion.webp",
  },
  {
    title: "Red Onion",
    category: "Vegetables",
    subCategory: "allium",
    photo: "/images/product-images/onion.webp",
  },
  {
    title: "Yellow Onion",
    category: "Vegetables",
    subCategory: "allium",
    photo: "/images/product-images/onion.webp",
  },
  {
    title: "White Onion",
    category: "Vegetables",
    subCategory: "allium",
    photo: "/images/product-images/onion.webp",
  },
  {
    title: "Vidalia Onion",
    category: "Vegetables",
    subCategory: "allium",
    photo: "/images/product-images/onion.webp",
  },
  {
    title: "Boiling Onion",
    category: "Vegetables",
    subCategory: "allium",
    photo: "/images/product-images/onion.webp",
  },
  {
    title: "Green Pea",
    category: "Legumes",
    subCategory: "Peas",
    photo: "/images/product-images/beans.webp",
  },
  {
    title: "Snow Pea",
    category: "Legumes",
    subCategory: "Peas",
    photo: "/images/product-images/beans.webp",
  },
  {
    title: "Sugar Snap Pea",
    category: "Legumes",
    subCategory: "Peas",
    photo: "/images/product-images/beans.webp",
  },
  {
    title: "Black-Eyed Pea",
    category: "Legumes",
    subCategory: "Peas",
    photo: "/images/product-images/beans.webp",
  },
  {
    title: "Yellow Pea",
    category: "Legumes",
    subCategory: "Peas",
    photo: "/images/product-images/beans.webp",
  },
  {
    title: "Split Pea",
    category: "Legumes",
    subCategory: "Peas",
    photo: "/images/product-images/beans.webp",
  },
  {
    title: "Chickpea",
    category: "Legumes",
    subCategory: "Peas",
    photo: "/images/product-images/beans.webp",
  },
  {
    title: "Black Chickpea",
    category: "Legumes",
    subCategory: "Peas",
    photo: "/images/product-images/beans.webp",
  },
  {
    title: "Green Chickpea",
    category: "Legumes",
    subCategory: "Peas",
    photo: "/images/product-images/beans.webp",
  },
  {
    title: "Pigeon Pea",
    category: "Legumes",
    subCategory: "Peas",
    photo: "/images/product-images/beans.webp",
  },
  {
    title: "Field Pea",
    category: "Legumes",
    subCategory: "Peas",
    photo: "/images/product-images/beans.webp",
  },
  {
    title: "Crowder Pea",
    category: "Legumes",
    subCategory: "Peas",
    photo: "/images/product-images/beans.webp",
  },
  {
    title: "Purple Hull Pea",
    category: "Legumes",
    subCategory: "Peas",
    photo: "/images/product-images/beans.webp",
  },
  {
    title: "Cowpea",
    category: "Legumes",
    subCategory: "Peas",
    photo: "/images/product-images/beans.webp",
  },
  {
    title: "Garden Pea",
    category: "Legumes",
    subCategory: "Peas",
    photo: "/images/product-images/beans.webp",
  },
  {
    title: "Edible-Podded Pea",
    category: "Legumes",
    subCategory: "Peas",
    photo: "/images/product-images/beans.webp",
  },
  {
    title: "Alderman Pea",
    category: "Legumes",
    subCategory: "Peas",
    photo: "/images/product-images/beans.webp",
  },
  {
    title: "Tom Thumb Pea",
    category: "Legumes",
    subCategory: "Peas",
    photo: "/images/product-images/beans.webp",
  },
  {
    title: "Butter Pea",
    category: "Legumes",
    subCategory: "Peas",
    photo: "/images/product-images/beans.webp",
  },
  {
    title: "Snap Pea",
    category: "Legumes",
    subCategory: "Peas",
    photo: "/images/product-images/beans.webp",
  },
  {
    title: "Green Bean",
    category: "Legumes",
    subCategory: "Beans",
    photo: "/images/product-images/beans.webp",
  },
  {
    title: "Kidney Bean",
    category: "Legumes",
    subCategory: "Beans",
    photo: "/images/product-images/beans.webp",
  },
  {
    title: "Black Bean",
    category: "Legumes",
    subCategory: "Beans",
    photo: "/images/product-images/beans.webp",
  },
  {
    title: "Pinto Bean",
    category: "Legumes",
    subCategory: "Beans",
    photo: "/images/product-images/beans.webp",
  },
  {
    title: "Navy Bean",
    category: "Legumes",
    subCategory: "Beans",
    photo: "/images/product-images/beans.webp",
  },
  {
    title: "Lima Bean",
    category: "Legumes",
    subCategory: "Beans",
    photo: "/images/product-images/beans.webp",
  },
  {
    title: "Garbanzo Bean",
    category: "Legumes",
    subCategory: "Beans",
    photo: "/images/product-images/beans.webp",
  },
  {
    title: "Fava Bean",
    category: "Legumes",
    subCategory: "Beans",
    photo: "/images/product-images/beans.webp",
  },
  {
    title: "Cannellini Bean",
    category: "Legumes",
    subCategory: "Beans",
    photo: "/images/product-images/beans.webp",
  },
  {
    title: "Great Northern Bean",
    category: "Legumes",
    subCategory: "Beans",
    photo: "/images/product-images/beans.webp",
  },
  {
    title: "Black-Eyed Pea",
    category: "Legumes",
    subCategory: "Beans",
    photo: "/images/product-images/beans.webp",
  },
  {
    title: "Adzuki Bean",
    category: "Legumes",
    subCategory: "Beans",
    photo: "/images/product-images/beans.webp",
  },
  {
    title: "Red Bean",
    category: "Legumes",
    subCategory: "Beans",
    photo: "/images/product-images/beans.webp",
  },
  {
    title: "Cranberry Bean",
    category: "Legumes",
    subCategory: "Beans",
    photo: "/images/product-images/beans.webp",
  },
  {
    title: "Mung Bean",
    category: "Legumes",
    subCategory: "Beans",
    photo: "/images/product-images/beans.webp",
  },
  {
    title: "Lentil",
    category: "Legumes",
    subCategory: "Beans",
    photo: "/images/product-images/beans.webp",
  },
  {
    title: "Chickpea",
    category: "Legumes",
    subCategory: "Beans",
    photo: "/images/product-images/beans.webp",
  },
  {
    title: "Black-Eyed Pea",
    category: "Legumes",
    subCategory: "Beans",
    photo: "/images/product-images/beans.webp",
  },
  {
    title: "Split Pea",
    category: "Legumes",
    subCategory: "Beans",
    photo: "/images/product-images/beans.webp",
  },
  {
    title: "Lima Bean",
    category: "Legumes",
    subCategory: "Beans",
    photo: "/images/product-images/beans.webp",
  },
  {
    title: "Butternut Squash",
    category: "Vegetables",
    subCategory: "squash",
    photo: "/images/product-images/squash.webp",
  },
  {
    title: "Acorn Squash",
    category: "Vegetables",
    subCategory: "squash",
    photo: "/images/product-images/squash.webp",
  },
  {
    title: "Spaghetti Squash",
    category: "Vegetables",
    subCategory: "squash",
    photo: "/images/product-images/squash.webp",
  },
  {
    title: "Yellow Squash",
    category: "Vegetables",
    subCategory: "squash",
    photo: "/images/product-images/squash.webp",
  },
  {
    title: "Delicata Squash",
    category: "Vegetables",
    subCategory: "squash",
    photo: "/images/product-images/squash.webp",
  },
  {
    title: "Kabocha Squash",
    category: "Vegetables",
    subCategory: "squash",
    photo: "/images/product-images/squash.webp",
  },
  {
    title: "Hubbard Squash",
    category: "Vegetables",
    subCategory: "squash",
    photo: "/images/product-images/squash.webp",
  },
  {
    title: "Buttercup Squash",
    category: "Vegetables",
    subCategory: "squash",
    photo: "/images/product-images/squash.webp",
  },
  {
    title: "Carnival Squash",
    category: "Vegetables",
    subCategory: "squash",
    photo: "/images/product-images/squash.webp",
  },
  {
    title: "Pattypan Squash",
    category: "Vegetables",
    subCategory: "squash",
    photo: "/images/product-images/squash.webp",
  },
  {
    title: "Crookneck Squash",
    category: "Vegetables",
    subCategory: "squash",
    photo: "/images/product-images/squash.webp",
  },
  {
    title: "Straightneck Squash",
    category: "Vegetables",
    subCategory: "squash",
    photo: "/images/product-images/squash.webp",
  },
  {
    title: "Sweet Dumpling Squash",
    category: "Vegetables",
    subCategory: "squash",
    photo: "/images/product-images/squash.webp",
  },
  {
    title: "Golden Nugget Squash",
    category: "Vegetables",
    subCategory: "squash",
    photo: "/images/product-images/squash.webp",
  },
  {
    title: "Hubbard Squash",
    category: "Vegetables",
    subCategory: "squash",
    photo: "/images/product-images/squash.webp",
  },
  {
    title: "Tromboncino Squash",
    category: "Vegetables",
    subCategory: "squash",
    photo: "/images/product-images/squash.webp",
  },
  {
    title: "Tatume Squash",
    category: "Vegetables",
    subCategory: "squash",
    photo: "/images/product-images/squash.webp",
  },
  {
    title: "Calabaza Squash",
    category: "Vegetables",
    subCategory: "squash",
    photo: "/images/product-images/squash.webp",
  },
  {
    title: "Banana Squash",
    category: "Vegetables",
    subCategory: "squash",
    photo: "/images/product-images/squash.webp",
  },
  {
    title: "Dill Pickles",
    category: "Vegetables",
    subCategory: "pickle",
    photo: "/images/product-images/pickle.webp",
  },
  {
    title: "Sweet Pickles",
    category: "Vegetables",
    subCategory: "pickle",
    photo: "/images/product-images/pickle.webp",
  },
  {
    title: "Bread and Butter Pickles",
    category: "Vegetables",
    subCategory: "pickle",
    photo: "/images/product-images/pickle.webp",
  },
  {
    title: "Bell Peppers",
    category: "Vegetables",
    subCategory: "pepper",
    photo: "/images/product-images/bellpep.webp",
  },
  {
    title: "Jalapeno Peppers",
    category: "Vegetables",
    subCategory: "pepper",
    photo: "/images/product-images/jalapeno.webp",
  },
  {
    title: "Habanero Peppers",
    category: "Vegetables",
    subCategory: "pepper",
    photo: "/images/product-images/habanero.webp",
  },
  {
    title: "Cayenne Peppers",
    category: "Vegetables",
    subCategory: "pepper",
    photo: "/images/product-images/thaichili.webp",
  },
  {
    title: "Anaheim Peppers",
    category: "Vegetables",
    subCategory: "pepper",
    photo: "/images/product-images/pepper.webp",
  },
  {
    title: "Poblano Peppers",
    category: "Vegetables",
    subCategory: "pepper",
    photo: "/images/product-images/pablo.webp",
  },
  {
    title: "Fresno Peppers",
    category: "Vegetables",
    subCategory: "pepper",
    photo: "/images/product-images/fresno.webp",
  },
  {
    title: "Chipotle Peppers",
    category: "Vegetables",
    subCategory: "pepper",
    photo: "/images/product-images/chipotlepep.webp",
  },
  {
    title: "Serrano Peppers",
    category: "Vegetables",
    subCategory: "pepper",
    photo: "/images/product-images/Serranos.webp",
  },
  {
    title: "Banana Peppers",
    category: "Vegetables",
    subCategory: "pepper",
    photo: "/images/product-images/bananapep.webp",
  },
  {
    title: "Thai Chili Peppers",
    category: "Vegetables",
    subCategory: "pepper",
    photo: "/images/product-images/thaichili.webp",
  },
  {
    title: "Bird's Eye Peppers",
    category: "Vegetables",
    subCategory: "pepper",
    photo: "/images/product-images/pepper.webp",
  },
  {
    title: "Cubanelle Peppers",
    category: "Vegetables",
    subCategory: "pepper",
    photo: "/images/product-images/pepper.webp",
  },
  {
    title: "Carolina Reaper Peppers",
    category: "Vegetables",
    subCategory: "pepper",
    photo: "/images/product-images/carolina.webp",
  },
  {
    title: "Ghost Peppers",
    category: "Vegetables",
    subCategory: "pepper",
    photo: "/images/product-images/Ghost-pepper.webp",
  },
  {
    title: "Scotch Bonnet Peppers",
    category: "Vegetables",
    subCategory: "pepper",
    photo: "/images/product-images/pepper.webp",
  },
  {
    title: "Aji Amarillo Peppers",
    category: "Vegetables",
    subCategory: "pepper",
    photo: "/images/product-images/pepper.webp",
  },
  {
    title: "Peperoncini Peppers",
    category: "Vegetables",
    subCategory: "pepper",
    photo: "/images/product-images/peperon.webp",
  },
  {
    title: "Shishito Peppers",
    category: "Vegetables",
    subCategory: "pepper",
    photo: "/images/product-images/pepper.webp",
  },
  {
    title: "Iceberg Lettuce",
    category: "Vegetables",
    subCategory: "lettuce",
    photo: "/images/product-images/iceberg.webp",
  },
  {
    title: "Romaine Lettuce",
    category: "Vegetables",
    subCategory: "lettuce",
    photo: "/images/product-images/Romaine.webp",
  },
  {
    title: "Butterhead Lettuce",
    category: "Vegetables",
    subCategory: "lettuce",
    photo: "/images/product-images/lettuce.webp",
  },
  {
    title: "Leaf Lettuce",
    category: "Vegetables",
    subCategory: "lettuce",
    photo: "/images/product-images/lettuce.webp",
  },
  {
    title: "Red Leaf Lettuce",
    category: "Vegetables",
    subCategory: "lettuce",
    photo: "/images/product-images/lettuce.webp",
  },
  {
    title: "Green Leaf Lettuce",
    category: "Vegetables",
    subCategory: "lettuce",
    photo: "/images/product-images/lettuce.webp",
  },
  {
    title: "Boston Lettuce",
    category: "Vegetables",
    subCategory: "lettuce",
    photo: "/images/product-images/lettuce.webp",
  },
  {
    title: "Summer Crisp Lettuce",
    category: "Vegetables",
    subCategory: "lettuce",
    photo: "/images/product-images/lettuce.webp",
  },
  {
    title: "Batavia Lettuce",
    category: "Vegetables",
    subCategory: "lettuce",
    photo: "/images/product-images/lettuce.webp",
  },
  {
    title: "Arugula Lettuce",
    category: "Vegetables",
    subCategory: "lettuce",
    photo: "/images/product-images/Arugula.webp",
  },
  {
    title: "Frisee Lettuce",
    category: "Vegetables",
    subCategory: "lettuce",
    photo: "/images/product-images/lettuce.webp",
  },
  {
    title: "Oak Leaf Lettuce",
    category: "Vegetables",
    subCategory: "lettuce",
    photo: "/images/product-images/lettuce.webp",
  },
  {
    title: "Crisphead Lettuce",
    category: "Vegetables",
    subCategory: "lettuce",
    photo: "/images/product-images/lettuce.webp",
  },
  {
    title: "Endive Lettuce",
    category: "Vegetables",
    subCategory: "lettuce",
    photo: "/images/product-images/lettuce.webp",
  },
  {
    title: "Escarole Lettuce",
    category: "Vegetables",
    subCategory: "lettuce",
    photo: "/images/product-images/lettuce.webp",
  },
  {
    title: "Radichetta Lettuce",
    category: "Vegetables",
    subCategory: "lettuce",
    photo: "/images/product-images/lettuce.webp",
  },
  {
    title: "Tango Lettuce",
    category: "Vegetables",
    subCategory: "lettuce",
    photo: "/images/product-images/lettuce.webp",
  },
  {
    title: "Lollo Rosso Lettuce",
    category: "Vegetables",
    subCategory: "lettuce",
    photo: "/images/product-images/lettuce.webp",
  },
  {
    title: "Red Batavia Lettuce",
    category: "Vegetables",
    subCategory: "lettuce",
    photo: "/images/product-images/lettuce.webp",
  },
  {
    title: "Salanova Lettuce",
    category: "Vegetables",
    subCategory: "lettuce",
    photo: "/images/product-images/lettuce.webp",
  },
  {
    title: "Beef",
    category: "Meats",
    subCategory: "",
    photo: "/images/product-images/beef.webp",
  },
  {
    title: "Pork",
    category: "Meats",
    subCategory: "",
    photo: "/images/product-images/pork.webp",
  },
  {
    title: "Chicken",
    category: "Meats",
    subCategory: "",
    photo: "/images/product-images/chicken.webp",
  },
  {
    title: "Turkey",
    category: "Meats",
    subCategory: "",
    photo: "/images/product-images/turkey.webp",
  },
  {
    title: "Lamb",
    category: "Meats",
    subCategory: "",
    photo: "/images/product-images/lamb.webp",
  },
  {
    title: "Duck",
    category: "Meats",
    subCategory: "",
    photo: "/images/product-images/duck.webp",
  },
  {
    title: "Bison",
    category: "Meats",
    subCategory: "",
    photo: "/images/product-images/bison.webp",
  },
  {
    title: "Rabbit",
    category: "Meats",
    subCategory: "",
    photo: "/images/product-images/rabbit.webp",
  },
  {
    title: "Quail",
    category: "Meats",
    subCategory: "",
    photo: "/images/product-images/quail.webp",
  },
  {
    title: "Venison",
    category: "Meats",
    subCategory: "",
    photo: "/images/product-images/venison.webp",
  },
  {
    title: "Goose",
    category: "Meats",
    subCategory: "",
    photo: "/images/product-images/goose.webp",
  },
  {
    title: "Pheasant",
    category: "Meats",
    subCategory: "",
    photo: "/images/product-images/Pheasant.webp",
  },
  {
    title: "Wild Boar",
    category: "Meats",
    subCategory: "",
    photo: "/images/product-images/boar.webp",
  },
  {
    title: "Emu",
    category: "Meats",
    subCategory: "",
    photo: "/images/product-images/emu.webp",
  },
  {
    title: "Ostrich",
    category: "Meats",
    subCategory: "",
    photo: "/images/product-images/ostrich.webp",
  },
  {
    title: "Alligator",
    category: "Meats",
    subCategory: "",
    photo: "/images/product-images/Alligator.webp",
  },
  {
    title: "Frog",
    category: "Meats",
    subCategory: "",
    photo: "/images/product-images/frogleg.webp",
  },
  {
    title: "Milk",
    category: "Dairy",
    subCategory: "milk",
    photo: "/images/product-images/milk.webp",
  },
  {
    title: "Whole Milk",
    category: "Dairy",
    subCategory: "milk",
    photo: "/images/product-images/milk.webp",
  },
  {
    title: "2% Milk",
    category: "Dairy",
    subCategory: "milk",
    photo: "/images/product-images/milk.webp",
  },
  {
    title: "Heavy Whipping Cream",
    category: "Dairy",
    subCategory: "milk",
    photo: "/images/product-images/cream.webp",
  },
  {
    title: "Cheese",
    category: "Dairy",
    subCategory: "Cheese",
    photo: "/images/product-images/cheese.webp",
  },
  {
    title: "Yogurt",
    category: "Dairy",
    subCategory: "milk product",
    photo: "/images/product-images/yogurt.webp",
  },
  {
    title: "Butter",
    category: "Dairy",
    subCategory: "milk product",
    photo: "/images/product-images/butter.webp",
  },
  {
    title: "Cream",
    category: "Dairy",
    subCategory: "milk",
    photo: "/images/product-images/cream.webp",
  },
  {
    title: "Ice Cream",
    category: "Dairy",
    subCategory: "milk product",
    photo: "/images/product-images/icecream.webp",
  },
  {
    title: "Almonds",
    category: "Nuts",
    subCategory: "",
    photo: "/images/product-images/almond.webp",
  },
  {
    title: "Walnuts",
    category: "Nuts",
    subCategory: "",
    photo: "/images/product-images/walnut.webp",
  },
  {
    title: "Cashews",
    category: "Nuts",
    subCategory: "",
    photo: "/images/product-images/cashew.webp",
  },
  {
    title: "Pistachios",
    category: "Nuts",
    subCategory: "",
    photo: "/images/product-images/pistachio.webp",
  },
  {
    title: "Hazelnuts",
    category: "Nuts",
    subCategory: "",
    photo: "/images/product-images/hazel.webp",
  },
  {
    title: "Peanuts",
    category: "Nuts",
    subCategory: "",
    photo: "/images/product-images/peanuts.webp",
  },
  {
    title: "Baguette",
    category: "Bread",
    subCategory: "",
    photo: "/images/product-images/baguette.webp",
  },
  {
    title: "Sourdough",
    category: "Bread",
    subCategory: "",
    photo: "/images/product-images/sourdough.webp",
  },
  {
    title: "Whole Wheat",
    category: "Bread",
    subCategory: "",
    photo: "/images/product-images/whole_wheat.webp",
  },
  {
    title: "Rye Bread",
    category: "Bread",
    subCategory: "",
    photo: "/images/product-images/rye_bread.webp",
  },
  {
    title: "Ciabatta",
    category: "Bread",
    subCategory: "",
    photo: "/images/product-images/ciabatta.webp",
  },
  {
    title: "Multigrain",
    category: "Bread",
    subCategory: "",
    photo: "/images/product-images/multigrain.webp",
  },
  {
    title: "Olive Oil",
    category: "Oils",
    subCategory: "",
    photo: "/images/product-images/oil.webp",
  },
  {
    title: "Coconut Oil",
    category: "Oils",
    subCategory: "",
    photo: "/images/product-images/oil.webp",
  },
  {
    title: "Canola Oil",
    category: "Oils",
    subCategory: "",
    photo: "/images/product-images/oil.webp",
  },
  {
    title: "Sesame Oil",
    category: "Oils",
    subCategory: "",
    photo: "/images/product-images/oil.webp",
  },
  {
    title: "Sunflower Oil",
    category: "Oils",
    subCategory: "",
    photo: "/images/product-images/oil.webp",
  },
  {
    title: "Avocado Oil",
    category: "Oils",
    subCategory: "",
    photo: "/images/product-images/oil.webp",
  },
  {
    title: "Rice",
    category: "Grains",
    subCategory: "",
    photo: "/images/product-images/rice.webp",
  },
  {
    title: "Quinoa",
    category: "Grains",
    subCategory: "",
    photo: "/images/product-images/millet.webp",
  },
  {
    title: "Oats",
    category: "Grains",
    subCategory: "",
    photo: "/images/product-images/oats.webp",
  },
  {
    title: "Barley",
    category: "Grains",
    subCategory: "",
    photo: "/images/product-images/barley.webp",
  },
  {
    title: "Bulgur",
    category: "Grains",
    subCategory: "",
    photo: "/images/product-images/millet.webp",
  },
  {
    title: "Millet",
    category: "Grains",
    subCategory: "",
    photo: "/images/product-images/millet.webp",
  },
  {
    title: "Chocolate",
    category: "Sweets",
    subCategory: "",
    photo: "/images/product-images/chocolate.webp",
  },
  {
    title: "Cookies",
    category: "Sweets",
    subCategory: "",
    photo: "/images/product-images/cookies.webp",
  },
  {
    title: "Cake",
    category: "Sweets",
    subCategory: "",
    photo: "/images/product-images/cake.webp",
  },
  {
    title: "Gummies",
    category: "Sweets",
    subCategory: "",
    photo: "/images/product-images/gummies.webp",
  },
];

const getlistings = async () => {
  const response = await fetch(`/api/listing/listingSuggestionsCreate/`);
  const data = await response.json();
  console.log(data);
  const formattedListings = data.listings.map((product: any) => ({
    title: product.title,
    subCategory: product.subCategory,
    photo: "",
    category: product.category,
  }));
  return [...defaultProducts, ...formattedListings];
};

export const getProducts = getlistings();
